CLASS z2ui5_cl_http_handler DEFINITION PUBLIC INHERITING FROM z2ui5_cl_UI5_http_handler.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.

ENDCLASS.

CLASS z2ui5_cl_http_handler IMPLEMENTATION.

ENDCLASS.
