CLASS ltcl_test_db DEFINITION FINAL FOR TESTING
  DURATION LONG
  RISK LEVEL DANGEROUS.

  PUBLIC SECTION.

    INTERFACES z2ui5_if_app.
    DATA mr_data TYPE REF TO data ##NEEDED.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS ltcl_test_db IMPLEMENTATION.


  METHOD z2ui5_if_app~main.

  ENDMETHOD.

ENDCLASS.
