const pool = {};
pool['icon_abap'] = new abap.types.Character(4, {});
pool['icon_abap'].set('ICON');
pool['icon_address'] = new abap.types.Character(4, {});
pool['icon_address'].set('ICON');
pool['icon_adopt'] = new abap.types.Character(4, {});
pool['icon_adopt'].set('ICON');
pool['icon_arrow_left'] = new abap.types.Character(4, {});
pool['icon_arrow_left'].set('ICON');
pool['icon_arrow_right'] = new abap.types.Character(4, {});
pool['icon_arrow_right'].set('ICON');
pool['icon_ben_current_benefits'] = new abap.types.Character(4, {});
pool['icon_ben_current_benefits'].set('ICON');
pool['icon_biw_report'] = new abap.types.Character(4, {});
pool['icon_biw_report'].set('ICON');
pool['icon_biw_source_sys_r3'] = new abap.types.Character(4, {});
pool['icon_biw_source_sys_r3'].set('ICON');
pool['icon_businav_process'] = new abap.types.Character(4, {});
pool['icon_businav_process'].set('ICON');
pool['icon_change'] = new abap.types.Character(4, {});
pool['icon_change'].set('ICON');
pool['icon_change_text'] = new abap.types.Character(4, {});
pool['icon_change_text'].set('ICON');
pool['icon_check'] = new abap.types.Character(4, {});
pool['icon_check'].set('ICON');
pool['icon_checked'] = new abap.types.Character(4, {});
pool['icon_checked'].set('ICON');
pool['icon_client_breakpoint'] = new abap.types.Character(4, {});
pool['icon_client_breakpoint'].set('ICON');
pool['icon_compare'] = new abap.types.Character(4, {});
pool['icon_compare'].set('ICON');
pool['icon_complete'] = new abap.types.Character(4, {});
pool['icon_complete'].set('ICON');
pool['icon_connect'] = new abap.types.Character(4, {});
pool['icon_connect'].set('ICON');
pool['icon_copy_object'] = new abap.types.Character(4, {});
pool['icon_copy_object'].set('ICON');
pool['icon_create'] = new abap.types.Character(4, {});
pool['icon_create'].set('ICON');
pool['icon_database_table'] = new abap.types.Character(4, {});
pool['icon_database_table'].set('ICON');
pool['icon_delete'] = new abap.types.Character(4, {});
pool['icon_delete'].set('ICON');
pool['icon_delete_favorites'] = new abap.types.Character(4, {});
pool['icon_delete_favorites'].set('ICON');
pool['icon_delete_row'] = new abap.types.Character(4, {});
pool['icon_delete_row'].set('ICON');
pool['icon_delete_template'] = new abap.types.Character(4, {});
pool['icon_delete_template'].set('ICON');
pool['icon_delivery_inbound'] = new abap.types.Character(4, {});
pool['icon_delivery_inbound'].set('ICON');
pool['icon_deselect_all'] = new abap.types.Character(4, {});
pool['icon_deselect_all'].set('ICON');
pool['icon_detail'] = new abap.types.Character(4, {});
pool['icon_detail'].set('ICON');
pool['icon_display'] = new abap.types.Character(4, {});
pool['icon_display'].set('ICON');
pool['icon_display_more'] = new abap.types.Character(4, {});
pool['icon_display_more'].set('ICON');
pool['icon_display_text'] = new abap.types.Character(4, {});
pool['icon_display_text'].set('ICON');
pool['icon_document'] = new abap.types.Character(4, {});
pool['icon_document'].set('ICON');
pool['icon_element'] = new abap.types.Character(4, {});
pool['icon_element'].set('ICON');
pool['icon_execute_object'] = new abap.types.Character(4, {});
pool['icon_execute_object'].set('ICON');
pool['icon_export'] = new abap.types.Character(4, {});
pool['icon_export'].set('ICON');
pool['icon_field_with_text'] = new abap.types.Character(4, {});
pool['icon_field_with_text'].set('ICON');
pool['icon_foreign_key'] = new abap.types.Character(4, {});
pool['icon_foreign_key'].set('ICON');
pool['icon_generate'] = new abap.types.Character(4, {});
pool['icon_generate'].set('ICON');
pool['icon_green_light'] = new abap.types.Character(4, {});
pool['icon_green_light'].set('ICON');
pool['icon_hint'] = new abap.types.Character(4, {});
pool['icon_hint'].set('ICON');
pool['icon_history'] = new abap.types.Character(4, {});
pool['icon_history'].set('ICON');
pool['icon_host'] = new abap.types.Character(4, {});
pool['icon_host'].set('ICON');
pool['icon_htm'] = new abap.types.Character(4, {});
pool['icon_htm'].set('ICON');
pool['icon_incoming_object'] = new abap.types.Character(4, {});
pool['icon_incoming_object'].set('ICON');
pool['icon_incomplete'] = new abap.types.Character(4, {});
pool['icon_incomplete'].set('ICON');
pool['icon_information'] = new abap.types.Character(4, {});
pool['icon_information'].set('ICON');
pool['icon_insert_row'] = new abap.types.Character(4, {});
pool['icon_insert_row'].set('ICON');
pool['icon_led_green'] = new abap.types.Character(4, {});
pool['icon_led_green'].set('ICON');
pool['icon_led_inactive'] = new abap.types.Character(4, {});
pool['icon_led_inactive'].set('ICON');
pool['icon_led_red'] = new abap.types.Character(4, {});
pool['icon_led_red'].set('ICON');
pool['icon_led_yellow'] = new abap.types.Character(4, {});
pool['icon_led_yellow'].set('ICON');
pool['icon_list'] = new abap.types.Character(4, {});
pool['icon_list'].set('ICON');
pool['icon_mass_change'] = new abap.types.Character(4, {});
pool['icon_mass_change'].set('ICON');
pool['icon_message_critical'] = new abap.types.Character(4, {});
pool['icon_message_critical'].set('ICON');
pool['icon_message_error_small'] = new abap.types.Character(4, {});
pool['icon_message_error_small'].set('ICON');
pool['icon_message_information'] = new abap.types.Character(4, {});
pool['icon_message_information'].set('ICON');
pool['icon_message_question'] = new abap.types.Character(4, {});
pool['icon_message_question'].set('ICON');
pool['icon_message_warning_small'] = new abap.types.Character(4, {});
pool['icon_message_warning_small'].set('ICON');
pool['icon_move'] = new abap.types.Character(4, {});
pool['icon_move'].set('ICON');
pool['icon_next_object'] = new abap.types.Character(4, {});
pool['icon_next_object'].set('ICON');
pool['icon_no_status'] = new abap.types.Character(4, {});
pool['icon_no_status'].set('ICON');
pool['icon_object_list'] = new abap.types.Character(4, {});
pool['icon_object_list'].set('ICON');
pool['icon_okay'] = new abap.types.Character(4, {});
pool['icon_okay'].set('ICON');
pool['icon_org_unit'] = new abap.types.Character(4, {});
pool['icon_org_unit'].set('ICON');
pool['icon_outgoing_object'] = new abap.types.Character(4, {});
pool['icon_outgoing_object'].set('ICON');
pool['icon_package_standard'] = new abap.types.Character(4, {});
pool['icon_package_standard'].set('ICON');
pool['icon_parameter_result'] = new abap.types.Character(4, {});
pool['icon_parameter_result'].set('ICON');
pool['icon_plant'] = new abap.types.Character(4, {});
pool['icon_plant'].set('ICON');
pool['icon_pm_insert'] = new abap.types.Character(4, {});
pool['icon_pm_insert'].set('ICON');
pool['icon_pm_press'] = new abap.types.Character(4, {});
pool['icon_pm_press'].set('ICON');
pool['icon_previous_object'] = new abap.types.Character(4, {});
pool['icon_previous_object'].set('ICON');
pool['icon_profit_center'] = new abap.types.Character(4, {});
pool['icon_profit_center'].set('ICON');
pool['icon_protocol'] = new abap.types.Character(4, {});
pool['icon_protocol'].set('ICON');
pool['icon_question'] = new abap.types.Character(4, {});
pool['icon_question'].set('ICON');
pool['icon_red_light'] = new abap.types.Character(4, {});
pool['icon_red_light'].set('ICON');
pool['icon_refresh'] = new abap.types.Character(4, {});
pool['icon_refresh'].set('ICON');
pool['icon_relation'] = new abap.types.Character(4, {});
pool['icon_relation'].set('ICON');
pool['icon_release'] = new abap.types.Character(4, {});
pool['icon_release'].set('ICON');
pool['icon_resubmission'] = new abap.types.Character(4, {});
pool['icon_resubmission'].set('ICON');
pool['icon_select_all'] = new abap.types.Character(4, {});
pool['icon_select_all'].set('ICON');
pool['icon_select_block'] = new abap.types.Character(4, {});
pool['icon_select_block'].set('ICON');
pool['icon_select_detail'] = new abap.types.Character(4, {});
pool['icon_select_detail'].set('ICON');
pool['icon_set_state'] = new abap.types.Character(4, {});
pool['icon_set_state'].set('ICON');
pool['icon_simulate'] = new abap.types.Character(4, {});
pool['icon_simulate'].set('ICON');
pool['icon_space'] = new abap.types.Character(4, {});
pool['icon_space'].set('ICON');
pool['icon_stack'] = new abap.types.Character(4, {});
pool['icon_stack'].set('ICON');
pool['icon_status_booked'] = new abap.types.Character(4, {});
pool['icon_status_booked'].set('ICON');
pool['icon_status_open'] = new abap.types.Character(4, {});
pool['icon_status_open'].set('ICON');
pool['icon_status_reverse'] = new abap.types.Character(4, {});
pool['icon_status_reverse'].set('ICON');
pool['icon_store_location'] = new abap.types.Character(4, {});
pool['icon_store_location'].set('ICON');
pool['icon_structure'] = new abap.types.Character(4, {});
pool['icon_structure'].set('ICON');
pool['icon_sym_log_server'] = new abap.types.Character(4, {});
pool['icon_sym_log_server'].set('ICON');
pool['icon_system_help'] = new abap.types.Character(4, {});
pool['icon_system_help'].set('ICON');
pool['icon_system_local_paste'] = new abap.types.Character(4, {});
pool['icon_system_local_paste'].set('ICON');
pool['icon_system_okay'] = new abap.types.Character(4, {});
pool['icon_system_okay'].set('ICON');
pool['icon_system_save'] = new abap.types.Character(4, {});
pool['icon_system_save'].set('ICON');
pool['icon_terminated_org_unit'] = new abap.types.Character(4, {});
pool['icon_terminated_org_unit'].set('ICON');
pool['icon_test'] = new abap.types.Character(4, {});
pool['icon_test'].set('ICON');
pool['icon_text_field'] = new abap.types.Character(4, {});
pool['icon_text_field'].set('ICON');
pool['icon_total_left'] = new abap.types.Character(4, {});
pool['icon_total_left'].set('ICON');
pool['icon_transport'] = new abap.types.Character(4, {});
pool['icon_transport'].set('ICON');
pool['icon_variable'] = new abap.types.Character(4, {});
pool['icon_variable'].set('ICON');
pool['icon_warehouse'] = new abap.types.Character(4, {});
pool['icon_warehouse'].set('ICON');
pool['icon_wd_context'] = new abap.types.Character(4, {});
pool['icon_wd_context'].set('ICON');
pool['icon_wd_table'] = new abap.types.Character(4, {});
pool['icon_wd_table'].set('ICON');
pool['icon_wf_workitem_completed'] = new abap.types.Character(4, {});
pool['icon_wf_workitem_completed'].set('ICON');
pool['icon_yellow_light'] = new abap.types.Character(4, {});
pool['icon_yellow_light'].set('ICON');
abap.TypePools['ICON'] = pool;
//# sourceMappingURL=icon.type.mjs.map