{
// openabap.fugr.saplzopenabap.abap


// openabap.fugr.convert_itf_to_stream_text.abap
async function convert_itf_to_stream_text(INPUT) {
                            // importing LF undefined false
                            let lf = INPUT.exporting?.lf;
                            // exporting STREAM_LINES STRING_TABLE true
                            let stream_lines = INPUT.importing?.stream_lines;
                            if (stream_lines === undefined) {
                                                          stream_lines = abap.types.TableFactory.construct(new abap.types.String({qualifiedName: "STRING"}), {"withHeader":false,"keyType":"DEFAULT","primaryKey":{"isUnique":false,"type":"STANDARD","keyFields":[],"name":"primary_key"},"secondary":[]}, "STRING_TABLE");
                                                      }
                                                      // tables ITF_TEXT TLINE false
                                                      let itf_text = INPUT.tables?.itf_text;
                                                      // tables TEXT_STREAM undefined true
                                                      let text_stream = INPUT.tables?.text_stream;
                                                      if (text_stream === undefined) {
                                                                                    text_stream = abap.types.TableFactory.construct(new abap.types.Character(4), {"withHeader":true,"keyType":"DEFAULT"});
                                                                                }
                                                                                abap.statements.clear(stream_lines);
                                                                                abap.statements.clear(text_stream);
                                                                                if (abap.compare.eq(abap.builtin.lines({val: itf_text}), abap.IntegerFactory.get(0))) {
                                                                                                            return;
                                                                                                          }
                                                                                                          abap.statements.assert(abap.compare.eq(new abap.types.Character(4).set('todo'), abap.IntegerFactory.get(1)));
                                                                                                      }
                                                                                                      abap.FunctionModules['CONVERT_ITF_TO_STREAM_TEXT'] = convert_itf_to_stream_text;// openabap.fugr.docu_get.abap
                                                                                                      async function docu_get(INPUT) {
                                                                                                                                // importing ID undefined false
                                                                                                                                let id = INPUT.exporting?.id;
                                                                                                                                // importing LANGU undefined false
                                                                                                                                let langu = INPUT.exporting?.langu;
                                                                                                                                // importing OBJECT undefined false
                                                                                                                                let object = INPUT.exporting?.object;
                                                                                                                                // importing TYP undefined false
                                                                                                                                let typ = INPUT.exporting?.typ;
                                                                                                                                // tables LINE TLINE false
                                                                                                                                let line = INPUT.tables?.line;
                                                                                                                                abap.statements.clear(line);
                                                                                                                                if (abap.compare.eq(id, new abap.types.Character(2).set('NA')) && abap.compare.eq(object, new abap.types.Character(5).set('00001'))) {
                                                                                                                                                          return;
                                                                                                                                                        }
                                                                                                                                                        console.dir(INPUT);
                                                                                                                                                        abap.statements.assert(abap.compare.eq(new abap.types.Character(4).set('todo'), abap.IntegerFactory.get(1)));
                                                                                                                                                      }
                                                                                                                                                      abap.FunctionModules['DOCU_GET'] = docu_get;// openabap.fugr.generate_sec_random.abap
                                                                                                                                                async function generate_sec_random(INPUT) {
                                                                                                                                                                        // importing LENGTH I false
                                                                                                                                                                        let length = INPUT.exporting?.length;
                                                                                                                                                                        // exporting RANDOM XSTRING true
                                                                                                                                                                        let random = INPUT.importing?.random;
                                                                                                                                                                        if (random === undefined) {
                                                                                                                                                                                                  random = new abap.types.XString({qualifiedName: "XSTRING"});
                                                                                                                                                                                              }
                                                                                                                                                                                              abap.statements.assert(abap.compare.gt(length, abap.IntegerFactory.get(0)));
                                                                                                                                                                                              const crypto = await import("crypto");
                                                                                                                                                                                              random.set(crypto.randomBytes(length.get()).toString("hex").toUpperCase());
                                                                                                                                                                                            }
                                                                                                                                                                                            abap.FunctionModules['GENERATE_SEC_RANDOM'] = generate_sec_random;// openabap.fugr.system_callstack.abap
                                                                                                                                                                                async function system_callstack(INPUT) {
                                                                                                                                                                                                      // exporting CALLSTACK ABAP_CALLSTACK true
                                                                                                                                                                                                      let callstack = INPUT.importing?.callstack;
                                                                                                                                                                                                      if (callstack === undefined) {
                                                                                                                                                                                                                              callstack = abap.types.TableFactory.construct(new abap.types.Structure({"mainprogram": new abap.types.Character(40, {}), "include": new abap.types.Character(40, {}), "line": new abap.types.Integer({qualifiedName: "I"}), "blocktype": new abap.types.Character(12, {}), "blockname": new abap.types.String({qualifiedName: "STRING"})}, "ABAP_CALLSTACK_LINE", "ABAP_CALLSTACK_LINE", {}, {}), {"withHeader":false,"keyType":"DEFAULT","primaryKey":{"isUnique":false,"type":"STANDARD","keyFields":[],"name":"primary_key"},"secondary":[]}, "ABAP_CALLSTACK");
                                                                                                                                                                                                                          }
                                                                                                                                                                                                                          let fs_fs_ = new abap.types.FieldSymbol(new abap.types.Structure({"mainprogram": new abap.types.Character(40, {}), "include": new abap.types.Character(40, {}), "line": new abap.types.Integer({qualifiedName: "I"}), "blocktype": new abap.types.Character(12, {}), "blockname": new abap.types.String({qualifiedName: "STRING"})}, "ABAP_CALLSTACK_LINE", "ABAP_CALLSTACK_LINE", {}, {}));
                                                                                                                                                                                                                          fs_fs_.assign(callstack.appendInitial());
                                                                                                                                                                                                                          fs_fs_.get().mainprogram.set(new abap.types.Character(5).set('ZTODO'));
                                                                                                                                                                                                                          fs_fs_.get().include.set(new abap.types.Character(5).set('ZTODO'));
                                                                                                                                                                                                                          fs_fs_.get().line.set(new abap.types.Character(3).set('123'));
                                                                                                                                                                                                                        }
                                                                                                                                                                                                                        abap.FunctionModules['SYSTEM_CALLSTACK'] = system_callstack;// openabap.fugr.get_system_timezone.abap
                                                                                                                                                                                                        async function get_system_timezone(INPUT) {
                                                                                                                                                                                                                            // exporting TIMEZONE TIMEZONE true
                                                                                                                                                                                                                            let timezone = INPUT.importing?.timezone;
                                                                                                                                                                                                                            if (timezone === undefined) {
                                                                                                                                                                                                                                                  timezone = new abap.types.Character(6, {"qualifiedName":"TIMEZONE","ddicName":"TIMEZONE","description":"TIMEZONE"});
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                              timezone.set(new abap.types.Character(3).set('UTC'));
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                            abap.FunctionModules['GET_SYSTEM_TIMEZONE'] = get_system_timezone;// openabap.fugr.function_exists.abap
                                                                                                                                                                                                                        async function function_exists(INPUT) {
                                                                                                                                                                                                                                          // importing FUNCNAME CHAR30 false
                                                                                                                                                                                                                                          let funcname = INPUT.exporting?.funcname;
                                                                                                                                                                                                                                          let lv_name = new abap.types.String({qualifiedName: "STRING"});
                                                                                                                                                                                                                                          let lv_exists = new abap.types.Character(1, {"qualifiedName":"ABAP_BOOL","ddicName":"ABAP_BOOL"});
                                                                                                                                                                                                                                          lv_name.set(funcname);
                                                                                                                                                                                                                                          abap.statements.condense(lv_name, {nogaps: false});
                                                                                                                                                                                                                                          lv_exists.set(abap.FunctionModules[lv_name.get()] === undefined ? " " : "X");
                                                                                                                                                                                                                                          if (abap.compare.eq(lv_exists, abap.builtin.abap_false)) {
                                                                                                                                                                                                                                                            throw new abap.ClassicError({classic: "function_not_exist"});
                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        abap.FunctionModules['FUNCTION_EXISTS'] = function_exists;// openabap.fugr.call_v1_ping.abap
                                                                                                                                                                                                                                async function call_v1_ping(INPUT) {
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                              abap.FunctionModules['CALL_V1_PING'] = call_v1_ping;// openabap.fugr.text_split.abap
                                                                                                                                                                                                                  async function text_split(INPUT) {
                                                                                                                                                                                                                                // importing LENGTH undefined false
                                                                                                                                                                                                                                let length = INPUT.exporting?.length;
                                                                                                                                                                                                                                // importing TEXT undefined false
                                                                                                                                                                                                                                let text = INPUT.exporting?.text;
                                                                                                                                                                                                                                // exporting LINE undefined true
                                                                                                                                                                                                                                let line = INPUT.importing?.line;
                                                                                                                                                                                                                                if (line === undefined) {
                                                                                                                                                                                                                                                line = new abap.types.Character(4);
                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                            // exporting REST undefined true
                                                                                                                                                                                                                                            let rest = INPUT.importing?.rest;
                                                                                                                                                                                                                                            if (rest === undefined) {
                                                                                                                                                                                                                                                            rest = new abap.types.Character(4);
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                        if (abap.compare.lt(abap.builtin.strlen({val: text}), abap.IntegerFactory.get(50))) {
                                                                                                                                                                                                                                                                      line.set(text);
                                                                                                                                                                                                                                                                      rest.set(new abap.types.Character(1).set(''));
                                                                                                                                                                                                                                                                    } else {
                                                                                                                                                                                                                                                                                  line.set(text.getOffset({length: 50}));
                                                                                                                                                                                                                                                                                  rest.set(text.getOffset({offset: 50}));
                                                                                                                                                                                                                                                                                  abap.statements.condense(rest, {nogaps: false});
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                              abap.FunctionModules['TEXT_SPLIT'] = text_split;// openabap.fugr.unit_conversion_simple.abap
                                                                                                                                                                                                                                                async function unit_conversion_simple(INPUT) {
                                                                                                                                                                                                                                                            // importing INPUT undefined false
                                                                                                                                                                                                                                                            let input = INPUT.exporting?.input;
                                                                                                                                                                                                                                                            // importing UNIT_IN MSEHI true
                                                                                                                                                                                                                                                            let unit_in = INPUT.exporting?.unit_in;
                                                                                                                                                                                                                                                            if (unit_in === undefined) {
                                                                                                                                                                                                                                                                          unit_in = new abap.types.Character(3, {"qualifiedName":"MSEHI","ddicName":"MSEHI","description":"UOM"});
                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                      // importing UNIT_OUT MSEHI true
                                                                                                                                                                                                                                                                      let unit_out = INPUT.exporting?.unit_out;
                                                                                                                                                                                                                                                                      if (unit_out === undefined) {
                                                                                                                                                                                                                                                                                    unit_out = new abap.types.Character(3, {"qualifiedName":"MSEHI","ddicName":"MSEHI","description":"UOM"});
                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                // exporting OUTPUT undefined true
                                                                                                                                                                                                                                                                                let output = INPUT.importing?.output;
                                                                                                                                                                                                                                                                                if (output === undefined) {
                                                                                                                                                                                                                                                                                              output = new abap.types.Character(4);
                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                          let lv_float = new abap.types.Float({qualifiedName: "F"});
                                                                                                                                                                                                                                                                                          if (abap.compare.eq(unit_in, unit_out)) {
                                                                                                                                                                                                                                                                                                      output.set(input);
                                                                                                                                                                                                                                                                                                    } else if (abap.compare.eq(unit_in, new abap.types.Character(1).set('G')) && abap.compare.eq(unit_out, new abap.types.Character(2).set('KG'))) {
                                                                                                                                                                                                                                                                                                                output.set(abap.operators.divide(input,new abap.types.Integer().set(1000)));
                                                                                                                                                                                                                                                                                                              } else if (abap.compare.eq(unit_in, new abap.types.Character(2).set('M3')) && abap.compare.eq(unit_out, new abap.types.Character(3).set('CDM'))) {
                                                                                                                                                                                                                                                                                                                          output.set(abap.operators.multiply(input,new abap.types.Integer().set(1000)));
                                                                                                                                                                                                                                                                                                                        } else if (abap.compare.eq(unit_in, new abap.types.Character(2).set('LB')) && abap.compare.eq(unit_out, new abap.types.Character(2).set('KG'))) {
                                                                                                                                                                                                                                                                                                                                    lv_float.set(new abap.types.Character(10).set('0.45359237'));
                                                                                                                                                                                                                                                                                                                                    output.set(abap.operators.multiply(input,lv_float));
                                                                                                                                                                                                                                                                                                                                  } else if (abap.compare.eq(unit_in, new abap.types.Character(3).set('CCM')) && abap.compare.eq(unit_out, new abap.types.Character(3).set('CDM'))) {
                                                                                                                                                                                                                                                                                                                                              output.set(abap.operators.divide(input,new abap.types.Integer().set(1000)));
                                                                                                                                                                                                                                                                                                                                            } else if (abap.compare.eq(unit_in, new abap.types.Character(3).set('FT3')) && abap.compare.eq(unit_out, new abap.types.Character(3).set('CDM'))) {
                                                                                                                                                                                                                                                                                                                                                        lv_float.set(new abap.types.Character(14).set('28.31684660923'));
                                                                                                                                                                                                                                                                                                                                                        output.set(abap.operators.multiply(input,lv_float));
                                                                                                                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                                                                                                                                  abap.statements.assert(abap.compare.eq(abap.IntegerFactory.get(1), abap.IntegerFactory.get(2)));
                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                              abap.FunctionModules['UNIT_CONVERSION_SIMPLE'] = unit_conversion_simple;// openabap.fugr.system_installed_languages.abap
                                                                                                                                                                                                                                                                                                                      async function system_installed_languages(INPUT) {
                                                                                                                                                                                                                                                                                                                                // exporting LANGUAGES undefined true
                                                                                                                                                                                                                                                                                                                                let languages = INPUT.importing?.languages;
                                                                                                                                                                                                                                                                                                                                if (languages === undefined) {
                                                                                                                                                                                                                                                                                                                                            languages = new abap.types.Character(4);
                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                        languages.set(abap.builtin.sy.get().langu);
                                                                                                                                                                                                                                                                                                                                        abap.builtin.sy.get().subrc.set(abap.IntegerFactory.get(0));
                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                      abap.FunctionModules['SYSTEM_INSTALLED_LANGUAGES'] = system_installed_languages;// openabap.fugr.conversion_exit_isola_input.abap
                                                                                                                                                                                                                                                                        async function conversion_exit_isola_input(INPUT) {
                                                                                                                                                                                                                                                                                // importing INPUT undefined false
                                                                                                                                                                                                                                                                                let input = INPUT.exporting?.input;
                                                                                                                                                                                                                                                                                // exporting OUTPUT undefined true
                                                                                                                                                                                                                                                                                let output = INPUT.importing?.output;
                                                                                                                                                                                                                                                                                if (output === undefined) {
                                                                                                                                                                                                                                                                                          output = new abap.types.Character(4);
                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                      output.set((await abap.Classes['CL_I18N_LANGUAGES'].sap2_to_sap1({im_lang_sap2: input})));
                                                                                                                                                                                                                                                                                      if (abap.compare.eq(abap.builtin.sy.get().subrc, abap.IntegerFactory.get(1))) {
                                                                                                                                                                                                                                                                                              throw new abap.ClassicError({classic: "unknown_language"});
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                          abap.FunctionModules['CONVERSION_EXIT_ISOLA_INPUT'] = conversion_exit_isola_input;// openabap.fugr.conversion_exit_isola_output.abap
                                                                                                                                                                                                                        async function conversion_exit_isola_output(INPUT) {
                                                                                                                                                                                                                              // importing INPUT undefined false
                                                                                                                                                                                                                              let input = INPUT.exporting?.input;
                                                                                                                                                                                                                              // exporting OUTPUT undefined true
                                                                                                                                                                                                                              let output = INPUT.importing?.output;
                                                                                                                                                                                                                              if (output === undefined) {
                                                                                                                                                                                                                                      output = new abap.types.Character(4);
                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                        output.set(await abap.Classes['CL_I18N_LANGUAGES'].sap1_to_sap2({im_lang_sap1: input}));
                                                                                                                                                                                                                                        abap.builtin.sy.get().subrc.set(0);
                                                                                                                                                                                                                                      } catch (e) {
                                                                                                                                                                                                                                            if (e.classic) {
                                                                                                                                                                                                                                                    switch (e.classic.toUpperCase()) {
                                                                                                                                                                                                                                                        case "NO_ASSIGNMENT": abap.builtin.sy.get().subrc.set(1); break;
                                                                                                                                                                                                                                                        default: abap.builtin.sy.get().subrc.set(2); break;
                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                      } else {
                                                                                                                                                                                                                                                              throw e;
                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                      abap.FunctionModules['CONVERSION_EXIT_ISOLA_OUTPUT'] = conversion_exit_isola_output;// openabap.fugr.conversion_exit_alpha_input.abap
                                                                                                                                                                            async function conversion_exit_alpha_input(INPUT) {
                                                                                                                                                                                // importing INPUT CLIKE false
                                                                                                                                                                                let input = INPUT.exporting?.input;
                                                                                                                                                                                // exporting OUTPUT CLIKE true
                                                                                                                                                                                let output = INPUT.importing?.output;
                                                                                                                                                                                if (output === undefined) {
                                                                                                                                                                                      output = new abap.types.Character();
                                                                                                                                                                                  }
                                                                                                                                                                                  let lv_len = new abap.types.Integer({qualifiedName: "I"});
                                                                                                                                                                                  let lv_type = new abap.types.Character(1, {});
                                                                                                                                                                                  let lv_tmp = new abap.types.String({qualifiedName: "STRING"});
                                                                                                                                                                                  lv_tmp.set(input);
                                                                                                                                                                                  abap.statements.condense(lv_tmp, {nogaps: false});
                                                                                                                                                                                  abap.statements.describe({field: input, type: lv_type});
                                                                                                                                                                                  if (abap.compare.eq(lv_type, new abap.types.Character(1).set('g')) || abap.compare.eq(lv_type, new abap.types.Character(1).set('D'))) {
                                                                                                                                                                                      abap.statements.describe({field: output, type: lv_type});
                                                                                                                                                                                      if (abap.compare.eq(lv_type, new abap.types.Character(1).set('g')) || abap.compare.eq(lv_type, new abap.types.Character(1).set('D'))) {
                                                                                                                                                                                          output.set(input);
                                                                                                                                                                                          return;
                                                                                                                                                                                        }
                                                                                                                                                                                        abap.statements.describe({field: output, length: lv_len, mode: 'CHARACTER'});
                                                                                                                                                                                      } else {
                                                                                                                                                                                          abap.statements.describe({field: input, length: lv_len, mode: 'CHARACTER'});
                                                                                                                                                                                        }
                                                                                                                                                                                        if (abap.compare.initial(lv_tmp)) {
                                                                                                                                                                                            abap.statements.clear(output);
                                                                                                                                                                                            return;
                                                                                                                                                                                          }
                                                                                                                                                                                          const indexBackup1 = abap.builtin.sy.get().index.get();
                                                                                                                                                                                          const unique34 = abap.operators.minus(lv_len.get(),abap.builtin.strlen({val: lv_tmp}).get()).get();
                                                                                                                                                                                          for (let unique35 = 0; unique35 < unique34; unique35++) {
                                                                                                                                                                                              abap.builtin.sy.get().index.set(unique35 + 1);
                                                                                                                                                                                              lv_tmp.set(abap.operators.concat(new abap.types.String().set(`0`),lv_tmp));
                                                                                                                                                                                            }
                                                                                                                                                                                            abap.builtin.sy.get().index.set(indexBackup1);
                                                                                                                                                                                            output.set(lv_tmp);
                                                                                                                                                                                          }
                                                                                                                                                                                          abap.FunctionModules['CONVERSION_EXIT_ALPHA_INPUT'] = conversion_exit_alpha_input;// openabap.fugr.conversion_exit_alpha_output.abap
                                                                                                    async function conversion_exit_alpha_output(INPUT) {
                                                                                                      // importing INPUT CLIKE false
                                                                                                      let input = INPUT.exporting?.input;
                                                                                                      // exporting OUTPUT CLIKE true
                                                                                                      let output = INPUT.importing?.output;
                                                                                                      if (output === undefined) {
                                                                                                          output = new abap.types.Character();
                                                                                                      }
                                                                                                      output.set(input);
                                                                                                      abap.statements.shift(output, {direction: 'LEFT',deletingLeading: new abap.types.Character(1).set('0')});
                                                                                                      const indexBackup1 = abap.builtin.sy.get().index.get();
                                                                                                      const unique36 = abap.operators.minus(abap.builtin.strlen({val: input}),abap.builtin.strlen({val: output}).get()).get();
                                                                                                      for (let unique37 = 0; unique37 < unique36; unique37++) {
                                                                                                        abap.builtin.sy.get().index.set(unique37 + 1);
                                                                                                        output.set(abap.operators.concat(output,new abap.types.String().set(` `)));
                                                                                                      }
                                                                                                      abap.builtin.sy.get().index.set(indexBackup1);
                                                                                                    }
                                                                                                    abap.FunctionModules['CONVERSION_EXIT_ALPHA_OUTPUT'] = conversion_exit_alpha_output;
}
//# sourceMappingURL=openabap.fugr.mjs.map