CLASS z2ui5_cl_ui_pop_to_confirm DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS Z2UI5_CL_UI_POP_TO_CONFIRM IMPLEMENTATION.
ENDCLASS.
