name: playwright-browser-test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm run init && npm run build
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps && npm i
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
