// The help text of the developer tools - what each tab answers, and the
// entry points.
//
// Discoverability is the real barrier here: a tab that nobody knows
// exists helps nobody, and Ctrl+F12 is not guessable. Kept as text in the
// module tree next to the tabs it describes so it cannot drift into a
// wiki; devtools/Inspect.js re-exports formatHelp for the dialog's (i)
// button. Zero dependencies: it is a string.
sap.ui.define([], () => {
  "use strict";

  const HELP = [
    "abap2UI5 Developer Tools",
    "",
    "Opening",
    "-------",
    "  Ctrl+F12                    open / close these tools",
    "  ?z2ui5-devtools=1           open them on page load (for problems",
    "                              that happen during startup)",
    "  ?z2ui5-devtools=HISTORY     open them directly on a view, by its key",
    "",
    "  Without one named, they reopen where you left off.",
    "",
    "The six tabs, and what each is for",
    "----------------------------------",
    "  Overview      which app, which roundtrip, is anything broken - and",
    "                where to go next. The landing tab",
    "  Problems      what went wrong",
    "  Roundtrips    what went over the wire",
    "  View & Data   what the screen is made of, and what fills it",
    "  System        what the app is running on, and its ABAP class",
    "  Search        one term across EVERY other tab at once - answers",
    "                'where does /CUSTOMER appear?' without opening each",
    "",
    "Problems",
    "--------",
    "  Error         the last fatal error, with Retry / Restart / Logout",
    "  Log           ONE timeline of everything logged: the framework's",
    "                own error log (with stack traces), UI5's log (binding",
    "                and control problems), uncaught errors, unhandled",
    "                rejections, every console.* call, and the backend",
    "                messages the user was shown - so the browser's own",
    "                devtools do not have to be open",
    "",
    "Roundtrips",
    "----------",
    "  History       every roundtrip: backend vs. render time, payload",
    "                sizes, draft ids - and the ones that never rendered",
    "  Request /     the raw JSON on the wire",
    "  Response",
    "  Actions       the response's T_SYSTEM / T_CUSTOM lists, readable",
    "  Model Diff    what the backend changed between two responses",
    "  View Diff     what changed in the view XML between two rebuilds",
    "",
    "  'Record Payloads' keeps the request/response bodies, which is what",
    "  the two diffs need. OFF by default: it is the only part of the",
    "  history that costs real memory (2 MB budget, oldest dropped first).",
    "",
    "View & Data",
    "-----------",
    "  Pick the SLOT on the left (only the filled ones are offered), then",
    "  the aspect:",
    "",
    "  XML           the view XML the slot holds",
    "  Model         the JSON model behind it",
    "  Bindings      the model attributes, '*' on the paths that will",
    "                travel as the next delta, the delta itself, the paths",
    "                bound in the view that the model does NOT have (the",
    "                usual cause of an empty field), and the attributes",
    "                ranked by size (the usual cause of a huge response)",
    "  Picked        'Pick Control' closes these tools, lets you click any",
    "  Control       control in the app, and reports which ABAP attribute",
    "                feeds it with its current value. Escape cancels",
    "",
    "  On an XML view: 'Apply to App' renders the edited XML into the",
    "  running app with NO roundtrip and no activation - a local preview",
    "  the next response replaces again. 'Reset' puts the original back.",
    "",
    "System",
    "------",
    "  Environment   versions, SAPUI5 vs OpenUI5, the SDK url the page",
    "                bootstrapped from and its resource roots, theme,",
    "                language, content density, session, device, the",
    "                focus/scroll block sent on every roundtrip, slots",
    "  Registry      shortcuts, timers, callbacks, bound backend events",
    "  ABAP Source   the running app's class. 'Open in ADT' opens it in a",
    "                new tab, at the line of the last event",
    "",
    "Always available",
    "----------------",
    "  Copy             put the current view's content on the clipboard",
    "  Report a Bug     see below",
    "  (i)              this help",
    "",
    "  'Open on Error' (on Overview) pops these tools open on the Log as",
    "  soon as anything logs at error level. Off by default.",
    "",
    "Reporting a bug",
    "---------------",
    "  'Report a Bug' puts the whole session state on the clipboard as a",
    "  GitHub-ready issue body: environment, the error, the log, the",
    "  roundtrip history and the running app's ABAP class, each in a",
    "  collapsed section. Paste it into an issue as it is.",
    "",
    "  'Export' opens the same content for reading, with downloads. With",
    "  Record Payloads on, Download History (JSON) additionally carries",
    "  the actual request/response bodies.",
    "",
    "  The console errors and the roundtrip history survive a page reload",
    "  (sessionStorage), so an app that died and was reloaded keeps its",
    "  evidence - those rows are marked with a '*'.",
  ].join("\n");

  function formatHelp() {
    return HELP;
  }

  return { formatHelp };
});
