CLASS ltcl_test DEFINITION FINAL FOR TESTING
  DURATION LONG
  RISK LEVEL DANGEROUS.

  PUBLIC SECTION.

    INTERFACES z2ui5_if_app.
    DATA mr_data TYPE REF TO data ##NEEDED.

  PRIVATE SECTION.
    METHODS test_trans_xml FOR TESTING RAISING cx_static_check.
ENDCLASS.


CLASS ltcl_test IMPLEMENTATION.

  METHOD test_trans_xml.



  ENDMETHOD.

  METHOD z2ui5_if_app~main.

  ENDMETHOD.

ENDCLASS.
