* =====================================================================
* GENERATED FILE - DO NOT EDIT (AGENTS.md rule 2)
* Source: app/webapp/cc/Tree.js
* Embedded frontend resource, generated by tools/app2abap/trans2abap.js.
* Change the source file above and run 'npm run app2abap' to regenerate;
* the check_app2abap CI gate fails any manual edit here.
* =====================================================================
CLASS z2ui5_cl_ui5f_tree_js DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CLASS-METHODS get
      RETURNING
        VALUE(result) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS z2ui5_cl_ui5f_tree_js IMPLEMENTATION.

  METHOD get.

    result = `sap.ui.define(` && |\n| &&
             `  [` && |\n| &&
             `    "sap/ui/core/Control",` && |\n| &&
             `    "z2ui5/core/Lib",` && |\n| &&
             `    "z2ui5/core/ViewSlots",` && |\n| &&
             `    "z2ui5/core/AppState",` && |\n| &&
             `  ],` && |\n| &&
             `  (Control, Lib, ViewSlots, AppState) => {` && |\n| &&
             `    "use strict";` && |\n| &&
             `` && |\n| &&
             `    return Control.extend("z2ui5.cc.Tree", {` && |\n| &&
             `      metadata: {` && |\n| &&
             `        properties: {` && |\n| &&
             `          tree_id: {` && |\n| &&
             `            type: "string",` && |\n| &&
             `          },` && |\n| &&
             `        },` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      _getTreeBinding() {` && |\n| &&
             `        const treeControl = ViewSlots.byIdOfOwner(` && |\n| &&
             `          this,` && |\n| &&
             `          this.getProperty("tree_id"),` && |\n| &&
             `        );` && |\n| &&
             `        return treeControl?.getBinding("items");` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      setBackend() {` && |\n| &&
             `        try {` && |\n| &&
             `          const id = this.getProperty("tree_id");` && |\n| &&
             `          if (!id) return;` && |\n| &&
             `          const binding = this._getTreeBinding();` && |\n| &&
             `` && |\n| &&
             `          if (binding) {` && |\n| &&
             `            AppState.state.treeStates[id] = binding.getCurrentTreeState();` && |\n| &&
             `          }` && |\n| &&
             `        } catch (e) {` && |\n| &&
             `          Lib.logError("Tree.setBackend: failed", e);` && |\n| &&
             `        }` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      init() {` && |\n| &&
             `        this._unhook = Lib.hookCallback(` && |\n| &&
             `          this,` && |\n| &&
             `          "onBeforeRoundtrip",` && |\n| &&
             `          "setBackend",` && |\n| &&
             `        );` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      exit() {` && |\n| &&
             `        this._unhook();` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      onAfterRendering() {` && |\n| &&
             `        try {` && |\n| &&
             `          const id = this.getProperty("tree_id");` && |\n| &&
             `          const snapshot = id && AppState.state.treeStates[id];` && |\n| &&
             `          if (!snapshot) return;` && |\n| &&
             `          const binding = this._getTreeBinding();` && |\n| &&
             `          if (!binding) return;` && |\n| &&
             `` && |\n| &&
             `          if (` && |\n| &&
             `            this._appliedSnapshot === snapshot &&` && |\n| &&
             `            this._appliedBinding === binding` && |\n| &&
             `          ) {` && |\n| &&
             `            return;` && |\n| &&
             `          }` && |\n| &&
             `          this._appliedSnapshot = snapshot;` && |\n| &&
             `          this._appliedBinding = binding;` && |\n| &&
             `` && |\n| &&
             `          binding.setTreeState(snapshot);` && |\n| &&
             `          binding.refresh(true);` && |\n| &&
             `        } catch (e) {` && |\n| &&
             `          Lib.logError("Tree.onAfterRendering: setTreeState failed", e);` && |\n| &&
             `        }` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      renderer: {` && |\n| &&
             `        apiVersion: 2,` && |\n| &&
             `        render(oRm, oControl) {` && |\n| &&
             `          Lib.renderInvisibleSpan(oRm, oControl);` && |\n| &&
             `        },` && |\n| &&
             `      },` && |\n| &&
             `    });` && |\n| &&
             `  },` && |\n| &&
             `);` && |\n| &&
             `` && |\n| &&
              ``.

  ENDMETHOD.

ENDCLASS.
