* =====================================================================
* GENERATED FILE - DO NOT EDIT (AGENTS.md rule 2)
* Source: app/webapp/cc/UploadSetExt.js
* Embedded frontend resource, generated by tools/app2abap/trans2abap.js.
* Change the source file above and run 'npm run app2abap' to regenerate;
* the check_app2abap CI gate fails any manual edit here.
* =====================================================================
CLASS z2ui5_cl_ui5f_upldset_js DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CLASS-METHODS get
      RETURNING
        VALUE(result) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS z2ui5_cl_ui5f_upldset_js IMPLEMENTATION.

  METHOD get.

    result = `sap.ui.define(` && |\n| &&
             `  ["sap/ui/core/Control", "z2ui5/core/Lib", "z2ui5/core/ViewSlots"],` && |\n| &&
             `  (Control, Lib, ViewSlots) => {` && |\n| &&
             `    "use strict";` && |\n| &&
             `` && |\n| &&
             `    return Control.extend("z2ui5.cc.UploadSetExt", {` && |\n| &&
             `      metadata: {` && |\n| &&
             `        properties: {` && |\n| &&
             `          uploadSetId: {` && |\n| &&
             `            type: "string",` && |\n| &&
             `          },` && |\n| &&
             `          fileData: {` && |\n| &&
             `            type: "string",` && |\n| &&
             `            defaultValue: "",` && |\n| &&
             `          },` && |\n| &&
             `          fileName: {` && |\n| &&
             `            type: "string",` && |\n| &&
             `            defaultValue: "",` && |\n| &&
             `          },` && |\n| &&
             `          mediaType: {` && |\n| &&
             `            type: "string",` && |\n| &&
             `            defaultValue: "",` && |\n| &&
             `          },` && |\n| &&
             `          fileSize: {` && |\n| &&
             `            type: "string",` && |\n| &&
             `            defaultValue: "",` && |\n| &&
             `          },` && |\n| &&
             `          removedFileName: {` && |\n| &&
             `            type: "string",` && |\n| &&
             `            defaultValue: "",` && |\n| &&
             `          },` && |\n| &&
             `          checkInit: {` && |\n| &&
             `            type: "boolean",` && |\n| &&
             `            defaultValue: false,` && |\n| &&
             `          },` && |\n| &&
             `        },` && |\n| &&
             `        events: {` && |\n| &&
             `          change: {` && |\n| &&
             `            allowPreventDefault: true,` && |\n| &&
             `            parameters: {},` && |\n| &&
             `          },` && |\n| &&
             `          remove: {` && |\n| &&
             `            allowPreventDefault: true,` && |\n| &&
             `            parameters: {},` && |\n| &&
             `          },` && |\n| &&
             `        },` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      init() {` && |\n| &&
             `        this._unhook = Lib.hookCallback(this, "onAfterRendering", "setControl");` && |\n| &&
             `      },` && |\n| &&
             `      exit() {` && |\n| &&
             `        this._unhook();` && |\n| &&
             `        this._detach();` && |\n| &&
             `        if (this._reader) this._reader.cancel();` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      _detach() {` && |\n| &&
             `        const uploadSet = this._target;` && |\n| &&
             `        this._target = null;` && |\n| &&
             `        if (!uploadSet || Lib.isDestroyed(uploadSet)) return;` && |\n| &&
             `        if (this._onItemAdded) {` && |\n| &&
             `          uploadSet.detachAfterItemAdded?.(this._onItemAdded);` && |\n| &&
             `        }` && |\n| &&
             `        if (this._onItemRemoved) {` && |\n| &&
             `          uploadSet.detachAfterItemRemoved?.(this._onItemRemoved);` && |\n| &&
             `        }` && |\n| &&
             `        this._onItemAdded = null;` && |\n| &&
             `        this._onItemRemoved = null;` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      _readFile(file) {` && |\n| &&
             `        if (!this._reader) {` && |\n| &&
             `          this._reader = Lib.readFilesInTurn(` && |\n| &&
             `            this,` && |\n| &&
             `            "UploadSetExt",` && |\n| &&
             `            (f, result) => {` && |\n| &&
             `              this.setProperty("fileData", result, true);` && |\n| &&
             `              this.setProperty("fileName", f.name, true);` && |\n| &&
             `              this.setProperty("mediaType", f.type, true);` && |\n| &&
             `              this.setProperty("fileSize", String(f.size), true);` && |\n| &&
             `              this.fireChange();` && |\n| &&
             `            },` && |\n| &&
             `          );` && |\n| &&
             `        }` && |\n| &&
             `        this._reader.add([file]);` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      onItemAdded(oEvent) {` && |\n| &&
             `        const file = oEvent.getParameter("item")?.getFileObject?.();` && |\n| &&
             `        if (file) this._readFile(file);` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      onItemRemoved(oEvent) {` && |\n| &&
             `        const name = oEvent.getParameter("item")?.getFileName?.() ?? "";` && |\n| &&
             `        this.setProperty("removedFileName", name, true);` && |\n| &&
             `        this.fireRemove();` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      renderer: Lib.EMPTY_RENDERER,` && |\n| &&
             `      setControl() {` && |\n| &&
             `        if (this.getProperty("checkInit")) return;` && |\n| &&
             `        const uploadSet = ViewSlots.byIdOfOwner(` && |\n| &&
             `          this,` && |\n| &&
             `          this.getProperty("uploadSetId"),` && |\n| &&
             `        );` && |\n| &&
             `        if (!Lib.claimOnce(this, uploadSet)) return;` && |\n| &&
             `        try {` && |\n| &&
             `          this._target = uploadSet;` && |\n| &&
             `          this._onItemAdded = this.onItemAdded.bind(this);` && |\n| &&
             `          uploadSet.attachAfterItemAdded(this._onItemAdded);` && |\n| &&
             `` && |\n| &&
             `          if (uploadSet.attachAfterItemRemoved) {` && |\n| &&
             `            this._onItemRemoved = this.onItemRemoved.bind(this);` && |\n| &&
             `            uploadSet.attachAfterItemRemoved(this._onItemRemoved);` && |\n| &&
             `          } else {` && |\n| &&
             `            Lib.logError(` && |\n| &&
             `              "UploadSetExt: afterItemRemoved needs UI5 >= 1.83, removals will not be reported",` && |\n| &&
             `            );` && |\n| &&
             `          }` && |\n| &&
             `        } catch (e) {` && |\n| &&
             `          Lib.logError("UploadSetExt.setControl: setup failed", e);` && |\n| &&
             `        }` && |\n| &&
             `      },` && |\n| &&
             `    });` && |\n| &&
             `  },` && |\n| &&
             `);` && |\n| &&
             `` && |\n| &&
              ``.

  ENDMETHOD.

ENDCLASS.
