* =====================================================================
* GENERATED FILE - DO NOT EDIT (AGENTS.md rule 2)
* Source: app/webapp/core/actions/BindingCall.js
* Embedded frontend resource, generated by tools/app2abap/trans2abap.js.
* Change the source file above and run 'npm run app2abap' to regenerate;
* the check_app2abap CI gate fails any manual edit here.
* =====================================================================
CLASS z2ui5_cl_ui5f_bindcall_js DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CLASS-METHODS get
      RETURNING
        VALUE(result) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS z2ui5_cl_ui5f_bindcall_js IMPLEMENTATION.

  METHOD get.

    result = `sap.ui.define(` && |\n| &&
             `  [` && |\n| &&
             `    "sap/ui/model/Filter",` && |\n| &&
             `    "sap/ui/model/FilterOperator",` && |\n| &&
             `    "sap/ui/model/Sorter",` && |\n| &&
             `    "z2ui5/core/Lib",` && |\n| &&
             `    "z2ui5/core/ViewSlots",` && |\n| &&
             `    "z2ui5/core/actions/ControlCall",` && |\n| &&
             `  ],` && |\n| &&
             `  (Filter, FilterOperator, Sorter, Lib, ViewSlots, ControlCall) => {` && |\n| &&
             `    "use strict";` && |\n| &&
             `` && |\n| &&
             `    const FILTER_OPERATORS = new Set([` && |\n| &&
             `      "BT",` && |\n| &&
             `      "Contains",` && |\n| &&
             `      "EndsWith",` && |\n| &&
             `      "EQ",` && |\n| &&
             `      "GE",` && |\n| &&
             `      "GT",` && |\n| &&
             `      "LE",` && |\n| &&
             `      "LT",` && |\n| &&
             `      "NB",` && |\n| &&
             `      "NE",` && |\n| &&
             `      "NotContains",` && |\n| &&
             `      "NotEndsWith",` && |\n| &&
             `      "NotStartsWith",` && |\n| &&
             `      "StartsWith",` && |\n| &&
             `    ]);` && |\n| &&
             `` && |\n| &&
             `    const isEmpty = (v) => v == null || v === "";` && |\n| &&
             `` && |\n| &&
             `    function buildFilterGroups(binding, json) {` && |\n| &&
             `      let groups = json;` && |\n| &&
             `      if (typeof json === "string") {` && |\n| &&
             `        try {` && |\n| &&
             `          groups = JSON.parse(json);` && |\n| &&
             `        } catch {` && |\n| &&
             `          Lib.logError("BINDING_CALL: malformed filter groups JSON");` && |\n| &&
             `          return;` && |\n| &&
             `        }` && |\n| &&
             `      }` && |\n| &&
             `      if (!Array.isArray(groups)) {` && |\n| &&
             `        Lib.logError("BINDING_CALL: filter groups must be an array");` && |\n| &&
             `        return;` && |\n| &&
             `      }` && |\n| &&
             `      groups = groups.filter((g) => Array.isArray(g) && g.length);` && |\n| &&
             `      if (!groups.length) {` && |\n| &&
             `        binding.filter([]);` && |\n| &&
             `        return;` && |\n| &&
             `      }` && |\n| &&
             `      const outer = [];` && |\n| &&
             `      for (const group of groups) {` && |\n| &&
             `        const inner = [];` && |\n| &&
             `        for (const row of group) {` && |\n| &&
             `          const [path, operator, value1, value2] = Array.isArray(row)` && |\n| &&
             `            ? row` && |\n| &&
             `            : [];` && |\n| &&
             `          if (typeof path !== "string" || !FILTER_OPERATORS.has(operator)) {` && |\n| &&
             `            Lib.logError(` && |\n| &&
             `              ``BINDING_CALL: bad filter row (path '${path}' / operator '${operator}')``,` && |\n| &&
             `            );` && |\n| &&
             `            return;` && |\n| &&
             `          }` && |\n| &&
             `          inner.push(` && |\n| &&
             `            new Filter(path, FilterOperator[operator], value1, value2),` && |\n| &&
             `          );` && |\n| &&
             `        }` && |\n| &&
             `        outer.push(new Filter(inner, false));` && |\n| &&
             `      }` && |\n| &&
             `      binding.filter([new Filter(outer, true)]);` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    const BINDING_METHODS = {` && |\n| &&
             `      filter(binding, params) {` && |\n| &&
             `        const [path, operator, value1, value2] = params;` && |\n| &&
             `` && |\n| &&
             `        if (` && |\n| &&
             `          params.length === 1 &&` && |\n| &&
             `          (Array.isArray(path) ||` && |\n| &&
             `            (typeof path === "string" && path.trimStart().startsWith("[")))` && |\n| &&
             `        ) {` && |\n| &&
             `          buildFilterGroups(binding, path);` && |\n| &&
             `          return;` && |\n| &&
             `        }` && |\n| &&
             `` && |\n| &&
             `        if (isEmpty(value1) && isEmpty(value2)) {` && |\n| &&
             `          binding.filter([]);` && |\n| &&
             `          return;` && |\n| &&
             `        }` && |\n| &&
             `        if (!FILTER_OPERATORS.has(operator)) {` && |\n| &&
             `          Lib.logError(``BINDING_CALL: operator '${operator}' not allowed``);` && |\n| &&
             `          return;` && |\n| &&
             `        }` && |\n| &&
             `        binding.filter([` && |\n| &&
             `          new Filter(path, FilterOperator[operator], value1, value2),` && |\n| &&
             `        ]);` && |\n| &&
             `      },` && |\n| &&
             `      sort(binding, [path, descending, group]) {` && |\n| &&
             `        binding.sort([` && |\n| &&
             `          new Sorter(` && |\n| &&
             `            path,` && |\n| &&
             `            ControlCall.castArg("bool", descending),` && |\n| &&
             `            ControlCall.castArg("bool", group),` && |\n| &&
             `          ),` && |\n| &&
             `        ]);` && |\n| &&
             `      },` && |\n| &&
             `    };` && |\n| &&
             `` && |\n| &&
             `    Object.setPrototypeOf(BINDING_METHODS, null);` && |\n| &&
             `` && |\n| &&
             `    function evBindingCall(oController, args) {` && |\n| &&
             `      const [, id, aggregation, method] = args;` && |\n| &&
             `      const build = BINDING_METHODS[method];` && |\n| &&
             `      if (!build) {` && |\n| &&
             `        Lib.logError(``BINDING_CALL: method '${method}' not allowed``);` && |\n| &&
             `        return;` && |\n| &&
             `      }` && |\n| &&
             `      const binding = ViewSlots.resolveById(oController?.ctx, id)?.getBinding?.(` && |\n| &&
             `        aggregation,` && |\n| &&
             `      );` && |\n| &&
             `      if (!binding || typeof binding[method] !== "function") {` && |\n| &&
             `        Lib.logError(` && |\n| &&
             `          ``BINDING_CALL: no '${aggregation}' binding with '${method}' on control '${id}'``,` && |\n| &&
             `        );` && |\n| &&
             `        return;` && |\n| &&
             `      }` && |\n| &&
             `      build(binding, args.slice(4));` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    const handlers = {` && |\n| &&
             `      BINDING_CALL: evBindingCall,` && |\n| &&
             `    };` && |\n| &&
             `` && |\n| &&
             `    return { handlers };` && |\n| &&
             `  },` && |\n| &&
             `);` && |\n| &&
             `` && |\n| &&
              ``.

  ENDMETHOD.

ENDCLASS.
