* =====================================================================
* GENERATED FILE - DO NOT EDIT (AGENTS.md rule 2)
* Source: app/webapp/cc/Focus.js
* Embedded frontend resource, generated by tools/app2abap/trans2abap.js.
* Change the source file above and run 'npm run app2abap' to regenerate;
* the check_app2abap CI gate fails any manual edit here.
* =====================================================================
CLASS z2ui5_cl_ui5f_focus_js DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CLASS-METHODS get
      RETURNING
        VALUE(result) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS z2ui5_cl_ui5f_focus_js IMPLEMENTATION.

  METHOD get.

    result = `sap.ui.define(` && |\n| &&
             `  ["sap/ui/core/Control", "z2ui5/core/Lib", "z2ui5/core/ViewSlots"],` && |\n| &&
             `  (Control, Lib, ViewSlots) => {` && |\n| &&
             `    "use strict";` && |\n| &&
             `` && |\n| &&
             `    return Control.extend("z2ui5.cc.Focus", {` && |\n| &&
             `      metadata: {` && |\n| &&
             `        properties: {` && |\n| &&
             `          setUpdate: {` && |\n| &&
             `            type: "boolean",` && |\n| &&
             `            defaultValue: true,` && |\n| &&
             `          },` && |\n| &&
             `          focusId: {` && |\n| &&
             `            type: "string",` && |\n| &&
             `          },` && |\n| &&
             `          selectionStart: {` && |\n| &&
             `            type: "string",` && |\n| &&
             `            defaultValue: "0",` && |\n| &&
             `          },` && |\n| &&
             `          selectionEnd: {` && |\n| &&
             `            type: "string",` && |\n| &&
             `            defaultValue: "0",` && |\n| &&
             `          },` && |\n| &&
             `        },` && |\n| &&
             `      },` && |\n| &&
             `      setFocusId(val) {` && |\n| &&
             `        try {` && |\n| &&
             `          this.setProperty("focusId", val, true);` && |\n| &&
             `          const oElement = ViewSlots.byIdOfOwner(this, val);` && |\n| &&
             `          if (oElement) oElement.applyFocusInfo(oElement.getFocusInfo());` && |\n| &&
             `        } catch (e) {` && |\n| &&
             `          Lib.logError("Focus.setFocusId failed", e);` && |\n| &&
             `        }` && |\n| &&
             `      },` && |\n| &&
             `      onBeforeRendering() {` && |\n| &&
             `        this._liveCaret = Lib.readCaret(document.activeElement);` && |\n| &&
             `      },` && |\n| &&
             `      onAfterRendering() {` && |\n| &&
             `        const liveCaret = this._liveCaret;` && |\n| &&
             `        this._liveCaret = null;` && |\n| &&
             `        if (!this._pendingFocus) return;` && |\n| &&
             `        this._pendingFocus = false;` && |\n| &&
             `        const oElement = ViewSlots.byIdOfOwner(` && |\n| &&
             `          this,` && |\n| &&
             `          this.getProperty("focusId"),` && |\n| &&
             `        );` && |\n| &&
             `        if (!oElement) return;` && |\n| &&
             `        try {` && |\n| &&
             `          const info = oElement.getFocusInfo();` && |\n| &&
             `          let start = Number(this.getProperty("selectionStart"));` && |\n| &&
             `          let end = Number(this.getProperty("selectionEnd"));` && |\n| &&
             `` && |\n| &&
             `          const input = this._textInput(oElement);` && |\n| &&
             `          if (input) {` && |\n| &&
             `            const len = (input.value ?? "").length;` && |\n| &&
             `            start = Math.min(Math.max(start, 0), len);` && |\n| &&
             `            end = Math.min(Math.max(end, 0), len);` && |\n| &&
             `` && |\n| &&
             `            if (len > 0) {` && |\n| &&
             `              let liveStart = null;` && |\n| &&
             `              let liveEnd = null;` && |\n| &&
             `              if (input === document.activeElement) {` && |\n| &&
             `                liveStart = input.selectionStart;` && |\n| &&
             `                liveEnd = input.selectionEnd;` && |\n| &&
             `              } else if (liveCaret) {` && |\n| &&
             `                liveStart = liveCaret.start;` && |\n| &&
             `                liveEnd = liveCaret.end;` && |\n| &&
             `              }` && |\n| &&
             `              if (liveStart != null && (liveStart > start || liveEnd > end)) {` && |\n| &&
             `                start = Math.min(Math.max(liveStart, 0), len);` && |\n| &&
             `                end = Math.min(Math.max(liveEnd, 0), len);` && |\n| &&
             `              }` && |\n| &&
             `            }` && |\n| &&
             `          }` && |\n| &&
             `` && |\n| &&
             `          info.selectionStart = start;` && |\n| &&
             `          info.selectionEnd = end;` && |\n| &&
             `          oElement.applyFocusInfo(info);` && |\n| &&
             `        } catch (e) {` && |\n| &&
             `          Lib.logError("Focus.onAfterRendering: applyFocusInfo failed", e);` && |\n| &&
             `        }` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      _textInput(oElement) {` && |\n| &&
             `        try {` && |\n| &&
             `          const ref = oElement.getFocusDomRef?.();` && |\n| &&
             `          if (ref && (ref.tagName === "INPUT" || ref.tagName === "TEXTAREA")) {` && |\n| &&
             `            return ref;` && |\n| &&
             `          }` && |\n| &&
             `          const root = oElement.getDomRef?.();` && |\n| &&
             `          return root?.querySelector?.("input, textarea") || null;` && |\n| &&
             `        } catch {` && |\n| &&
             `          return null;` && |\n| &&
             `        }` && |\n| &&
             `      },` && |\n| &&
             `      renderer: {` && |\n| &&
             `        apiVersion: 2,` && |\n| &&
             `        render(oRm, oControl) {` && |\n| &&
             `          Lib.renderInvisibleSpan(oRm, oControl);` && |\n| &&
             `          if (!oControl.getProperty("setUpdate")) return;` && |\n| &&
             `          oControl.setProperty("setUpdate", false, true);` && |\n| &&
             `          oControl._pendingFocus = true;` && |\n| &&
             `        },` && |\n| &&
             `      },` && |\n| &&
             `    });` && |\n| &&
             `  },` && |\n| &&
             `);` && |\n| &&
             `` && |\n| &&
              ``.

  ENDMETHOD.

ENDCLASS.
