* =====================================================================
* GENERATED FILE - DO NOT EDIT (AGENTS.md rule 2)
* Source: app/webapp/core/Router.js
* Embedded frontend resource, generated by tools/app2abap/trans2abap.js.
* Change the source file above and run 'npm run app2abap' to regenerate;
* the check_app2abap CI gate fails any manual edit here.
* =====================================================================
CLASS z2ui5_cl_ui5f_router_js DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CLASS-METHODS get
      RETURNING
        VALUE(result) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS z2ui5_cl_ui5f_router_js IMPLEMENTATION.

  METHOD get.

    result = `sap.ui.define(` && |\n| &&
             `  ["sap/ui/core/routing/HashChanger", "z2ui5/core/Lib"],` && |\n| &&
             `  (HashChanger, Lib) => {` && |\n| &&
             `    "use strict";` && |\n| &&
             `` && |\n| &&
             `    const APP_ROUTE_PREFIX = "/app/";` && |\n| &&
             `` && |\n| &&
             `    const SHELL_SEPARATOR = "&/";` && |\n| &&
             `` && |\n| &&
             `    function hashChanger() {` && |\n| &&
             `      return HashChanger.getInstance();` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function splitHash(sHash) {` && |\n| &&
             `      const raw = String(sHash || "").replace(/^#/, "");` && |\n| &&
             `` && |\n| &&
             `      if (!raw || raw.startsWith("/")) return { shell: "", app: raw };` && |\n| &&
             `      const i = raw.indexOf(SHELL_SEPARATOR);` && |\n| &&
             `      if (i < 0) return { shell: "", app: raw };` && |\n| &&
             `      let app = raw.slice(i + SHELL_SEPARATOR.length).replace(/^\/+/, "");` && |\n| &&
             `      if (app) app = ``/${app}``;` && |\n| &&
             `      return { shell: raw.slice(0, i), app };` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function appHashOf(sHash) {` && |\n| &&
             `      return splitHash(sHash).app;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function getHash() {` && |\n| &&
             `      return appHashNormalized(hashChanger().getHash());` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function appHashNormalized(sHash) {` && |\n| &&
             `      const app = appHashOf(sHash);` && |\n| &&
             `` && |\n| &&
             `      if (app === "/") return "";` && |\n| &&
             `      return app && !app.startsWith("/") ? ``/${app}`` : app;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function getRawHash() {` && |\n| &&
             `      return String(window.location.hash || "").replace(/^#/, "");` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function patternFor(sClass, sDraftId) {` && |\n| &&
             `      const base = ``${APP_ROUTE_PREFIX}${sClass}``;` && |\n| &&
             `      return sDraftId ? ``${base}/${sDraftId}`` : base;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function segmentsOf(sHash) {` && |\n| &&
             `      const app = appHashOf(sHash).replace(/^\/+/, "");` && |\n| &&
             `      const marker = "app/";` && |\n| &&
             `      if (!app.startsWith(marker)) return null;` && |\n| &&
             `` && |\n| &&
             `      return app.slice(marker.length).split(/[&?]/)[0].split("/");` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function parse(sHash) {` && |\n| &&
             `      const parts = segmentsOf(sHash);` && |\n| &&
             `      if (!parts) return null;` && |\n| &&
             `` && |\n| &&
             `      if (parts[0] === "") {` && |\n| &&
             `        if (parts.length < 3 || !parts[1] || !parts[2]) return null;` && |\n| &&
             `        return {` && |\n| &&
             `          app: ``/${parts[1]}/${parts[2]}``,` && |\n| &&
             `          draft: parts.length > 3 ? parts[3] : "",` && |\n| &&
             `        };` && |\n| &&
             `      }` && |\n| &&
             `      if (!parts[0]) return null;` && |\n| &&
             `      return { app: parts[0], draft: parts.length > 1 ? parts[1] : "" };` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function navTo(sRoute, bReplace) {` && |\n| &&
             `      const sHash = String(sRoute || "").replace(/^\/+/, "");` && |\n| &&
             `      if (bReplace) {` && |\n| &&
             `        hashChanger().replaceHash(sHash);` && |\n| &&
             `      } else {` && |\n| &&
             `        hashChanger().setHash(sHash);` && |\n| &&
             `      }` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function writeHash(ctx, sHash, bPush) {` && |\n| &&
             `      if (bPush) ctx.state.hashPushCount += 1;` && |\n| &&
             `      navTo(sHash, !bPush);` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function writeLegacyUrl(ctx, sSuffix, bPush) {` && |\n| &&
             `      const url = ``${window.location.pathname}${window.location.search}#${getRawHash()}${sSuffix}``;` && |\n| &&
             `      if (bPush) {` && |\n| &&
             `        ctx.state.hashPushCount += 1;` && |\n| &&
             `        history.pushState(null, "", url);` && |\n| &&
             `      } else {` && |\n| &&
             `        history.replaceState(null, "", url);` && |\n| &&
             `      }` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function navBack(ctx, sFallback) {` && |\n| &&
             `      if (!sFallback || ctx.state.hashPushCount > 0) {` && |\n| &&
             `        window.history.back();` && |\n| &&
             `        return;` && |\n| &&
             `      }` && |\n| &&
             `      navTo(sFallback, true);` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function onHashChanged(ctx, sNewHash) {` && |\n| &&
             `      const state = ctx.state;` && |\n| &&
             `` && |\n| &&
             `      if (!state.navRouting) {` && |\n| &&
             `        dispatchAppHashChange(ctx, sNewHash);` && |\n| &&
             `        return;` && |\n| &&
             `      }` && |\n| &&
             `` && |\n| &&
             `      const route = parse(sNewHash);` && |\n| &&
             `      if (!route) return;` && |\n| &&
             `` && |\n| &&
             `      if (route.draft) {` && |\n| &&
             `        if (route.draft === state.currentDraftId) return;` && |\n| &&
             `      } else if (` && |\n| &&
             `        route.app.toUpperCase() === String(state.currentApp).toUpperCase()` && |\n| &&
             `      ) {` && |\n| &&
             `        return;` && |\n| &&
             `      }` && |\n| &&
             `` && |\n| &&
             `      state.navFromHash = true;` && |\n| &&
             `      if (ctx.router.navigate) ctx.router.navigate();` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function applyHashEvent(ctx, mOptions) {` && |\n| &&
             `      if (!mOptions.setHashEvent) return;` && |\n| &&
             `      const state = ctx.state;` && |\n| &&
             `      const sEvent = String(mOptions.setHashEvent).trim();` && |\n| &&
             `      state.hashEvent = sEvent || null;` && |\n| &&
             `` && |\n| &&
             `      state.appHash = appHashNormalized(getRawHash());` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function dispatchAppHashChange(ctx, sNewHash) {` && |\n| &&
             `      const state = ctx.state;` && |\n| &&
             `      if (!state.hashEvent) return;` && |\n| &&
             `      const appHash = appHashNormalized(sNewHash);` && |\n| &&
             `      if (appHash === state.appHash) return;` && |\n| &&
             `      const controller = state.oController;` && |\n| &&
             `      if (!controller || !Lib.isControllerAlive(controller)) return;` && |\n| &&
             `` && |\n| &&
             `      if (state.isBusy) {` && |\n| &&
             `        state.pendingAppHash = sNewHash;` && |\n| &&
             `        return;` && |\n| &&
             `      }` && |\n| &&
             `      state.pendingAppHash = null;` && |\n| &&
             `      state.appHash = appHash;` && |\n| &&
             `      controller.eB([state.hashEvent]);` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function dispatchPendingAppHash(ctx) {` && |\n| &&
             `      const state = ctx.state;` && |\n| &&
             `      const pending = state.pendingAppHash;` && |\n| &&
             `      if (pending === null || pending === undefined) return;` && |\n| &&
             `      state.pendingAppHash = null;` && |\n| &&
             `      dispatchAppHashChange(ctx, pending);` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function repointCallerEntry(ctx, mOptions, draftForRoute) {` && |\n| &&
             `      const state = ctx.state;` && |\n| &&
             `      const prevApp = mOptions.navAppCallPrevApp;` && |\n| &&
             `      const prevDraft = mOptions.navAppCallPrevId;` && |\n| &&
             `      if (!draftForRoute || !prevApp || !prevDraft) return;` && |\n| &&
             `      const prevRoute = patternFor(prevApp, prevDraft);` && |\n| &&
             `      if (getHash() === prevRoute) return;` && |\n| &&
             `` && |\n| &&
             `      state.currentDraftId = prevDraft;` && |\n| &&
             `      navTo(prevRoute, true);` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function applyMode(ctx, mOptions) {` && |\n| &&
             `      if (!mOptions.setNavRouting) return;` && |\n| &&
             `      const mode = String(mOptions.setNavRouting).toUpperCase();` && |\n| &&
             `      const on = mode === "KEEP" || mode === "FRESH";` && |\n| &&
             `      ctx.state.navRouting = on;` && |\n| &&
             `      ctx.state.navMode = on ? mode : null;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function updateAppRoute(ctx, mOptions, ID, app) {` && |\n| &&
             `      const state = ctx.state;` && |\n| &&
             `` && |\n| &&
             `      const draftForRoute = state.navMode === "FRESH" ? null : ID;` && |\n| &&
             `` && |\n| &&
             `      state.currentApp = app;` && |\n| &&
             `      state.currentDraftId = draftForRoute;` && |\n| &&
             `` && |\n| &&
             `      if (state.navFromHash) {` && |\n| &&
             `        state.navFromHash = false;` && |\n| &&
             `        return;` && |\n| &&
             `      }` && |\n| &&
             `      if (mOptions.setPushState || mOptions.setHashReplace) return;` && |\n| &&
             `` && |\n| &&
             `      const route = patternFor(app, draftForRoute);` && |\n| &&
             `      if (mOptions.checkNavAppCall) {` && |\n| &&
             `        repointCallerEntry(ctx, mOptions, draftForRoute);` && |\n| &&
             `        state.currentApp = app;` && |\n| &&
             `        state.currentDraftId = draftForRoute;` && |\n| &&
             `        navTo(route);` && |\n| &&
             `      } else if (getHash() !== route) {` && |\n| &&
             `        navTo(route, true);` && |\n| &&
             `      }` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function sync(ctx, mOptions) {` && |\n| &&
             `      const ID = mOptions.id;` && |\n| &&
             `      try {` && |\n| &&
             `        applyMode(ctx, mOptions);` && |\n| &&
             `        applyHashEvent(ctx, mOptions);` && |\n| &&
             `` && |\n| &&
             `        const state = ctx.state;` && |\n| &&
             `` && |\n| &&
             `        const sAppWrite = mOptions.setPushState || mOptions.setHashReplace;` && |\n| &&
             `        const bPush = Boolean(mOptions.setPushState);` && |\n| &&
             `` && |\n| &&
             `        if (state.navRouting) {` && |\n| &&
             `          const app = state.oResponse?.APP;` && |\n| &&
             `          if (app) updateAppRoute(ctx, mOptions, ID, app);` && |\n| &&
             `` && |\n| &&
             `          if (!sAppWrite) return;` && |\n| &&
             `` && |\n| &&
             `          if (state.currentDraftId) {` && |\n| &&
             `            writeHash(` && |\n| &&
             `              ctx,` && |\n| &&
             `              patternFor(state.currentApp, state.currentDraftId) + sAppWrite,` && |\n| &&
             `              bPush,` && |\n| &&
             `            );` && |\n| &&
             `            return;` && |\n| &&
             `          }` && |\n| &&
             `        }` && |\n| &&
             `` && |\n| &&
             `        if (sAppWrite) {` && |\n| &&
             `          if (state.hashEvent) {` && |\n| &&
             `            state.appHash = appHashNormalized(sAppWrite);` && |\n| &&
             `            writeHash(ctx, sAppWrite, bPush);` && |\n| &&
             `            return;` && |\n| &&
             `          }` && |\n| &&
             `` && |\n| &&
             `          writeLegacyUrl(ctx, sAppWrite, bPush);` && |\n| &&
             `` && |\n| &&
             `          return;` && |\n| &&
             `        }` && |\n| &&
             `` && |\n| &&
             `        if (state.hashEvent) return;` && |\n| &&
             `` && |\n| &&
             `        const newHash = mOptions.setAppStateActive` && |\n| &&
             `          ? ``/z2ui5-xapp-state=${ID || ""}``` && |\n| &&
             `          : "";` && |\n| &&
             `        navTo(newHash, true);` && |\n| &&
             `      } catch (e) {` && |\n| &&
             `        Lib.logError("Router.sync: history update failed", e);` && |\n| &&
             `      }` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function init(ctx, fnNavigate) {` && |\n| &&
             `      ctx.router.navigate = fnNavigate;` && |\n| &&
             `` && |\n| &&
             `      const listener = (oEvent) =>` && |\n| &&
             `        onHashChanged(ctx, oEvent.getParameter("newHash"));` && |\n| &&
             `      ctx.router.hashListener = listener;` && |\n| &&
             `      hashChanger().attachEvent("hashChanged", listener);` && |\n| &&
             `` && |\n| &&
             `      hashChanger().init();` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function exit(ctx) {` && |\n| &&
             `      const listener = ctx.router.hashListener;` && |\n| &&
             `      if (listener) {` && |\n| &&
             `        hashChanger().detachEvent("hashChanged", listener);` && |\n| &&
             `        ctx.router.hashListener = null;` && |\n| &&
             `      }` && |\n| &&
             `      ctx.router.navigate = null;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    return {` && |\n| &&
             `      init,` && |\n| &&
             `      exit,` && |\n| &&
             `      splitHash,` && |\n| &&
             `      patternFor,` && |\n| &&
             `      parse,` && |\n| &&
             `      navTo,` && |\n| &&
             `      navBack,` && |\n| &&
             `      onHashChanged,` && |\n| &&
             `      dispatchPendingAppHash,` && |\n| &&
             `      sync,` && |\n| &&
             `    };` && |\n| &&
             `  },` && |\n| &&
             `);` && |\n| &&
             `` && |\n| &&
              ``.

  ENDMETHOD.

ENDCLASS.
