* =====================================================================
* GENERATED FILE - DO NOT EDIT (AGENTS.md rule 2)
* Source: app/webapp/core/Session.js
* Embedded frontend resource, generated by tools/app2abap/trans2abap.js.
* Change the source file above and run 'npm run app2abap' to regenerate;
* the check_app2abap CI gate fails any manual edit here.
* =====================================================================
CLASS z2ui5_cl_ui5f_session_js DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CLASS-METHODS get
      RETURNING
        VALUE(result) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS z2ui5_cl_ui5f_session_js IMPLEMENTATION.

  METHOD get.

    result = `sap.ui.define(["sap/ui/Device", "z2ui5/core/Lib"], (Device, Lib) => {` && |\n| &&
             `  "use strict";` && |\n| &&
             `` && |\n| &&
             `  let deviceStatic;` && |\n| &&
             `  function getDeviceStatic() {` && |\n| &&
             `    if (!deviceStatic) {` && |\n| &&
             `      deviceStatic = {` && |\n| &&
             `        SYSTEM: Lib.deriveSystemType(Device.system),` && |\n| &&
             `        BROWSER: {` && |\n| &&
             `          NAME: Device.browser.name || "",` && |\n| &&
             `          VERSION: String(Device.browser.version || ""),` && |\n| &&
             `        },` && |\n| &&
             `        OS: {` && |\n| &&
             `          NAME: Device.os.name || "",` && |\n| &&
             `          VERSION: String(Device.os.version || ""),` && |\n| &&
             `        },` && |\n| &&
             `        SUPPORT: {` && |\n| &&
             `          TOUCH: Device.support.touch || false,` && |\n| &&
             `          POINTER: Device.support.pointer || false,` && |\n| &&
             `          RETINA: Device.support.retina || false,` && |\n| &&
             `        },` && |\n| &&
             `      };` && |\n| &&
             `    }` && |\n| &&
             `    return deviceStatic;` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  function getDeviceLive() {` && |\n| &&
             `    return {` && |\n| &&
             `      ORIENTATION: Device.orientation.portrait ? "portrait" : "landscape",` && |\n| &&
             `      RESIZE: {` && |\n| &&
             `        WIDTH: Device.resize.width || window.innerWidth,` && |\n| &&
             `        HEIGHT: Device.resize.height || window.innerHeight,` && |\n| &&
             `      },` && |\n| &&
             `    };` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  let sessionConfigSent = false;` && |\n| &&
             `` && |\n| &&
             `  let liveSent = "";` && |\n| &&
             `` && |\n| &&
             `  let pending = null;` && |\n| &&
             `` && |\n| &&
             `  function config(oConfig, draftId) {` && |\n| &&
             `    const live = getDeviceLive();` && |\n| &&
             `    const liveKey = JSON.stringify(live);` && |\n| &&
             `    if (sessionConfigSent && draftId) {` && |\n| &&
             `      if (liveKey === liveSent) {` && |\n| &&
             `        pending = null;` && |\n| &&
             `        return {};` && |\n| &&
             `      }` && |\n| &&
             `      pending = { live: liveKey };` && |\n| &&
             `      return { S_DEVICE: live };` && |\n| &&
             `    }` && |\n| &&
             `    pending = { config: Boolean(oConfig?.S_UI5), live: liveKey };` && |\n| &&
             `    return {` && |\n| &&
             `      S_UI5: oConfig?.S_UI5,` && |\n| &&
             `      ComponentData: oConfig?.ComponentData,` && |\n| &&
             `      S_DEVICE: { ...getDeviceStatic(), ...live },` && |\n| &&
             `    };` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  function takePending() {` && |\n| &&
             `    const p = pending;` && |\n| &&
             `    pending = null;` && |\n| &&
             `    return p;` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  function confirmSent(p) {` && |\n| &&
             `    if (!p) return;` && |\n| &&
             `    if (p.config) sessionConfigSent = true;` && |\n| &&
             `    if (p.live !== undefined) liveSent = p.live;` && |\n| &&
             `    if (p.location) locationSent = true;` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  let locationSent = false;` && |\n| &&
             `` && |\n| &&
             `  function location(draftId, search) {` && |\n| &&
             `    if (draftId && locationSent) return null;` && |\n| &&
             `` && |\n| &&
             `    pending = { ...pending, location: true };` && |\n| &&
             `    return {` && |\n| &&
             `      ORIGIN: window.location.origin,` && |\n| &&
             `      PATHNAME: window.location.pathname,` && |\n| &&
             `      SEARCH: search || window.location.search,` && |\n| &&
             `    };` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  return { config, takePending, confirmSent, location };` && |\n| &&
             `});` && |\n| &&
             `` && |\n| &&
              ``.

  ENDMETHOD.

ENDCLASS.
