* =====================================================================
* GENERATED FILE - DO NOT EDIT (AGENTS.md rule 2)
* Source: app/webapp/devtools/Inspect.js
* Embedded frontend resource, generated by tools/app2abap/trans2abap.js.
* Change the source file above and run 'npm run app2abap' to regenerate;
* the check_app2abap CI gate fails any manual edit here.
* =====================================================================
CLASS z2ui5_cl_ui5f_inspect_js DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CLASS-METHODS get
      RETURNING
        VALUE(result) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS z2ui5_cl_ui5f_inspect_js IMPLEMENTATION.

  METHOD get.

    result = `// Read-only inspectors of the developer tools.` && |\n| &&
             `//` && |\n| &&
             `// Like devtools/Recorder.js this module is OUTSIDE the framework: it` && |\n| &&
             `// only reads state other modules own (AppState, ViewSlots, the recorded` && |\n| &&
             `// history) and renders it as text for a developer-tools tab. Nothing here` && |\n| &&
             `// is wired into a framework code path, and nothing in the framework knows` && |\n| &&
             `// this file exists.` && |\n| &&
             `//` && |\n| &&
             `// Everything renders to plain text rather than a control tree, because the` && |\n| &&
             `// same string has to serve two consumers: the CodeEditor in the dialog and` && |\n| &&
             `// the Export blob.` && |\n| &&
             `sap.ui.define(` && |\n| &&
             `  [` && |\n| &&
             `    "sap/ui/Device",` && |\n| &&
             `    "z2ui5/core/AppState",` && |\n| &&
             `    "z2ui5/core/Lib",` && |\n| &&
             `    "z2ui5/core/ScrollFocus",` && |\n| &&
             `    "z2ui5/core/ViewSlots",` && |\n| &&
             `    "z2ui5/devtools/Console",` && |\n| &&
             `    "z2ui5/devtools/Recorder",` && |\n| &&
             `  ],` && |\n| &&
             `  (Device, AppState, Lib, ScrollFocus, ViewSlots, Console, Recorder) => {` && |\n| &&
             `    "use strict";` && |\n| &&
             `` && |\n| &&
             `    // Longest argument rendered inline in the action list; a view XML` && |\n| &&
             `    // argument is thousands of characters and would bury the structure.` && |\n| &&
             `    const MAX_ARG_CHARS = 160;` && |\n| &&
             `` && |\n| &&
             `    // Cap for the scraped event list - a generated view can bind hundreds.` && |\n| &&
             `    const MAX_SCRAPED_EVENTS = 200;` && |\n| &&
             `` && |\n| &&
             `    const LABEL_WIDTH = 24;` && |\n| &&
             `` && |\n| &&
             `    function line(label, value) {` && |\n| &&
             `      const text =` && |\n| &&
             `        value === undefined || value === null || value === "" ? "-" : value;` && |\n| &&
             `      return ``  ${label.padEnd(LABEL_WIDTH)}${text}``;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function section(title) {` && |\n| &&
             `      return ``\n${title}\n${"-".repeat(title.length)}``;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function yesNo(value) {` && |\n| &&
             `      return value ? "yes" : "no";` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function truncate(text, max) {` && |\n| &&
             `      const str = String(text);` && |\n| &&
             `      if (str.length <= max) return str;` && |\n| &&
             `      return ``${str.slice(0, max)}... (${str.length} chars)``;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `    // Environment` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `` && |\n| &&
             `    // The running theme, version-independently. sap/ui/core/Theming arrived` && |\n| &&
             `    // in 1.118 and is the only API left in UI5 2.x; older releases expose` && |\n| &&
             `    // it through the Configuration singleton.` && |\n| &&
             `    function getTheme() {` && |\n| &&
             `      const Theming = sap.ui.require("sap/ui/core/Theming");` && |\n| &&
             `      if (Theming?.getTheme) return Theming.getTheme();` && |\n| &&
             `      /* ui5lint-disable no-globals, no-deprecated-api --` && |\n| &&
             `       deliberate fallback for UI5 releases without sap/ui/core/Theming` && |\n| &&
             `       (added in 1.118); the modern API is used in the branch above. */` && |\n| &&
             `      if (sap.ui.getCore) {` && |\n| &&
             `        const config = sap.ui.getCore().getConfiguration?.();` && |\n| &&
             `        if (config?.getTheme) return config.getTheme();` && |\n| &&
             `      }` && |\n| &&
             `      /* ui5lint-enable no-globals, no-deprecated-api */` && |\n| &&
             `      return "";` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // The bootstrap <script> of the page. Both pages abap2UI5 can run on` && |\n| &&
             `    // give it the id "sap-ui-bootstrap": the standalone app/webapp/index.html` && |\n| &&
             `    // and the HTML the backend generates (z2ui5_cl_ui5_http_handler), whose` && |\n| &&
             `    // ``src`` comes from the exit configuration. Which SDK URL a system is` && |\n| &&
             `    // actually configured with is the first question when a view fails to` && |\n| &&
             `    // load a control, and it is nowhere else to be seen.` && |\n| &&
             `    function bootstrapElement() {` && |\n| &&
             `      try {` && |\n| &&
             `        return document.getElementById("sap-ui-bootstrap");` && |\n| &&
             `      } catch {` && |\n| &&
             `        return null;` && |\n| &&
             `      }` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function bootstrapAttr(el, name) {` && |\n| &&
             `      // The bootstrap attributes are written camelCase in the page` && |\n| &&
             `      // (data-sap-ui-compatVersion); getAttribute is case-insensitive for` && |\n| &&
             `      // HTML elements, so the lower-case form finds them either way.` && |\n| &&
             `      return el?.getAttribute?.(``data-sap-ui-${name}``) || "";` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // Where the UI5 loader resolves a module namespace to. Answers "is this` && |\n| &&
             `    // app loading its own resources from the BSP, the standalone service or` && |\n| &&
             `    // a sibling add-on BSP", which a wrong resourceroot silently breaks.` && |\n| &&
             `    function resourceUrl(namespace) {` && |\n| &&
             `      try {` && |\n| &&
             `        return sap.ui.require?.toUrl ? sap.ui.require.toUrl(namespace) : "";` && |\n| &&
             `      } catch {` && |\n| &&
             `        return "";` && |\n| &&
             `      }` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // Language and text direction, version-independently.` && |\n| &&
             `    // sap/base/i18n/Localization arrived in 1.118 and is the only API left` && |\n| &&
             `    // in UI5 2.x; older releases expose both through the Configuration.` && |\n| &&
             `    function getLocale() {` && |\n| &&
             `      const Localization = sap.ui.require("sap/base/i18n/Localization");` && |\n| &&
             `      if (Localization?.getLanguage) {` && |\n| &&
             `        return {` && |\n| &&
             `          language: Localization.getLanguage(),` && |\n| &&
             `          rtl: Boolean(Localization.getRTL?.()),` && |\n| &&
             `        };` && |\n| &&
             `      }` && |\n| &&
             `      /* ui5lint-disable no-globals, no-deprecated-api --` && |\n| &&
             `       deliberate fallback for UI5 releases without` && |\n| &&
             `       sap/base/i18n/Localization (added in 1.118); the modern API is used` && |\n| &&
             `       in the branch above. */` && |\n| &&
             `      if (sap.ui.getCore) {` && |\n| &&
             `        const config = sap.ui.getCore().getConfiguration?.();` && |\n| &&
             `        if (config?.getLanguage) {` && |\n| &&
             `          return {` && |\n| &&
             `            language: config.getLanguage(),` && |\n| &&
             `            rtl: Boolean(config.getRTL?.()),` && |\n| &&
             `          };` && |\n| &&
             `        }` && |\n| &&
             `      }` && |\n| &&
             `      /* ui5lint-enable no-globals, no-deprecated-api */` && |\n| &&
             `      return { language: "", rtl: false };` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // Compact vs cozy decides control heights and is set on the body by the` && |\n| &&
             `    // page (or by an app) - a layout that looks wrong in one density and` && |\n| &&
             `    // right in the other is a classic, and invisible without this.` && |\n| &&
             `    function getContentDensity() {` && |\n| &&
             `      try {` && |\n| &&
             `        const classes = document.body?.classList;` && |\n| &&
             `        if (classes?.contains("sapUiSizeCompact")) return "Compact";` && |\n| &&
             `        if (classes?.contains("sapUiSizeCozy")) return "Cozy";` && |\n| &&
             `      } catch {` && |\n| &&
             `        return "";` && |\n| &&
             `      }` && |\n| &&
             `      return "(neither class set)";` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // SAPUI5 and OpenUI5 ship different control libraries, and a view that` && |\n| &&
             `    // works on one can fail to load a module on the other - so which one is` && |\n| &&
             `    // running is a first-order fact when a view refuses to build. The` && |\n| &&
             `    // distribution is visible in the version info's group/artefact id.` && |\n| &&
             `    function getDistribution(sUi5) {` && |\n| &&
             `      const gav = sUi5?.GAV || "";` && |\n| &&
             `      if (!gav) return "";` && |\n| &&
             `      return gav.includes("com.sap.ui5") ? "SAPUI5" : "OpenUI5";` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function modelAttributeCount(slotKey) {` && |\n| &&
             `      const data = ViewSlots.getView(slotKey)?.getModel?.()?.getData?.();` && |\n| &&
             `      if (!data) return 0;` && |\n| &&
             `      return Object.keys(data).length;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function formatSlots() {` && |\n| &&
             `      const lines = [];` && |\n| &&
             `      for (const slot of ViewSlots.slots) {` && |\n| &&
             `        const view = ViewSlots.getView(slot.key);` && |\n| &&
             `        const xml = ViewSlots.getViewXml(slot.key);` && |\n| &&
             `        if (!view && !xml) {` && |\n| &&
             `          lines.push(line(slot.key, "empty"));` && |\n| &&
             `          continue;` && |\n| &&
             `        }` && |\n| &&
             `        const parts = [];` && |\n| &&
             `        parts.push(view ? "filled" : "xml only");` && |\n| &&
             `        if (xml) parts.push(``${xml.length} chars XML``);` && |\n| &&
             `        if (slot.ownsModel) {` && |\n| &&
             `          parts.push(``${modelAttributeCount(slot.key)} model attributes``);` && |\n| &&
             `        } else {` && |\n| &&
             `          parts.push("inherits MAIN model");` && |\n| &&
             `        }` && |\n| &&
             `        lines.push(line(slot.key, parts.join(", ")));` && |\n| &&
             `      }` && |\n| &&
             `      return lines;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function formatEnvironment() {` && |\n| &&
             `      const state = AppState.state;` && |\n| &&
             `      const oConfig = AppState.getGlobal("oConfig") || {};` && |\n| &&
             `      const sUi5 = oConfig.S_UI5;` && |\n| &&
             `      const responseFront = state.responseData?.S_FRONT;` && |\n| &&
             `      const out = ["abap2UI5 Developer Tools - Environment"];` && |\n| &&
             `` && |\n| &&
             `      out.push(section("App"));` && |\n| &&
             `      out.push(line("App class", responseFront?.APP));` && |\n| &&
             `      out.push(line("Rendered app", state.renderedApp));` && |\n| &&
             `      out.push(line("Draft id (received)", responseFront?.ID));` && |\n| &&
             `      out.push(line("Draft id (sent)", state.oBody?.S_FRONT?.ID));` && |\n| &&
             `      out.push(line("Last event", state.oBody?.S_FRONT?.EVENT));` && |\n| &&
             `      out.push(line("Roundtrip in flight", yesNo(state.isBusy)));` && |\n| &&
             `` && |\n| &&
             `      out.push(section("Session"));` && |\n| &&
             `      out.push(line("sap-contextid", state.contextId));` && |\n| &&
             `      out.push(line("Backend endpoint", AppState.getGlobal("url")));` && |\n| &&
             `      out.push(` && |\n| &&
             `        line("Served by backend", yesNo(AppState.getGlobal("checkLocal"))),` && |\n| &&
             `      );` && |\n| &&
             `      out.push(line("Launchpad", yesNo(state.oLaunchpad)));` && |\n| &&
             `      out.push(line("Origin", window.location.origin));` && |\n| &&
             `      out.push(line("Pathname", window.location.pathname));` && |\n| &&
             `      out.push(line("Search", window.location.search));` && |\n| &&
             `      out.push(line("Hash", window.location.hash));` && |\n| &&
             `` && |\n| &&
             `      out.push(section("Routing"));` && |\n| &&
             `      out.push(line("Hash routing", yesNo(state.navRouting)));` && |\n| &&
             `      out.push(line("Mode", state.navMode));` && |\n| &&
             `      out.push(line("Current app", state.currentApp));` && |\n| &&
             `      out.push(line("Current draft id", state.currentDraftId));` && |\n| &&
             `` && |\n| &&
             `      out.push(section("UI5"));` && |\n| &&
             `      /* ui5lint-disable no-globals --` && |\n| &&
             `       sap.ui.version is the only way to read the running UI5 version; there` && |\n| &&
             `       is no injected/module equivalent (core/Lib.js reads it the same way). */` && |\n| &&
             `      out.push(line("Version", sap.ui.version));` && |\n| &&
             `      /* ui5lint-enable no-globals */` && |\n| &&
             `      out.push(line("Distribution", getDistribution(sUi5)));` && |\n| &&
             `      out.push(line("Build timestamp", sUi5?.BUILDTIMESTAMP));` && |\n| &&
             `      out.push(line("Theme", getTheme()));` && |\n| &&
             `      const locale = getLocale();` && |\n| &&
             `      out.push(line("Language", locale.language));` && |\n| &&
             `      out.push(line("Text direction", locale.rtl ? "RTL" : "LTR"));` && |\n| &&
             `      out.push(line("Content density", getContentDensity()));` && |\n| &&
             `` && |\n| &&
             `      out.push(...formatBootstrap());` && |\n| &&
             `` && |\n| &&
             `      out.push(section("Device"));` && |\n| &&
             `      out.push(line("System", Lib.deriveSystemType(Device.system)));` && |\n| &&
             `      out.push(` && |\n| &&
             `        line(` && |\n| &&
             `          "Browser",` && |\n| &&
             `          ``${Device.browser.name || "?"} ${Device.browser.version || ""}``.trim(),` && |\n| &&
             `        ),` && |\n| &&
             `      );` && |\n| &&
             `      out.push(` && |\n| &&
             `        line(` && |\n| &&
             `          "OS",` && |\n| &&
             `          ``${Device.os.name || "?"} ${Device.os.version || ""}``.trim(),` && |\n| &&
             `        ),` && |\n| &&
             `      );` && |\n| &&
             `      out.push(` && |\n| &&
             `        line(` && |\n| &&
             `          "Orientation",` && |\n| &&
             `          Device.orientation.portrait ? "portrait" : "landscape",` && |\n| &&
             `        ),` && |\n| &&
             `      );` && |\n| &&
             `      out.push(` && |\n| &&
             `        line(` && |\n| &&
             `          "Window",` && |\n| &&
             `          ``${Device.resize.width || window.innerWidth} x `` +` && |\n| &&
             `            ``${Device.resize.height || window.innerHeight}``,` && |\n| &&
             `        ),` && |\n| &&
             `      );` && |\n| &&
             `      out.push(line("Touch", yesNo(Device.support.touch)));` && |\n| &&
             `      out.push(line("Pointer", yesNo(Device.support.pointer)));` && |\n| &&
             `      out.push(line("Retina", yesNo(Device.support.retina)));` && |\n| &&
             `` && |\n| &&
             `      out.push(...formatFrontendInfo());` && |\n| &&
             `` && |\n| &&
             `      out.push(section("View slots"));` && |\n| &&
             `      out.push(...formatSlots());` && |\n| &&
             `` && |\n| &&
             `      return out.join("\n");` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // How this page loaded UI5 and where it resolves resources from. Every` && |\n| &&
             `    // value is read from the LIVE page, not from what the backend says it` && |\n| &&
             `    // configured - which is the point: a proxy, a launchpad or a stale` && |\n| &&
             `    // cached page can all make these differ from the configuration.` && |\n| &&
             `    function formatBootstrap() {` && |\n| &&
             `      const out = [section("UI5 bootstrap")];` && |\n| &&
             `      const el = bootstrapElement();` && |\n| &&
             `      if (!el) {` && |\n| &&
             `        out.push('  (no <script id="sap-ui-bootstrap"> on this page -');` && |\n| &&
             `        out.push("  UI5 was started some other way, e.g. by a launchpad)");` && |\n| &&
             `      } else {` && |\n| &&
             `        // .src resolves relative to the page, so this is the absolute URL` && |\n| &&
             `        // the browser actually fetched the SDK from.` && |\n| &&
             `        out.push(line("SDK source", el.src || bootstrapAttr(el, "src")));` && |\n| &&
             `        for (const [label, attr] of [` && |\n| &&
             `          ["Bootstrap theme", "theme"],` && |\n| &&
             `          ["Resource roots", "resourceroots"],` && |\n| &&
             `          ["On init", "oninit"],` && |\n| &&
             `          ["Compat version", "compatversion"],` && |\n| &&
             `          ["Async", "async"],` && |\n| &&
             `          ["Frame options", "frameoptions"],` && |\n| &&
             `          ["Binding syntax", "bindingsyntax"],` && |\n| &&
             `          ["Libs", "libs"],` && |\n| &&
             `        ]) {` && |\n| &&
             `          const value = bootstrapAttr(el, attr);` && |\n| &&
             `          if (value) out.push(line(label, truncate(value, MAX_ARG_CHARS)));` && |\n| &&
             `        }` && |\n| &&
             `      }` && |\n| &&
             `` && |\n| &&
             `      out.push("");` && |\n| &&
             `      // The resolved roots matter more than the declared ones: this is` && |\n| &&
             `      // where a module request actually goes.` && |\n| &&
             `      out.push(line("Resource base", resourceUrl("")));` && |\n| &&
             `      out.push(line("z2ui5 root", resourceUrl("z2ui5")));` && |\n| &&
             `      // The two sibling BSPs for community controls and the customer's own` && |\n| &&
             `      // frontend extension. Reported only when the app set them up, since` && |\n| &&
             `      // a system that has neither installed should not look misconfigured.` && |\n| &&
             `      const cci = AppState.getGlobal("ccResourceRoot");` && |\n| &&
             `      const ccc = AppState.getGlobal("cccResourceRoot");` && |\n| &&
             `      if (cci) out.push(line("z2ui5_cci root", cci));` && |\n| &&
             `      if (ccc) out.push(line("z2ui5_ccc root", ccc));` && |\n| &&
             `      return out;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // The frontend block the framework puts on the wire - what an app reads` && |\n| &&
             `    // as client->get( )-s_ui5 / -s_device / -s_focus / -s_scroll and what` && |\n| &&
             `    // the start page's "System Information" popup shows of it. Rendered` && |\n| &&
             `    // here from the LIVE producers (core/ScrollFocus.js), so it is what the` && |\n| &&
             `    // NEXT roundtrip will send, not what the last one happened to carry.` && |\n| &&
             `    //` && |\n| &&
             `    // Focus and scroll are the interesting half: they travel on every` && |\n| &&
             `    // roundtrip, they decide where the caret and the scroll position end up` && |\n| &&
             `    // after a re-render, and nothing has ever shown them.` && |\n| &&
             `    function formatFrontendInfo() {` && |\n| &&
             `      const out = [section("Frontend info sent to the backend")];` && |\n| &&
             `      out.push("  (client->get( )-s_focus / -s_scroll, live for the next");` && |\n| &&
             `      out.push("  roundtrip - see -s_ui5 / -s_device above)");` && |\n| &&
             `      out.push("");` && |\n| &&
             `` && |\n| &&
             `      let focus;` && |\n| &&
             `      let scroll;` && |\n| &&
             `      try {` && |\n| &&
             `        focus = ScrollFocus.getFocusInfo();` && |\n| &&
             `        scroll = ScrollFocus.getScrollInfo();` && |\n| &&
             `      } catch (e) {` && |\n| &&
             `        Lib.logError("DevTools Inspect: reading focus/scroll failed", e);` && |\n| &&
             `        out.push("  (focus / scroll info unavailable)");` && |\n| &&
             `        return out;` && |\n| &&
             `      }` && |\n| &&
             `` && |\n| &&
             `      out.push(line("Focused control", focus?.ID));` && |\n| &&
             `      if (focus?.SELECTION_START !== undefined) {` && |\n| &&
             `        out.push(` && |\n| &&
             `          line("Caret", ``${focus.SELECTION_START} - ${focus.SELECTION_END}``),` && |\n| &&
             `        );` && |\n| &&
             `      }` && |\n| &&
             `      out.push("");` && |\n| &&
             `      let anyScroll = false;` && |\n| &&
             `      for (const slot of ViewSlots.slots) {` && |\n| &&
             `        // getScrollInfo keys by slot key and omits slots never scrolled` && |\n| &&
             `        const entry = scroll?.[slot.key];` && |\n| &&
             `        if (!entry) continue;` && |\n| &&
             `        anyScroll = true;` && |\n| &&
             `        out.push(` && |\n| &&
             `          line(` && |\n| &&
             `            ``Scroll ${slot.key}``,` && |\n| &&
             `            ``${entry.ID || "(unnamed)"}  x ${entry.X || 0} / y ${entry.Y || 0}``,` && |\n| &&
             `          ),` && |\n| &&
             `        );` && |\n| &&
             `      }` && |\n| &&
             `      if (!anyScroll) out.push(line("Scroll", "nothing scrolled yet"));` && |\n| &&
             `      return out;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `    // Registry - what the frontend currently has registered` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `` && |\n| &&
             `    // Backend event names bound in a view's XML. The framework binds an` && |\n| &&
             `    // event as ``.eB(['NAME'])`` / ``.eF(['NAME'])`` (see the backend's` && |\n| &&
             `    // get_event), so the names can be read back off the XML the slot was` && |\n| &&
             `    // filled with. Best effort by design: this is a diagnostic listing, and` && |\n| &&
             `    // a name it misses costs nothing but a shorter list.` && |\n| &&
             `    function scrapeEvents(xml) {` && |\n| &&
             `      if (!xml) return [];` && |\n| &&
             `      const found = new Set();` && |\n| &&
             `      // eB / eBP / eF, then an optional array bracket, then the quoted` && |\n| &&
             `      // event name - single, double or the XML-escaped apostrophe.` && |\n| &&
             `      const pattern =` && |\n| &&
             `        /\b(eB|eBP|eF)\s*\(\s*\[?\s*(?:&apos;|&quot;|['"])([A-Za-z0-9_.-]+)/g;` && |\n| &&
             `      let match = pattern.exec(xml);` && |\n| &&
             `      while (match !== null && found.size < MAX_SCRAPED_EVENTS) {` && |\n| &&
             `        found.add(``${match[1]}  ${match[2]}``);` && |\n| &&
             `        match = pattern.exec(xml);` && |\n| &&
             `      }` && |\n| &&
             `      return Array.from(found).sort();` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function formatShortcuts() {` && |\n| &&
             `      const shortcuts = AppState.state.shortcuts || {};` && |\n| &&
             `      const combos = Object.keys(shortcuts).sort();` && |\n| &&
             `      if (!combos.length) return ["  (none registered)"];` && |\n| &&
             `      const out = [];` && |\n| &&
             `      for (const combo of combos) {` && |\n| &&
             `        const scopes = shortcuts[combo];` && |\n| &&
             `        for (const scope of Object.keys(scopes)) {` && |\n|.
    result = result &&
             `          const entry = scopes[scope];` && |\n| &&
             `          out.push(` && |\n| &&
             `            ``  ${combo.padEnd(22)}${(scope || "(global)").padEnd(12)}`` +` && |\n| &&
             `              ``-> ${entry?.event || "?"}``,` && |\n| &&
             `          );` && |\n| &&
             `        }` && |\n| &&
             `      }` && |\n| &&
             `      return out;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function formatRegistry() {` && |\n| &&
             `      const state = AppState.state;` && |\n| &&
             `      const out = ["abap2UI5 Developer Tools - Registry"];` && |\n| &&
             `` && |\n| &&
             `      out.push(section("Keyboard shortcuts (combo / scope / backend event)"));` && |\n| &&
             `      out.push(...formatShortcuts());` && |\n| &&
             `` && |\n| &&
             `      out.push(section("Pending backend timers"));` && |\n| &&
             `      const timers = Object.keys(state.timers || {});` && |\n| &&
             `      out.push(timers.length ? ``  ${timers.join(", ")}`` : "  (none pending)");` && |\n| &&
             `` && |\n| &&
             `      out.push(section("Framework callbacks registered"));` && |\n| &&
             `      for (const name of [` && |\n| &&
             `        "onBeforeRoundtrip",` && |\n| &&
             `        "onAfterRoundtrip",` && |\n| &&
             `        "onAfterRendering",` && |\n| &&
             `        "onBeforeEventFrontend",` && |\n| &&
             `      ]) {` && |\n| &&
             `        out.push(line(name, String((state[name] || []).length)));` && |\n| &&
             `      }` && |\n| &&
             `` && |\n| &&
             `      out.push(section("Model size limits"));` && |\n| &&
             `      const limits = state.viewSizeLimits || {};` && |\n| &&
             `      const limitKeys = Object.keys(limits);` && |\n| &&
             `      if (!limitKeys.length) out.push("  (UI5 default everywhere)");` && |\n| &&
             `      for (const key of limitKeys) out.push(line(key, String(limits[key])));` && |\n| &&
             `` && |\n| &&
             `      out.push(section("Backend events bound in the current views"));` && |\n| &&
             `      let any = false;` && |\n| &&
             `      for (const slot of ViewSlots.slots) {` && |\n| &&
             `        const xml =` && |\n| &&
             `          ViewSlots.getView(slot.key)?.mProperties?.viewContent ||` && |\n| &&
             `          ViewSlots.getViewXml(slot.key);` && |\n| &&
             `        const events = scrapeEvents(xml);` && |\n| &&
             `        if (!events.length) continue;` && |\n| &&
             `        any = true;` && |\n| &&
             `        out.push(``  [${slot.key}]``);` && |\n| &&
             `        for (const event of events) out.push(``    ${event}``);` && |\n| &&
             `      }` && |\n| &&
             `      if (!any) out.push("  (no event bindings found in the current views)");` && |\n| &&
             `      out.push("");` && |\n| &&
             `      out.push(` && |\n| &&
             `        "  Scraped from the view XML the backend sent - eB rounds a trip," +` && |\n| &&
             `          " eF is handled in the browser.",` && |\n| &&
             `      );` && |\n| &&
             `` && |\n| &&
             `      return out.join("\n");` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `    // Actions - the response's two action lists, readable` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `` && |\n| &&
             `    function renderArg(arg) {` && |\n| &&
             `      if (arg === null) return "null";` && |\n| &&
             `      if (typeof arg === "object") {` && |\n| &&
             `        try {` && |\n| &&
             `          return truncate(JSON.stringify(arg), MAX_ARG_CHARS);` && |\n| &&
             `        } catch {` && |\n| &&
             `          return "[object]";` && |\n| &&
             `        }` && |\n| &&
             `      }` && |\n| &&
             `      return truncate(arg, MAX_ARG_CHARS);` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function renderActionList(list, title) {` && |\n| &&
             `      const out = [section(title)];` && |\n| &&
             `      if (!Array.isArray(list) || !list.length) {` && |\n| &&
             `        out.push("  (none)");` && |\n| &&
             `        return out;` && |\n| &&
             `      }` && |\n| &&
             `      list.forEach((item, index) => {` && |\n| &&
             `        const number = String(index + 1).padStart(3);` && |\n| &&
             `        if (!Array.isArray(item)) {` && |\n| &&
             `          // legacy app-authored raw JS snippet, passed through untouched` && |\n| &&
             `          out.push(``${number}  [legacy JS] ${truncate(item, MAX_ARG_CHARS)}``);` && |\n| &&
             `          return;` && |\n| &&
             `        }` && |\n| &&
             `        const [name, ...args] = item;` && |\n| &&
             `        out.push(``${number}  ${name}``);` && |\n| &&
             `        for (const arg of args) out.push(``       ${renderArg(arg)}``);` && |\n| &&
             `      });` && |\n| &&
             `      return out;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function formatActions() {` && |\n| &&
             `      const sAction = AppState.state.responseData?.S_FRONT?.S_ACTION;` && |\n| &&
             `      const out = ["abap2UI5 Developer Tools - Actions of the last response"];` && |\n| &&
             `      out.push("");` && |\n| &&
             `      out.push(` && |\n| &&
             `        "  T_SYSTEM runs first, in order, before the view is rendered;" +` && |\n| &&
             `          " T_CUSTOM runs last, once the DOM exists.",` && |\n| &&
             `      );` && |\n| &&
             `      out.push(` && |\n| &&
             `        ...renderActionList(sAction?.T_SYSTEM, "T_SYSTEM (view lifecycle)"),` && |\n| &&
             `      );` && |\n| &&
             `      out.push(...renderActionList(sAction?.T_CUSTOM, "T_CUSTOM (app)"));` && |\n| &&
             `      return out.join("\n");` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `    // Log - ONE timeline of everything the app logged` && |\n| &&
             `    //` && |\n| &&
             `    // These used to be three tabs: the framework's own error log, the` && |\n| &&
             `    // console capture, and the backend messages. They are three views of` && |\n| &&
             `    // the same timeline, and splitting them forced the developer to` && |\n| &&
             `    // correlate three tabs by timestamp by hand - which is exactly the` && |\n| &&
             `    // work a log is supposed to save. Merged and sorted by time, with the` && |\n| &&
             `    // origin in a column, the sequence reads itself: a UI5 binding warning,` && |\n| &&
             `    // then the toast the user saw, then the uncaught error that followed.` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `` && |\n| &&
             `    const LEVEL_LABEL = {` && |\n| &&
             `      error: "ERROR",` && |\n| &&
             `      warn: "WARN ",` && |\n| &&
             `      info: "INFO ",` && |\n| &&
             `      log: "LOG  ",` && |\n| &&
             `      debug: "DEBUG",` && |\n| &&
             `    };` && |\n| &&
             `` && |\n| &&
             `    // Column width of the origin marker. The longest is "rejection" at` && |\n| &&
             `    // nine characters, so nine would leave no separating space.` && |\n| &&
             `    const SOURCE_WIDTH = 10;` && |\n| &&
             `` && |\n| &&
             `    // Indent of a wrapped line (a stack trace) so it lines up under the` && |\n| &&
             `    // message rather than under the timestamp.` && |\n| &&
             `    const CONTINUATION_INDENT = " ".repeat(23 + SOURCE_WIDTH);` && |\n| &&
             `` && |\n| &&
             `    // The framework's own error log (Lib.logError) stores the caught error` && |\n| &&
             `    // alongside the message, and that is where the STACK TRACE is - the one` && |\n| &&
             `    // thing that says which line actually threw. Render it under its` && |\n| &&
             `    // message rather than dropping it.` && |\n| &&
             `    function frameworkEntryText(entry) {` && |\n| &&
             `      if (entry.error === undefined) return entry.message;` && |\n| &&
             `      let detail;` && |\n| &&
             `      if (entry.error && typeof entry.error === "object") {` && |\n| &&
             `        detail = entry.error.stack || entry.error.message;` && |\n| &&
             `      }` && |\n| &&
             `      if (!detail) {` && |\n| &&
             `        try {` && |\n| &&
             `          detail = String(entry.error);` && |\n| &&
             `        } catch {` && |\n| &&
             `          detail = "(error could not be rendered)";` && |\n| &&
             `        }` && |\n| &&
             `      }` && |\n| &&
             `      return ``${entry.message}\n${detail}``;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // A message box carries its severity in the method name` && |\n| &&
             `    // (MessageBox.error / .warning / .success); a toast has none.` && |\n| &&
             `    function messageLevel(message) {` && |\n| &&
             `      const method = String(message.method || "").toLowerCase();` && |\n| &&
             `      if (method === "error" || method === "alert") return "error";` && |\n| &&
             `      if (method === "warning") return "warn";` && |\n| &&
             `      return "info";` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function messageSource(message) {` && |\n| &&
             `      return message.target === "MESSAGE_BOX"` && |\n| &&
             `        ? ``box.${message.method || "show"}``` && |\n| &&
             `        : "toast";` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // Everything, in one array, oldest first. Sorted by the ISO timestamp` && |\n| &&
             `    // every source already carries - lexicographic order is chronological` && |\n| &&
             `    // for ISO strings, so no date parsing is needed.` && |\n| &&
             `    function collectLog() {` && |\n| &&
             `      const out = [];` && |\n| &&
             `      for (const entry of AppState.state.errors || []) {` && |\n| &&
             `        out.push({` && |\n| &&
             `          ts: entry.ts,` && |\n| &&
             `          level: "error",` && |\n| &&
             `          source: "framework",` && |\n| &&
             `          text: frameworkEntryText(entry),` && |\n| &&
             `        });` && |\n| &&
             `      }` && |\n| &&
             `      for (const entry of Console.getEntries()) {` && |\n| &&
             `        out.push({` && |\n| &&
             `          ts: entry.ts,` && |\n| &&
             `          level: entry.level,` && |\n| &&
             `          source: entry.source,` && |\n| &&
             `          text: entry.text,` && |\n| &&
             `          previousLoad: entry.previousLoad,` && |\n| &&
             `        });` && |\n| &&
             `      }` && |\n| &&
             `      for (const record of Recorder.getRecords()) {` && |\n| &&
             `        for (const message of record.messages || []) {` && |\n| &&
             `          out.push({` && |\n| &&
             `            ts: record.ts,` && |\n| &&
             `            level: messageLevel(message),` && |\n| &&
             `            source: messageSource(message),` && |\n| &&
             `            text: message.text,` && |\n| &&
             `            previousLoad: record.previousLoad,` && |\n| &&
             `          });` && |\n| &&
             `        }` && |\n| &&
             `      }` && |\n| &&
             `      out.sort((a, b) => {` && |\n| &&
             `        if (a.ts === b.ts) return 0;` && |\n| &&
             `        return a.ts < b.ts ? -1 : 1;` && |\n| &&
             `      });` && |\n| &&
             `      return out;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function countLevels(entries) {` && |\n| &&
             `      const out = { error: 0, warn: 0, info: 0, log: 0, debug: 0 };` && |\n| &&
             `      for (const entry of entries) {` && |\n| &&
             `        if (out[entry.level] !== undefined) out[entry.level] += 1;` && |\n| &&
             `      }` && |\n| &&
             `      return out;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function formatLog() {` && |\n| &&
             `      const entries = collectLog();` && |\n| &&
             `      const lines = ["abap2UI5 Developer Tools - Log"];` && |\n| &&
             `      lines.push("");` && |\n| &&
             `      lines.push(` && |\n| &&
             `        "  One timeline of everything the app logged, so the browser's own",` && |\n| &&
             `      );` && |\n| &&
             `      lines.push(` && |\n| &&
             `        "  devtools do not have to be open. The origin is in the third",` && |\n| &&
             `      );` && |\n| &&
             `      lines.push("  column:");` && |\n| &&
             `      lines.push("");` && |\n| &&
             `      lines.push(` && |\n| &&
             `        "    framework   the framework's own error log (Lib.logError)",` && |\n| &&
             `      );` && |\n| &&
             `      lines.push("    ui5         UI5's log - binding and control problems");` && |\n| &&
             `      lines.push("    console     a console.* call from the app or a library");` && |\n| &&
             `      lines.push("    uncaught    an uncaught error");` && |\n| &&
             `      lines.push("    rejection   an unhandled promise rejection");` && |\n| &&
             `      lines.push("    toast/box   a backend message the user was shown");` && |\n| &&
             `      lines.push("");` && |\n| &&
             `      const counts = countLevels(entries);` && |\n| &&
             `      const dropped = Console.getDropped();` && |\n| &&
             `      lines.push(` && |\n| &&
             `        ``  ${entries.length} entr(ies) - ${counts.error} error,`` +` && |\n| &&
             `          `` ${counts.warn} warn, ${counts.info} info, ${counts.log} log,`` +` && |\n| &&
             `          `` ${counts.debug} debug`` +` && |\n| &&
             `          (dropped ? `` (${dropped} older console entries dropped)`` : ""),` && |\n| &&
             `      );` && |\n| &&
             `      lines.push("");` && |\n| &&
             `      if (!entries.length) {` && |\n| &&
             `        lines.push("  (nothing logged yet)");` && |\n| &&
             `        return lines.join("\n");` && |\n| &&
             `      }` && |\n| &&
             `      for (const entry of entries) {` && |\n| &&
             `        const label = LEVEL_LABEL[entry.level] || entry.level.toUpperCase();` && |\n| &&
             `        const head =` && |\n| &&
             `          ``  ${entry.ts.slice(11, 23)}${entry.previousLoad ? "*" : " "} `` +` && |\n| &&
             `          ``${label}  ${entry.source.padEnd(SOURCE_WIDTH)}``;` && |\n| &&
             `        const [first, ...rest] = String(entry.text).split("\n");` && |\n| &&
             `        lines.push(``${head}${first}``);` && |\n| &&
             `        // a stack trace keeps its own lines, indented under its message` && |\n| &&
             `        for (const line of rest) {` && |\n| &&
             `          lines.push(``${CONTINUATION_INDENT}${line.trim()}``);` && |\n| &&
             `        }` && |\n| &&
             `      }` && |\n| &&
             `      if (entries.some((entry) => entry.previousLoad)) {` && |\n| &&
             `        lines.push("");` && |\n| &&
             `        lines.push(` && |\n| &&
             `          "  A '*' after the time marks an entry of the PREVIOUS page load," +` && |\n| &&
             `            " carried across the reload.",` && |\n| &&
             `        );` && |\n| &&
             `      }` && |\n| &&
             `      return lines.join("\n");` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `    // Bindings - model paths, and which of them the user edited` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `` && |\n| &&
             `    // Describe a model value the way a developer scanning for "why is this` && |\n| &&
             `    // field empty" needs: type, size, and a short preview.` && |\n| &&
             `    function describeValue(value) {` && |\n| &&
             `      if (value === null) return "null";` && |\n| &&
             `      if (value === undefined) return "(absent)";` && |\n| &&
             `      if (Array.isArray(value)) {` && |\n| &&
             `        return ``table, ${value.length} row(s)``;` && |\n| &&
             `      }` && |\n| &&
             `      if (typeof value === "object") {` && |\n| &&
             `        return ``structure, ${Object.keys(value).length} field(s)``;` && |\n| &&
             `      }` && |\n| &&
             `      if (value === "") return ``${typeof value} (empty)``;` && |\n| &&
             `      return ``${typeof value}  ${truncate(value, 60)}``;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function formatSlotBindings(slotKey) {` && |\n| &&
             `      const view = ViewSlots.getView(slotKey);` && |\n| &&
             `      if (!view) return [];` && |\n| &&
             `      const model = view.getModel?.();` && |\n| &&
             `      const data = model?.getData?.();` && |\n| &&
             `      if (!data) return [];` && |\n| &&
             `      const out = [section(``Slot ${slotKey}``)];` && |\n| &&
             `      // The edited-path set the next roundtrip will ship as its delta.` && |\n| &&
             `      // Slots.trackChanges parks it on the model itself; nothing surfaces` && |\n| &&
             `      // it today, which is why "why was my edit not sent" is hard to answer.` && |\n| &&
             `      const changed = model._z2ui5ChangedPaths;` && |\n| &&
             `      const dirty = changed ? new Set(changed) : new Set();` && |\n| &&
             `      const keys = Object.keys(data).sort();` && |\n| &&
             `      if (!keys.length) out.push("  (model is empty)");` && |\n| &&
             `      for (const key of keys) {` && |\n| &&
             `        const path = ``/${key}``;` && |\n| &&
             `        // a table edit is tracked on the deep path, so mark the attribute` && |\n| &&
             `        // when any tracked path starts with it` && |\n| &&
             `        const isDirty = Array.from(dirty).some(` && |\n| &&
             `          (p) => p === path || p.startsWith(``${path}/``),` && |\n| &&
             `        );` && |\n| &&
             `        out.push(` && |\n| &&
             `          ``  ${isDirty ? "*" : " "} ${path.padEnd(30)}${describeValue(data[key])}``,` && |\n| &&
             `        );` && |\n| &&
             `      }` && |\n| &&
             `      if (dirty.size) {` && |\n| &&
             `        out.push("");` && |\n| &&
             `        out.push("  Edited paths queued for the next roundtrip:");` && |\n| &&
             `        for (const path of Array.from(dirty).sort()) out.push(``    ${path}``);` && |\n| &&
             `      }` && |\n| &&
             `      out.push(...formatPendingDelta(dirty, data));` && |\n| &&
             `      out.push(...formatBindingCheck(slotKey, data));` && |\n| &&
             `      out.push(...formatSizeRanking(data));` && |\n| &&
             `      return out;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // Absolute model paths bound in a view's XML. Only the ABSOLUTE ones` && |\n| &&
             `    // ("{/NAME}", "{path: '/NAME'}", "${/NAME}" inside an expression) can be` && |\n| &&
             `    // checked against the model - a relative binding inside an aggregation` && |\n| &&
             `    // template ("{COL}") resolves against the row context and says nothing` && |\n| &&
             `    // on its own, so it is deliberately not collected.` && |\n| &&
             `    //` && |\n| &&
             `    // Returns the top-level ATTRIBUTE of each path ("/TAB/0/COL" -> "TAB"),` && |\n| &&
             `    // because that is what client->_bind( ) creates and what the model has` && |\n| &&
             `    // as a key.` && |\n| &&
             `    function scrapeBindingAttributes(xml) {` && |\n| &&
             `      if (!xml) return [];` && |\n| &&
             `      const found = new Set();` && |\n| &&
             `      // a "/" directly after {, ${, a quote or a comma-separated path:` && |\n| &&
             `      // covers {/A}, {path:'/A'}, {parts:['/A','/B']}, {= ${/A} > 1 }` && |\n| &&
             `      const pattern = /[{$'",:[\s]\/([A-Za-z_][A-Za-z0-9_]*)/g;` && |\n| &&
             `      let match = pattern.exec(xml);` && |\n| &&
             `      while (match !== null) {` && |\n| &&
             `        found.add(match[1]);` && |\n| &&
             `        match = pattern.exec(xml);` && |\n| &&
             `      }` && |\n| &&
             `      return Array.from(found).sort();` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // The check that answers "why is my field empty": every absolute path` && |\n| &&
             `    // the view binds, against the attributes the model actually carries. A` && |\n| &&
             `    // renamed ABAP attribute, a typo, or a forgotten client->_bind( ) all` && |\n| &&
             `    // land here, and nothing else in the tools makes them visible.` && |\n| &&
             `    function formatBindingCheck(slotKey, data) {` && |\n| &&
             `      const xml =` && |\n| &&
             `        ViewSlots.getView(slotKey)?.mProperties?.viewContent ||` && |\n| &&
             `        ViewSlots.getViewXml(slotKey);` && |\n| &&
             `      const bound = scrapeBindingAttributes(xml);` && |\n| &&
             `      if (!bound.length) return [];` && |\n| &&
             `      const missing = bound.filter((name) => !(name in data));` && |\n| &&
             `      const out = [];` && |\n| &&
             `      if (missing.length) {` && |\n| &&
             `        out.push("");` && |\n| &&
             `        out.push("  BOUND IN THE VIEW BUT NOT IN THE MODEL:");` && |\n| &&
             `        for (const name of missing) out.push(``    /${name}``);` && |\n| &&
             `        out.push(` && |\n| &&
             `          "    -> a typo, a renamed ABAP attribute, or a missing" +` && |\n| &&
             `            " client->_bind( ).",` && |\n| &&
             `        );` && |\n| &&
             `      }` && |\n| &&
             `      // The other direction is worth one line, not a list: an unbound` && |\n| &&
             `      // attribute is wasted payload, not a defect.` && |\n| &&
             `      const unused = Object.keys(data).filter((name) => !bound.includes(name));` && |\n| &&
             `      if (unused.length) {` && |\n| &&
             `        out.push("");` && |\n| &&
             `        out.push(` && |\n| &&
             `          ``  ${unused.length} model attribute(s) not bound in this view:`` +` && |\n| &&
             `            `` ${unused.slice(0, 12).join(", ")}`` +` && |\n| &&
             `            ``${unused.length > 12 ? ", ..." : ""}``,` && |\n| &&
             `        );` && |\n| &&
             `      }` && |\n| &&
             `      return out;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // Serialized size of one model attribute. This is the number that` && |\n| &&
             `    // explains a large response - and the ranking below turns "the response` && |\n| &&
             `    // is 800 KB" into "/T_ITEMS is 92 % of it".` && |\n| &&
             `    function attributeSize(value) {` && |\n| &&
             `      try {` && |\n| &&
             `        const json = JSON.stringify(value);` && |\n| &&
             `        return json === undefined ? 0 : json.length;` && |\n| &&
             `      } catch {` && |\n| &&
             `        return 0;` && |\n| &&
             `      }` && |\n|.
    result = result &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function formatBytes(bytes) {` && |\n| &&
             `      if (bytes < 1024) return ``${bytes} B``;` && |\n| &&
             `      if (bytes < 1024 * 1024) return ``${Math.round(bytes / 1024)} KB``;` && |\n| &&
             `      return ``${(bytes / (1024 * 1024)).toFixed(1)} MB``;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function formatSizeRanking(data) {` && |\n| &&
             `      const sizes = Object.keys(data)` && |\n| &&
             `        .map((name) => ({ name, size: attributeSize(data[name]) }))` && |\n| &&
             `        .sort((a, b) => b.size - a.size);` && |\n| &&
             `      const total = sizes.reduce((sum, entry) => sum + entry.size, 0);` && |\n| &&
             `      if (!total) return [];` && |\n| &&
             `      const out = ["", ``  Model size: ${formatBytes(total)} serialized``];` && |\n| &&
             `      // Only the heavy end is interesting; a long tail of small scalars` && |\n| &&
             `      // would bury it.` && |\n| &&
             `      for (const entry of sizes.slice(0, 8)) {` && |\n| &&
             `        if (!entry.size) continue;` && |\n| &&
             `        const share = Math.round((entry.size * 100) / total);` && |\n| &&
             `        const rows = Array.isArray(data[entry.name])` && |\n| &&
             `          ? ``, ${data[entry.name].length} row(s)``` && |\n| &&
             `          : "";` && |\n| &&
             `        out.push(` && |\n| &&
             `          ``    ${``/${entry.name}``.padEnd(30)}${formatBytes(entry.size).padStart(8)}`` +` && |\n| &&
             `            ``  ${String(share).padStart(3)}%${rows}``,` && |\n| &&
             `        );` && |\n| &&
             `      }` && |\n| &&
             `      return out;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // The delta the NEXT roundtrip will actually put on the wire, built` && |\n| &&
             `    // with the very function the framework uses for it` && |\n| &&
             `    // (Lib.buildDeltaFromPaths). Answers "why does my change not arrive in` && |\n| &&
             `    // the backend" BEFORE the roundtrip instead of after it.` && |\n| &&
             `    function formatPendingDelta(dirty, data) {` && |\n| &&
             `      if (!dirty.size) return [];` && |\n| &&
             `      const out = ["", "  Delta the next roundtrip will send:"];` && |\n| &&
             `      try {` && |\n| &&
             `        const delta = Lib.buildDeltaFromPaths(dirty, data);` && |\n| &&
             `        const json = JSON.stringify(delta, null, 2);` && |\n| &&
             `        for (const line of truncate(json, 1200).split("\n")) {` && |\n| &&
             `          out.push(``    ${line}``);` && |\n| &&
             `        }` && |\n| &&
             `      } catch (e) {` && |\n| &&
             `        Lib.logError("DevTools Inspect: building the delta preview failed", e);` && |\n| &&
             `        out.push("    (could not be built)");` && |\n| &&
             `      }` && |\n| &&
             `      return out;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function formatBindings() {` && |\n| &&
             `      const out = ["abap2UI5 Developer Tools - Model bindings"];` && |\n| &&
             `      out.push("");` && |\n| &&
             `      out.push(` && |\n| &&
             `        "  A '*' marks an attribute the user edited: those paths travel as" +` && |\n| &&
             `          " the delta of the next roundtrip.",` && |\n| &&
             `      );` && |\n| &&
             `      out.push(` && |\n| &&
             `        "  MAIN, NEST and NEST2 share one model by UI5 propagation, so they" +` && |\n| &&
             `          " are listed once, under MAIN.",` && |\n| &&
             `      );` && |\n| &&
             `      let any = false;` && |\n| &&
             `      for (const slot of ViewSlots.slots) {` && |\n| &&
             `        // only the slots that own a model - the nested ones would repeat MAIN` && |\n| &&
             `        if (!slot.ownsModel) continue;` && |\n| &&
             `        const lines = formatSlotBindings(slot.key);` && |\n| &&
             `        if (!lines.length) continue;` && |\n| &&
             `        any = true;` && |\n| &&
             `        out.push(...lines);` && |\n| &&
             `      }` && |\n| &&
             `      if (!any) out.push("\n  (no slot carries a model yet)");` && |\n| &&
             `      return out.join("\n");` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `    // ABAP source helpers` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `` && |\n| &&
             `    // 1-based line number where ``eventName`` first appears in the ABAP` && |\n| &&
             `    // source, or 0 when it does not. Used to deep-link the ADT jump at the` && |\n| &&
             `    // handler of the event the last roundtrip carried, instead of at the` && |\n| &&
             `    // top of the class. Pure string work so it is unit-testable.` && |\n| &&
             `    //` && |\n| &&
             `    // Matched case-insensitively and only where the name is not part of a` && |\n| &&
             `    // longer identifier, so ``SAVE`` does not hit ``SAVE_ALL``.` && |\n| &&
             `    function findEventLine(source, eventName) {` && |\n| &&
             `      if (!source || !eventName) return 0;` && |\n| &&
             `      const lines = source.split("\n");` && |\n| &&
             `      const needle = eventName.toLowerCase();` && |\n| &&
             `      for (let i = 0; i < lines.length; i++) {` && |\n| &&
             `        const haystack = lines[i].toLowerCase();` && |\n| &&
             `        let from = haystack.indexOf(needle);` && |\n| &&
             `        while (from !== -1) {` && |\n| &&
             `          const before = haystack[from - 1];` && |\n| &&
             `          const after = haystack[from + needle.length];` && |\n| &&
             `          const isWordChar = (ch) => ch !== undefined && /[a-z0-9_]/.test(ch);` && |\n| &&
             `          if (!isWordChar(before) && !isWordChar(after)) return i + 1;` && |\n| &&
             `          from = haystack.indexOf(needle, from + 1);` && |\n| &&
             `        }` && |\n| &&
             `      }` && |\n| &&
             `      return 0;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `    // Help - what each tab answers, and the entry points` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `` && |\n| &&
             `    // Discoverability is the real barrier here: a tab that nobody knows` && |\n| &&
             `    // exists helps nobody, and Ctrl+F12 is not guessable. Kept as text` && |\n| &&
             `    // next to the tabs it describes so it cannot drift into a wiki.` && |\n| &&
             `    const HELP = [` && |\n| &&
             `      "abap2UI5 Developer Tools",` && |\n| &&
             `      "",` && |\n| &&
             `      "Opening",` && |\n| &&
             `      "-------",` && |\n| &&
             `      "  Ctrl+F12                    open / close these tools",` && |\n| &&
             `      "  ?z2ui5-devtools=1           open them on page load (for problems",` && |\n| &&
             `      "                              that happen during startup)",` && |\n| &&
             `      "  ?z2ui5-devtools=HISTORY     open them directly on a tab, by its key",` && |\n| &&
             `      "",` && |\n| &&
             `      "  Without a tab named, they reopen on the tab you were last on.",` && |\n| &&
             `      "",` && |\n| &&
             `      "Tabs - what each one answers",` && |\n| &&
             `      "----------------------------",` && |\n| &&
             `      "  Error         the last fatal error, with Retry / Restart / Logout",` && |\n| &&
             `      "  Log           ONE timeline of everything logged: the framework's",` && |\n| &&
             `      "                own error log (with stack traces), UI5's log (binding",` && |\n| &&
             `      "                and control problems), uncaught errors, unhandled",` && |\n| &&
             `      "                rejections, every console.* call, and the backend",` && |\n| &&
             `      "                messages the user was shown - so the browser's own",` && |\n| &&
             `      "                devtools do not have to be open",` && |\n| &&
             `      "  History       every roundtrip: backend vs. render time, payload",` && |\n| &&
             `      "                sizes, draft ids - and the ones that never rendered",` && |\n| &&
             `      "  Model Diff    what the backend changed between two responses",` && |\n| &&
             `      "                (needs Record Payloads)",` && |\n| &&
             `      "  View Diff     what changed in the view XML between two rebuilds",` && |\n| &&
             `      "                (needs Record Payloads)",` && |\n| &&
             `      "  Search        one term across EVERY tab at once - answers 'where",` && |\n| &&
             `      "                does /CUSTOMER appear?' without opening each tab",` && |\n| &&
             `      "  Actions       the response's T_SYSTEM / T_CUSTOM lists, readable",` && |\n| &&
             `      "  Bindings      the model attributes, '*' on the paths that will",` && |\n| &&
             `      "                travel as the next delta, the delta itself, the paths",` && |\n| &&
             `      "                bound in the view that the model does NOT have (the",` && |\n| &&
             `      "                usual cause of an empty field), and the attributes",` && |\n| &&
             `      "                ranked by size (the usual cause of a huge response)",` && |\n| &&
             `      "  Picked        the last control picked with 'Pick Control'",` && |\n| &&
             `      "  Registry      shortcuts, timers, callbacks, bound backend events",` && |\n| &&
             `      "  Environment   versions, SAPUI5 vs OpenUI5, the SDK url the page",` && |\n| &&
             `      "                bootstrapped from and its resource roots, theme,",` && |\n| &&
             `      "                language, content density, session, device, the",` && |\n| &&
             `      "                focus/scroll block sent on every roundtrip, slots",` && |\n| &&
             `      "  Source Code   the running app's ABAP class (ADT opens it in a tab)",` && |\n| &&
             `      "  Request /     the raw JSON on the wire",` && |\n| &&
             `      "  Response",` && |\n| &&
             `      "  View / Popup / Popover / Nest   the view XML each slot holds",` && |\n| &&
             `      "",` && |\n| &&
             `      "In the tabs themselves",` && |\n| &&
             `      "----------------------",` && |\n| &&
             `      "  Search tab       the search field",` && |\n| &&
             `      "  Picked tab       'Pick Control' - click any control in the app and",` && |\n| &&
             `      "                   see which ABAP attribute feeds it, with its",` && |\n| &&
             `      "                   current value",` && |\n| &&
             `      "  History tab      'Record Payloads' - keep request/response bodies.",` && |\n| &&
             `      "                   OFF by default: it is the only part that costs",` && |\n| &&
             `      "                   real memory (2 MB budget, oldest dropped first).",` && |\n| &&
             `      "                   The Model Diff and View Diff need it",` && |\n| &&
             `      "",` && |\n| &&
             `      "Footer actions",` && |\n| &&
             `      "--------------",` && |\n| &&
             `      "  (i)              this help",` && |\n| &&
             `      "  Copy Tab         put the current tab's content on the clipboard",` && |\n| &&
             `      "  Open on Error    pop these tools open on the Log tab as soon as",` && |\n| &&
             `      "                   anything logs at error level. Off by default",` && |\n| &&
             `      "  ADT              open the ABAP class, at the line of the last",` && |\n| &&
             `      "                   event when the source has been loaded",` && |\n| &&
             `      "  Export           one report over everything, with downloads",` && |\n| &&
             `      "",` && |\n| &&
             `      "On the view tabs",` && |\n| &&
             `      "----------------",` && |\n| &&
             `      "  Apply to App     render the edited XML into the running app with",` && |\n| &&
             `      "                   NO roundtrip and no activation - a local preview",` && |\n| &&
             `      "                   the next response replaces again",` && |\n| &&
             `      "  Reset            put the backend's original XML back",` && |\n| &&
             `      "",` && |\n| &&
             `      "Reporting a bug",` && |\n| &&
             `      "---------------",` && |\n| &&
             `      "  Export -> Download Report gives a text file with the environment,",` && |\n| &&
             `      "  the error, the log and the roundtrip history. Copy as Markdown puts",` && |\n| &&
             `      "  the same content on the clipboard as a GitHub-ready issue body.",` && |\n| &&
             `      "  With Record Payloads on, Download History (JSON) additionally",` && |\n| &&
             `      "  carries the actual request/response bodies.",` && |\n| &&
             `      "",` && |\n| &&
             `      "  The console errors and the roundtrip history survive a page reload",` && |\n| &&
             `      "  (sessionStorage), so an app that died and was reloaded keeps its",` && |\n| &&
             `      "  evidence - those rows are marked with a '*'.",` && |\n| &&
             `    ].join("\n");` && |\n| &&
             `` && |\n| &&
             `    function formatHelp() {` && |\n| &&
             `      return HELP;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    return {` && |\n| &&
             `      formatEnvironment,` && |\n| &&
             `      formatHelp,` && |\n| &&
             `      formatRegistry,` && |\n| &&
             `      formatActions,` && |\n| &&
             `      formatLog,` && |\n| &&
             `      formatBindings,` && |\n| &&
             `      findEventLine,` && |\n| &&
             `      // exposed for the unit specs` && |\n| &&
             `      _internals: {` && |\n| &&
             `        scrapeEvents,` && |\n| &&
             `        scrapeBindingAttributes,` && |\n| &&
             `        describeValue,` && |\n| &&
             `        getDistribution,` && |\n| &&
             `      },` && |\n| &&
             `    };` && |\n| &&
             `  },` && |\n| &&
             `);` && |\n| &&
             `` && |\n| &&
              ``.

  ENDMETHOD.

ENDCLASS.
