* =====================================================================
* GENERATED FILE - DO NOT EDIT (AGENTS.md rule 2)
* Source: app/webapp/devtools/SlotXml.js
* Embedded frontend resource, generated by tools/app2abap/trans2abap.js.
* Change the source file above and run 'npm run app2abap' to regenerate;
* the check_app2abap CI gate fails any manual edit here.
* =====================================================================
CLASS z2ui5_cl_ui5f_slotxml_js DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CLASS-METHODS get
      RETURNING
        VALUE(result) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS z2ui5_cl_ui5f_slotxml_js IMPLEMENTATION.

  METHOD get.

    result = `sap.ui.define(["z2ui5/core/ViewSlots"], (ViewSlots) => {` && |\n| &&
             `  "use strict";` && |\n| &&
             `` && |\n| &&
             `  function viewContent(view) {` && |\n| &&
             `    return view?.mProperties?.viewContent;` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  function slotXml(ctx, slotKey) {` && |\n| &&
             `    if (!slotKey) return "";` && |\n| &&
             `    return (` && |\n| &&
             `      viewContent(ViewSlots.getView?.(ctx, slotKey)) ||` && |\n| &&
             `      ViewSlots.getViewXml?.(ctx, slotKey) ||` && |\n| &&
             `      ""` && |\n| &&
             `    );` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  return { viewContent, slotXml };` && |\n| &&
             `});` && |\n| &&
             `` && |\n| &&
              ``.

  ENDMETHOD.

ENDCLASS.
