* =====================================================================
* GENERATED FILE - DO NOT EDIT (AGENTS.md rule 2)
* Source: app/webapp/devtools/Tabs.js
* Embedded frontend resource, generated by tools/app2abap/trans2abap.js.
* Change the source file above and run 'npm run app2abap' to regenerate;
* the check_app2abap CI gate fails any manual edit here.
* =====================================================================
CLASS z2ui5_cl_ui5f_tabs_js DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CLASS-METHODS get
      RETURNING
        VALUE(result) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS z2ui5_cl_ui5f_tabs_js IMPLEMENTATION.

  METHOD get.

    result = `sap.ui.define(` && |\n| &&
             `  [` && |\n| &&
             `    "z2ui5/core/AppState",` && |\n| &&
             `    "z2ui5/core/ViewSlots",` && |\n| &&
             `    "z2ui5/devtools/Format",` && |\n| &&
             `    "z2ui5/devtools/Inspect",` && |\n| &&
             `    "z2ui5/devtools/Picker",` && |\n| &&
             `    "z2ui5/devtools/Recorder",` && |\n| &&
             `  ],` && |\n| &&
             `  (AppState, ViewSlots, Format, Inspect, Picker, Recorder) => {` && |\n| &&
             `    "use strict";` && |\n| &&
             `` && |\n| &&
             `    function getModelJson(view) {` && |\n| &&
             `      const model = view?.getModel?.();` && |\n| &&
             `      return model?.getData?.();` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function hasModelData(slotKey) {` && |\n| &&
             `      const data = getModelJson(ViewSlots.getView(slotKey));` && |\n| &&
             `      return Boolean(data) && Object.keys(data).length > 0;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function getViewContent(view) {` && |\n| &&
             `      return view?.mProperties?.viewContent;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function getRenderedContent(view) {` && |\n| &&
             `      return view?._xContent?.outerHTML;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function getSlotXml(slotKey) {` && |\n| &&
             `      return (` && |\n| &&
             `        getViewContent(ViewSlots.getView(slotKey)) ||` && |\n| &&
             `        ViewSlots.getViewXml(slotKey) ||` && |\n| &&
             `        ""` && |\n| &&
             `      );` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function slotFilled(slotKey) {` && |\n| &&
             `      return Boolean(getSlotXml(slotKey));` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    const GROUPS = [` && |\n| &&
             `      { key: "OVERVIEW", label: "Overview" },` && |\n| &&
             `      { key: "PROBLEMS", label: "Problems" },` && |\n| &&
             `      { key: "ROUNDTRIPS", label: "Roundtrips" },` && |\n| &&
             `      { key: "VIEWDATA", label: "View & Data" },` && |\n| &&
             `      { key: "SYSTEM", label: "System" },` && |\n| &&
             `      { key: "SEARCH", label: "Search" },` && |\n| &&
             `    ];` && |\n| &&
             `` && |\n| &&
             `    const DEFAULT_GROUP = "OVERVIEW";` && |\n| &&
             `` && |\n| &&
             `    const SLOTS = [` && |\n| &&
             `      { key: "MAIN", label: "Main" },` && |\n| &&
             `      { key: "POPUP", label: "Popup" },` && |\n| &&
             `      { key: "POPOVER", label: "Popover" },` && |\n| &&
             `      { key: "NEST", label: "Nested 1" },` && |\n| &&
             `      { key: "NEST2", label: "Nested 2" },` && |\n| &&
             `    ];` && |\n| &&
             `` && |\n| &&
             `    const ASPECTS = ["XML", "MODEL", "BINDINGS"];` && |\n| &&
             `` && |\n| &&
             `    const TABS = [` && |\n| &&
             `      {` && |\n| &&
             `        key: "OVERVIEW",` && |\n| &&
             `        group: "OVERVIEW",` && |\n| &&
             `        label: "Overview",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Inspect.formatOverview(),` && |\n| &&
             `` && |\n| &&
             `        searchable: false,` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      {` && |\n| &&
             `        key: "ERROR",` && |\n| &&
             `        group: "PROBLEMS",` && |\n| &&
             `        label: "Error",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Inspect.formatError(),` && |\n| &&
             `        enabled: () => Boolean(AppState.state.lastError),` && |\n| &&
             `        exportOrder: 20,` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "LOG",` && |\n| &&
             `        group: "PROBLEMS",` && |\n| &&
             `        label: "Log",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Inspect.formatLog(),` && |\n| &&
             `        exportOrder: 30,` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      {` && |\n| &&
             `        key: "HISTORY",` && |\n| &&
             `        group: "ROUNDTRIPS",` && |\n| &&
             `        label: "History",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Recorder.formatHistory(),` && |\n| &&
             `        exportOrder: 40,` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "REQUEST",` && |\n| &&
             `        group: "ROUNDTRIPS",` && |\n| &&
             `        label: "Request",` && |\n| &&
             `        kind: "json",` && |\n| &&
             `        produce: () => Format.toJson(AppState.state.oBody),` && |\n| &&
             `        exportOrder: 80,` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "PLAIN",` && |\n| &&
             `        group: "ROUNDTRIPS",` && |\n| &&
             `        label: "Response",` && |\n| &&
             `        kind: "json",` && |\n| &&
             `        produce: () => Format.toJson(AppState.state.responseData),` && |\n| &&
             `        exportOrder: 70,` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "ACTIONS",` && |\n| &&
             `        group: "ROUNDTRIPS",` && |\n| &&
             `        label: "Actions",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Inspect.formatActions(),` && |\n| &&
             `        exportOrder: 60,` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "DIFF",` && |\n| &&
             `        group: "ROUNDTRIPS",` && |\n| &&
             `        label: "Model Diff",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Recorder.formatModelDiff(),` && |\n| &&
             `` && |\n| &&
             `        exportOrder: 50,` && |\n| &&
             `        inExport: () => Recorder.isRecordingPayloads(),` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "VIEWDIFF",` && |\n| &&
             `        group: "ROUNDTRIPS",` && |\n| &&
             `        label: "View Diff",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Recorder.formatViewDiff(),` && |\n| &&
             `        exportOrder: 51,` && |\n| &&
             `        inExport: () => Recorder.isRecordingPayloads(),` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      {` && |\n| &&
             `        key: "VIEW",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "MAIN",` && |\n| &&
             `        aspect: "XML",` && |\n| &&
             `        label: "XML",` && |\n| &&
             `        kind: "xml",` && |\n| &&
             `        produce: () => Format.prettifyXml(getSlotXml("MAIN")),` && |\n| &&
             `        rendered: () =>` && |\n| &&
             `          Format.prettifyXml(getRenderedContent(ViewSlots.getView("MAIN"))),` && |\n| &&
             `        enabled: () => slotFilled("MAIN"),` && |\n| &&
             `        exportOrder: 90,` && |\n| &&
             `        exportTitle: "VIEW",` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "MODEL",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "MAIN",` && |\n| &&
             `        aspect: "MODEL",` && |\n| &&
             `        label: "Model",` && |\n| &&
             `        kind: "json",` && |\n| &&
             `        produce: () => Format.toJson(getModelJson(ViewSlots.getView("MAIN"))),` && |\n| &&
             `        enabled: () => hasModelData("MAIN"),` && |\n| &&
             `        exportOrder: 91,` && |\n| &&
             `        exportTitle: "VIEW MODEL",` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "BINDINGS",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "MAIN",` && |\n| &&
             `        aspect: "BINDINGS",` && |\n| &&
             `        label: "Bindings",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Inspect.formatBindings("MAIN"),` && |\n| &&
             `        enabled: () => hasModelData("MAIN"),` && |\n| &&
             `        exportOrder: 92,` && |\n| &&
             `        exportTitle: "VIEW BINDINGS",` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      {` && |\n| &&
             `        key: "POPUP",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "POPUP",` && |\n| &&
             `        aspect: "XML",` && |\n| &&
             `        label: "XML",` && |\n| &&
             `        kind: "xml",` && |\n| &&
             `        produce: () => Format.prettifyXml(getSlotXml("POPUP")),` && |\n| &&
             `        enabled: () => slotFilled("POPUP"),` && |\n| &&
             `        exportOrder: 100,` && |\n| &&
             `` && |\n| &&
             `        exportTitle: "POPUP",` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "POPUP_MODEL",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "POPUP",` && |\n| &&
             `        aspect: "MODEL",` && |\n| &&
             `        label: "Model",` && |\n| &&
             `        kind: "json",` && |\n| &&
             `        produce: () => Format.toJson(getModelJson(ViewSlots.getView("POPUP"))),` && |\n| &&
             `        enabled: () => hasModelData("POPUP"),` && |\n| &&
             `        exportOrder: 101,` && |\n| &&
             `        exportTitle: "POPUP MODEL",` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "POPUP_BINDINGS",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "POPUP",` && |\n| &&
             `        aspect: "BINDINGS",` && |\n| &&
             `        label: "Bindings",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Inspect.formatBindings("POPUP"),` && |\n| &&
             `        enabled: () => hasModelData("POPUP"),` && |\n| &&
             `        exportOrder: 102,` && |\n| &&
             `        exportTitle: "POPUP BINDINGS",` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      {` && |\n| &&
             `        key: "POPOVER",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "POPOVER",` && |\n| &&
             `        aspect: "XML",` && |\n| &&
             `        label: "XML",` && |\n| &&
             `        kind: "xml",` && |\n| &&
             `        produce: () => Format.prettifyXml(getSlotXml("POPOVER")),` && |\n| &&
             `        enabled: () => slotFilled("POPOVER"),` && |\n| &&
             `        exportOrder: 110,` && |\n| &&
             `        exportTitle: "POPOVER",` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "POPOVER_MODEL",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "POPOVER",` && |\n| &&
             `        aspect: "MODEL",` && |\n| &&
             `        label: "Model",` && |\n| &&
             `        kind: "json",` && |\n| &&
             `        produce: () =>` && |\n| &&
             `          Format.toJson(getModelJson(ViewSlots.getView("POPOVER"))),` && |\n| &&
             `        enabled: () => hasModelData("POPOVER"),` && |\n| &&
             `        exportOrder: 111,` && |\n| &&
             `        exportTitle: "POPOVER MODEL",` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "POPOVER_BINDINGS",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "POPOVER",` && |\n| &&
             `        aspect: "BINDINGS",` && |\n| &&
             `        label: "Bindings",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Inspect.formatBindings("POPOVER"),` && |\n| &&
             `        enabled: () => hasModelData("POPOVER"),` && |\n| &&
             `        exportOrder: 112,` && |\n| &&
             `        exportTitle: "POPOVER BINDINGS",` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      {` && |\n| &&
             `        key: "NEST1",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "NEST",` && |\n| &&
             `        aspect: "XML",` && |\n| &&
             `        label: "XML",` && |\n| &&
             `        kind: "xml",` && |\n| &&
             `        produce: () => Format.prettifyXml(getSlotXml("NEST")),` && |\n| &&
             `        rendered: () =>` && |\n| &&
             `          Format.prettifyXml(getRenderedContent(ViewSlots.getView("NEST"))),` && |\n| &&
             `        enabled: () => slotFilled("NEST"),` && |\n| &&
             `        exportOrder: 120,` && |\n| &&
             `        exportTitle: "NEST1",` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "NEST2",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "NEST2",` && |\n| &&
             `        aspect: "XML",` && |\n| &&
             `        label: "XML",` && |\n| &&
             `        kind: "xml",` && |\n| &&
             `        produce: () => Format.prettifyXml(getSlotXml("NEST2")),` && |\n| &&
             `        rendered: () =>` && |\n| &&
             `          Format.prettifyXml(getRenderedContent(ViewSlots.getView("NEST2"))),` && |\n| &&
             `        enabled: () => slotFilled("NEST2"),` && |\n| &&
             `        exportOrder: 121,` && |\n| &&
             `        exportTitle: "NEST2",` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      {` && |\n| &&
             `        key: "PICK",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        aspect: "PICK",` && |\n| &&
             `        label: "Picked Control",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () =>` && |\n| &&
             `          Picker.lastReport() ||` && |\n| &&
             `          'No control picked yet - press "Pick Control", then click any' +` && |\n| &&
             `            " control in the app.",` && |\n| &&
             `        searchable: true,` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      {` && |\n| &&
             `        key: "SEARCH",` && |\n| &&
             `        group: "SEARCH",` && |\n| &&
             `        label: "Search",` && |\n| &&
             `` && |\n| &&
             `        kind: "search",` && |\n| &&
             `        produce: () => "",` && |\n| &&
             `` && |\n| &&
             `        searchable: false,` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      {` && |\n| &&
             `        key: "ENV",` && |\n| &&
             `        group: "SYSTEM",` && |\n| &&
             `        label: "Environment",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Inspect.formatEnvironment(),` && |\n| &&
             `` && |\n| &&
             `        exportOrder: 10,` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "REGISTRY",` && |\n| &&
             `        group: "SYSTEM",` && |\n| &&
             `        label: "Registry",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Inspect.formatRegistry(),` && |\n| &&
             `        exportOrder: 61,` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "SOURCE",` && |\n| &&
             `        group: "SYSTEM",` && |\n| &&
             `        label: "ABAP Source",` && |\n| &&
             `` && |\n| &&
             `        kind: "source",` && |\n| &&
             `        produce: () => "",` && |\n| &&
             `` && |\n| &&
             `        searchable: false,` && |\n| &&
             `      },` && |\n| &&
             `    ];` && |\n| &&
             `` && |\n| &&
             `    const byKey = new Map(TABS.map((tab) => [tab.key, tab]));` && |\n| &&
             `` && |\n| &&
             `    function get(tabKey) {` && |\n| &&
             `      return byKey.get(tabKey);` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function isKnown(tabKey) {` && |\n| &&
             `      return Boolean(tabKey && byKey.has(tabKey));` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function isEnabled(tab) {` && |\n| &&
             `      if (!tab) return false;` && |\n| &&
             `      try {` && |\n| &&
             `        return tab.enabled ? Boolean(tab.enabled()) : true;` && |\n| &&
             `      } catch {` && |\n| &&
             `        return false;` && |\n| &&
             `      }` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function groupOf(tabKey) {` && |\n| &&
             `      return get(tabKey)?.group || DEFAULT_GROUP;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function enabledTabs(groupKey) {` && |\n| &&
             `      return TABS.filter((tab) => tab.group === groupKey && isEnabled(tab));` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function firstTabOf(groupKey) {` && |\n| &&
             `      const [first] = enabledTabs(groupKey);` && |\n| &&
             `      return first?.key || "";` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function enabledSlots() {` && |\n| &&
             `      const available = new Set(` && |\n| &&
             `        enabledTabs("VIEWDATA")` && |\n| &&
             `          .filter((tab) => tab.slot)` && |\n| &&
             `          .map((tab) => tab.slot),` && |\n| &&
             `      );` && |\n| &&
             `      return SLOTS.filter((slot) => available.has(slot.key));` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function aspectsOfSlot(slotKey) {` && |\n| &&
             `      return enabledTabs("VIEWDATA")` && |\n| &&
             `        .filter((tab) => tab.slot === slotKey)` && |\n| &&
             `        .sort((a, b) => ASPECTS.indexOf(a.aspect) - ASPECTS.indexOf(b.aspect));` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function tabFor(slotKey, aspect) {` && |\n| &&
             `      const aspects = aspectsOfSlot(slotKey);` && |\n| &&
             `      const exact = aspects.find((tab) => tab.aspect === aspect);` && |\n| &&
             `      return (exact || aspects[0])?.key || "";` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function render(tabKey) {` && |\n| &&
             `      const tab = get(tabKey);` && |\n| &&
             `      if (!tab) return "";` && |\n| &&
             `      try {` && |\n| &&
             `        return tab.produce() ?? "";` && |\n| &&
             `      } catch (e) {` && |\n|.
    result = result &&
             `        return ``(${tab.label} could not be rendered: ${e?.message || e})``;` && |\n| &&
             `      }` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function renderTemplated(tabKey) {` && |\n| &&
             `      const tab = get(tabKey);` && |\n| &&
             `      if (!tab?.rendered) return "";` && |\n| &&
             `      try {` && |\n| &&
             `        return tab.rendered() || "";` && |\n| &&
             `      } catch {` && |\n| &&
             `        return "";` && |\n| &&
             `      }` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function searchableTabs() {` && |\n| &&
             `      return TABS.filter((tab) => tab.searchable !== false && isEnabled(tab));` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function exportTabs() {` && |\n| &&
             `      return TABS.filter((tab) => {` && |\n| &&
             `        if (tab.exportOrder === undefined) return false;` && |\n| &&
             `        if (!isEnabled(tab)) return false;` && |\n| &&
             `        try {` && |\n| &&
             `          return tab.inExport ? Boolean(tab.inExport()) : true;` && |\n| &&
             `        } catch {` && |\n| &&
             `          return false;` && |\n| &&
             `        }` && |\n| &&
             `      }).sort((a, b) => a.exportOrder - b.exportOrder);` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function exportTitle(tab) {` && |\n| &&
             `      return tab.exportTitle || tab.label.toUpperCase();` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    const MAX_HITS_PER_TAB = 20;` && |\n| &&
             `` && |\n| &&
             `    function searchLabel(tab) {` && |\n| &&
             `      const group = GROUPS.find((entry) => entry.key === tab.group);` && |\n| &&
             `      const slot = SLOTS.find((entry) => entry.key === tab.slot);` && |\n| &&
             `      const parts = [group?.label || tab.group];` && |\n| &&
             `      if (slot) parts.push(slot.label);` && |\n| &&
             `      parts.push(tab.label);` && |\n| &&
             `      return parts.join(" > ");` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function search(term) {` && |\n| &&
             `      const needle = String(term || "").toLowerCase();` && |\n| &&
             `      if (!needle) return "(enter a search term)";` && |\n| &&
             `      const sections = [];` && |\n| &&
             `      let totalHits = 0;` && |\n| &&
             `` && |\n| &&
             `      for (const tab of searchableTabs()) {` && |\n| &&
             `        const text = render(tab.key);` && |\n| &&
             `        if (!text) continue;` && |\n| &&
             `        const lines = String(text).split("\n");` && |\n| &&
             `        const hits = [];` && |\n| &&
             `        for (let i = 0; i < lines.length; i += 1) {` && |\n| &&
             `          if (!lines[i].toLowerCase().includes(needle)) continue;` && |\n| &&
             `          hits.push(``    ${String(i + 1).padStart(5)}: ${lines[i].trim()}``);` && |\n| &&
             `          if (hits.length >= MAX_HITS_PER_TAB) break;` && |\n| &&
             `        }` && |\n| &&
             `        if (!hits.length) continue;` && |\n| &&
             `        totalHits += hits.length;` && |\n| &&
             `        sections.push(` && |\n| &&
             `          ``  [${searchLabel(tab)}]  ${hits.length}`` +` && |\n| &&
             `            ``${hits.length >= MAX_HITS_PER_TAB ? "+" : ""} hit(s)``,` && |\n| &&
             `        );` && |\n| &&
             `        sections.push(...hits);` && |\n| &&
             `        sections.push("");` && |\n| &&
             `      }` && |\n| &&
             `` && |\n| &&
             `      const head = [` && |\n| &&
             `        ``Search for "${term}" across every tab``,` && |\n| &&
             `        "",` && |\n| &&
             `        totalHits` && |\n| &&
             `          ? ``${totalHits} hit(s) - the tab is named in brackets.``` && |\n| &&
             `          : "(no hit in any tab)",` && |\n| &&
             `        "",` && |\n| &&
             `      ];` && |\n| &&
             `      return head.concat(sections).join("\n");` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    return {` && |\n| &&
             `      GROUPS,` && |\n| &&
             `      SLOTS,` && |\n| &&
             `      ASPECTS,` && |\n| &&
             `      DEFAULT_GROUP,` && |\n| &&
             `      get,` && |\n| &&
             `      isKnown,` && |\n| &&
             `      isEnabled,` && |\n| &&
             `      groupOf,` && |\n| &&
             `      enabledTabs,` && |\n| &&
             `      firstTabOf,` && |\n| &&
             `      enabledSlots,` && |\n| &&
             `      aspectsOfSlot,` && |\n| &&
             `      tabFor,` && |\n| &&
             `      render,` && |\n| &&
             `      renderTemplated,` && |\n| &&
             `      search,` && |\n| &&
             `      searchableTabs,` && |\n| &&
             `      exportTabs,` && |\n| &&
             `      exportTitle,` && |\n| &&
             `` && |\n| &&
             `      _internals: { TABS, getSlotXml, hasModelData, searchLabel },` && |\n| &&
             `    };` && |\n| &&
             `  },` && |\n| &&
             `);` && |\n| &&
             `` && |\n| &&
              ``.

  ENDMETHOD.

ENDCLASS.
