* =====================================================================
* GENERATED FILE - DO NOT EDIT (AGENTS.md rule 2)
* Source: app/webapp/Util.js
* Embedded frontend resource, generated by tools/app2abap/trans2abap.js.
* Change the source file above and run 'npm run app2abap' to regenerate;
* the check_app2abap CI gate fails any manual edit here.
* =====================================================================
CLASS z2ui5_cl_ui5f_util_js DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CLASS-METHODS get
      RETURNING
        VALUE(result) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS z2ui5_cl_ui5f_util_js IMPLEMENTATION.

  METHOD get.

    result = `sap.ui.define(["z2ui5/model/formatter"], (Formatter) => {` && |\n| &&
             `  "use strict";` && |\n| &&
             `` && |\n| &&
             `  return {` && |\n| &&
             `    DateCreateObject: Formatter.DateCreateObject,` && |\n| &&
             `    DateAbapDateToDateObject: Formatter.DateAbapDateToDateObject,` && |\n| &&
             `    DateAbapDateTimeToDateObject: Formatter.DateAbapDateTimeToDateObject,` && |\n| &&
             `  };` && |\n| &&
             `});` && |\n| &&
             `` && |\n| &&
              ``.

  ENDMETHOD.

ENDCLASS.
