* =====================================================================
* GENERATED FILE - DO NOT EDIT (AGENTS.md rule 2)
* Source: app/webapp/core/actions/ViewOps.js
* Embedded frontend resource, generated by tools/app2abap/trans2abap.js.
* Change the source file above and run 'npm run app2abap' to regenerate;
* the check_app2abap CI gate fails any manual edit here.
* =====================================================================
CLASS z2ui5_cl_ui5f_viewops_js DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CLASS-METHODS get
      RETURNING
        VALUE(result) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS z2ui5_cl_ui5f_viewops_js IMPLEMENTATION.

  METHOD get.

    result = `sap.ui.define(` && |\n| &&
             `  [` && |\n| &&
             `    "sap/ui/model/odata/v2/ODataModel",` && |\n| &&
             `    "z2ui5/core/Lib",` && |\n| &&
             `    "z2ui5/core/ViewSlots",` && |\n| &&
             `    "z2ui5/core/AppState",` && |\n| &&
             `  ],` && |\n| &&
             `  (ODataModel, Lib, ViewSlots, AppState) => {` && |\n| &&
             `    "use strict";` && |\n| &&
             `` && |\n| &&
             `    const TIMER_BUSY_RETRY_MS = 50;` && |\n| &&
             `` && |\n| &&
             `    const SMOOTH_SCROLL_MS = 300;` && |\n| &&
             `` && |\n| &&
             `    function evSetSizeLimit(oController, args) {` && |\n| &&
             `      const hasLimit = args[2] !== undefined && args[2] !== "";` && |\n| &&
             `      const viewKey = hasLimit ? args[2] : args[1];` && |\n| &&
             `      const limit = hasLimit ? Number(args[1]) : NaN;` && |\n| &&
             `` && |\n| &&
             `      const isValidLimit = Number.isFinite(limit) && limit > 0;` && |\n| &&
             `      const previous = AppState.state.viewSizeLimits[viewKey];` && |\n| &&
             `      if (isValidLimit) {` && |\n| &&
             `        AppState.state.viewSizeLimits[viewKey] = limit;` && |\n| &&
             `      } else {` && |\n| &&
             `        delete AppState.state.viewSizeLimits[viewKey];` && |\n| &&
             `      }` && |\n| &&
             `` && |\n| &&
             `      if (previous === AppState.state.viewSizeLimits[viewKey]) return;` && |\n| &&
             `` && |\n| &&
             `      const modelKey = Lib.isRootModelSlot(viewKey) ? "MAIN" : viewKey;` && |\n| &&
             `` && |\n| &&
             `      const view = ViewSlots.getView(modelKey);` && |\n| &&
             `      const model = view` && |\n| &&
             `        ? (ViewSlots.trackedModel(view) ?? view.getModel())` && |\n| &&
             `        : undefined;` && |\n| &&
             `      if (model) {` && |\n| &&
             `        const effective = Lib.effectiveSizeLimit(` && |\n| &&
             `          AppState.state.viewSizeLimits,` && |\n| &&
             `          viewKey,` && |\n| &&
             `        );` && |\n| &&
             `` && |\n| &&
             `        model.setSizeLimit(effective ?? 100);` && |\n| &&
             `        model.refresh(true);` && |\n| &&
             `      }` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function evSetODataModel(oController, args) {` && |\n| &&
             `      let oModel;` && |\n| &&
             `      try {` && |\n| &&
             `        oModel = new ODataModel({` && |\n| &&
             `          serviceUrl: args[1],` && |\n| &&
             `          annotationURI: args[3] || "",` && |\n| &&
             `        });` && |\n| &&
             `        const oView = ViewSlots.getView("MAIN");` && |\n| &&
             `        if (oView) {` && |\n| &&
             `          const name = args[2] || undefined;` && |\n| &&
             `` && |\n| &&
             `          const previous = oView.getModel(name);` && |\n| &&
             `          oView.setModel(oModel, name);` && |\n| &&
             `          AppState.state.odataClients.add(oModel);` && |\n| &&
             `` && |\n| &&
             `          if (` && |\n| &&
             `            previous !== oModel &&` && |\n| &&
             `            AppState.state.odataClients.has(previous)` && |\n| &&
             `          ) {` && |\n| &&
             `            AppState.state.odataClients.delete(previous);` && |\n| &&
             `            previous.destroy();` && |\n| &&
             `          }` && |\n| &&
             `        } else {` && |\n| &&
             `          oModel.destroy();` && |\n| &&
             `        }` && |\n| &&
             `      } catch (e) {` && |\n| &&
             `        Lib.logError(``SET_ODATA_MODEL: failed for '${args[1]}'``, e);` && |\n| &&
             `` && |\n| &&
             `        AppState.state.odataClients.delete(oModel);` && |\n| &&
             `        oModel?.destroy?.();` && |\n| &&
             `      }` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function evBindElement(oController, args) {` && |\n| &&
             `      const slot = args[1] || "MAIN";` && |\n| &&
             `      const view = ViewSlots.getView(slot);` && |\n| &&
             `      if (!view) {` && |\n| &&
             `        Lib.logError(``BIND_ELEMENT: no view for slot '${slot}'``);` && |\n| &&
             `        return;` && |\n| &&
             `      }` && |\n| &&
             `      const path = String(args[3] ?? "").replace(/[{}]/g, "");` && |\n| &&
             `      if (!path) {` && |\n| &&
             `        Lib.logError("BIND_ELEMENT: empty binding path");` && |\n| &&
             `        return;` && |\n| &&
             `      }` && |\n| &&
             `      view.bindElement(``${path}/${args[2]}``);` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function evImageEditorPopupClose(oController) {` && |\n| &&
             `      let image;` && |\n| &&
             `      try {` && |\n| &&
             `        const editor = ViewSlots.byId("POPUP", "imageEditor");` && |\n| &&
             `        if (editor) image = editor.getImagePngDataURL();` && |\n| &&
             `      } catch (e) {` && |\n| &&
             `        Lib.logError("IMAGE_EDITOR_POPUP_CLOSE: getImagePngDataURL failed", e);` && |\n| &&
             `      }` && |\n| &&
             `      ViewSlots.destroy("POPUP");` && |\n| &&
             `      oController.eB(["SAVE"], image);` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function evStartTimer(oController, args) {` && |\n| &&
             `      const timerKey = args[0];` && |\n| &&
             `      const callbackEvent = args[1];` && |\n| &&
             `      const delay = Number(args[2]) || 0;` && |\n| &&
             `      const timers = AppState.state.timers;` && |\n| &&
             `      clearTimeout(timers[timerKey]);` && |\n| &&
             `      const fire = () => {` && |\n| &&
             `        delete timers[timerKey];` && |\n| &&
             `` && |\n| &&
             `        if (!Lib.isControllerAlive(oController)) return;` && |\n| &&
             `` && |\n| &&
             `        if (AppState.state.isBusy) {` && |\n| &&
             `          timers[timerKey] = setTimeout(fire, TIMER_BUSY_RETRY_MS);` && |\n| &&
             `          return;` && |\n| &&
             `        }` && |\n| &&
             `` && |\n| &&
             `        oController.eB([callbackEvent, false, true]);` && |\n| &&
             `      };` && |\n| &&
             `      timers[timerKey] = setTimeout(fire, delay);` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function evSetFocus(oController, args) {` && |\n| &&
             `      const oElement = ViewSlots.resolveById(args[1]);` && |\n| &&
             `      if (!oElement) return;` && |\n| &&
             `` && |\n| &&
             `      const applyFocus = () => {` && |\n| &&
             `        try {` && |\n| &&
             `          const info = oElement.getFocusInfo();` && |\n| &&
             `          if (args[2] != null && args[2] !== "") {` && |\n| &&
             `            info.selectionStart = Number(args[2]);` && |\n| &&
             `          }` && |\n| &&
             `          if (args[3] != null && args[3] !== "") {` && |\n| &&
             `            info.selectionEnd = Number(args[3]);` && |\n| &&
             `          }` && |\n| &&
             `          oElement.applyFocusInfo(info);` && |\n| &&
             `        } catch (e) {` && |\n| &&
             `          Lib.logError(``SET_FOCUS: failed for '${args[1]}'``, e);` && |\n| &&
             `        }` && |\n| &&
             `      };` && |\n| &&
             `` && |\n| &&
             `      Lib.whenRendered(oElement, oController, () => {` && |\n| &&
             `        applyFocus();` && |\n| &&
             `        const dom = oElement.getDomRef();` && |\n| &&
             `        if (dom && dom.contains(document.activeElement)) return;` && |\n| &&
             `` && |\n| &&
             `        const prevActive = document.activeElement;` && |\n| &&
             `` && |\n| &&
             `        const samePlace = (el) =>` && |\n| &&
             `          el == null ||` && |\n| &&
             `          el === document.body ||` && |\n| &&
             `          el === prevActive ||` && |\n| &&
             `          Boolean(el.id && prevActive && el.id === prevActive.id);` && |\n| &&
             `        const delegate = {` && |\n| &&
             `          onAfterRendering: () => {` && |\n| &&
             `            oElement.removeEventDelegate(delegate);` && |\n| &&
             `` && |\n| &&
             `            setTimeout(() => {` && |\n| &&
             `              if (!Lib.isControllerAlive(oController)) return;` && |\n| &&
             `` && |\n| &&
             `              if (!samePlace(document.activeElement)) return;` && |\n| &&
             `              applyFocus();` && |\n| &&
             `            }, 0);` && |\n| &&
             `          },` && |\n| &&
             `        };` && |\n| &&
             `        oElement.addEventDelegate(delegate);` && |\n| &&
             `      });` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function evScrollTo(oController, args) {` && |\n| &&
             `      try {` && |\n| &&
             `        const oElement = ViewSlots.resolveById(args[1]);` && |\n| &&
             `        if (!oElement) return;` && |\n| &&
             `        const y = Number(args[2]) || 0;` && |\n| &&
             `        const x = Number(args[3]) || 0;` && |\n| &&
             `        const behavior = args[4] || "auto";` && |\n| &&
             `        const smooth = behavior === "smooth";` && |\n| &&
             `` && |\n| &&
             `        let handled = false;` && |\n| &&
             `        try {` && |\n| &&
             `          const delegate = oElement.getScrollDelegate?.();` && |\n| &&
             `          if (delegate?.scrollTo) {` && |\n| &&
             `            delegate.scrollTo(x, y, smooth ? SMOOTH_SCROLL_MS : 0);` && |\n| &&
             `            handled = true;` && |\n| &&
             `          }` && |\n| &&
             `        } catch {}` && |\n| &&
             `` && |\n| &&
             `        if (!handled) {` && |\n| &&
             `          const dom =` && |\n| &&
             `            document.getElementById(``${oElement.getId()}-inner``) ||` && |\n| &&
             `            oElement.getDomRef();` && |\n| &&
             `          if (dom?.scrollTo) {` && |\n| &&
             `            dom.scrollTo({ top: y, left: x, behavior });` && |\n| &&
             `          } else if (dom) {` && |\n| &&
             `            dom.scrollTop = y;` && |\n| &&
             `            dom.scrollLeft = x;` && |\n| &&
             `          } else if (oElement.scrollTo) {` && |\n| &&
             `            oElement.scrollTo(y, smooth ? SMOOTH_SCROLL_MS : 0);` && |\n| &&
             `          }` && |\n| &&
             `        }` && |\n| &&
             `      } catch (e) {` && |\n| &&
             `        Lib.logError(``SCROLL_TO: failed for '${args[1]}'``, e);` && |\n| &&
             `      }` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function evScrollIntoView(oController, args) {` && |\n| &&
             `      try {` && |\n| &&
             `        const oElement = ViewSlots.resolveById(args[1]);` && |\n| &&
             `        if (!oElement) return;` && |\n| &&
             `        const dom = oElement.getDomRef();` && |\n| &&
             `        if (!dom || !dom.scrollIntoView) return;` && |\n| &&
             `        dom.scrollIntoView({` && |\n| &&
             `          behavior: args[2] || "smooth",` && |\n| &&
             `          block: args[3] || "start",` && |\n| &&
             `          inline: args[4] || "nearest",` && |\n| &&
             `        });` && |\n| &&
             `      } catch (e) {` && |\n| &&
             `        Lib.logError(``SCROLL_INTO_VIEW: failed for '${args[1]}'``, e);` && |\n| &&
             `      }` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function evZ2ui5Custom(oController, args) {` && |\n| &&
             `      try {` && |\n| &&
             `        const fn = AppState.getGlobal(args[1]);` && |\n| &&
             `        if (typeof fn === "function") {` && |\n| &&
             `          fn(args.slice(2));` && |\n| &&
             `        } else {` && |\n| &&
             `          Lib.logError(``Z2UI5: 'z2ui5.${args[1]}' is not a function``);` && |\n| &&
             `        }` && |\n| &&
             `      } catch (e) {` && |\n| &&
             `        Lib.logError(``Z2UI5: '${args[1]}' failed``, e);` && |\n| &&
             `      }` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function evWizardSetNextStep(oController, args) {` && |\n| &&
             `      try {` && |\n| &&
             `        const wiz = ViewSlots.resolveById(args[1]);` && |\n| &&
             `        const step = ViewSlots.resolveById(args[2]);` && |\n| &&
             `        const nextStep = ViewSlots.resolveById(args[3]);` && |\n| &&
             `        if (!wiz || !step) {` && |\n| &&
             `          Lib.logError(` && |\n| &&
             `            ``WIZARD_SET_NEXT_STEP: '${args[1]}' / '${args[2]}' not found``,` && |\n| &&
             `          );` && |\n| &&
             `        }` && |\n| &&
             `        if (wiz && step) wiz.discardProgress(step);` && |\n| &&
             `        if (step && nextStep) step.setNextStep(nextStep);` && |\n| &&
             `      } catch (e) {` && |\n| &&
             `        Lib.logError(``WIZARD_SET_NEXT_STEP: failed for wizard '${args[1]}'``, e);` && |\n| &&
             `      }` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    const handlers = {` && |\n| &&
             `      SET_SIZE_LIMIT: evSetSizeLimit,` && |\n| &&
             `      SET_ODATA_MODEL: evSetODataModel,` && |\n| &&
             `      BIND_ELEMENT: evBindElement,` && |\n| &&
             `      IMAGE_EDITOR_POPUP_CLOSE: evImageEditorPopupClose,` && |\n| &&
             `      START_TIMER: evStartTimer,` && |\n| &&
             `      SET_FOCUS: evSetFocus,` && |\n| &&
             `      SCROLL_TO: evScrollTo,` && |\n| &&
             `      SCROLL_INTO_VIEW: evScrollIntoView,` && |\n| &&
             `      Z2UI5: evZ2ui5Custom,` && |\n| &&
             `      WIZARD_SET_NEXT_STEP: evWizardSetNextStep,` && |\n| &&
             `    };` && |\n| &&
             `` && |\n| &&
             `    return { handlers };` && |\n| &&
             `  },` && |\n| &&
             `);` && |\n| &&
             `` && |\n| &&
              ``.

  ENDMETHOD.

ENDCLASS.
