* =====================================================================
* GENERATED FILE - DO NOT EDIT (AGENTS.md rule 2)
* Source: app/webapp/Component.js
* Embedded frontend resource, generated by tools/app2abap/trans2abap.js.
* Change the source file above and run 'npm run app2abap' to regenerate;
* the check_app2abap CI gate fails any manual edit here.
* =====================================================================
CLASS z2ui5_cl_ui5f_comp_js DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CLASS-METHODS get
      RETURNING
        VALUE(result) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS z2ui5_cl_ui5f_comp_js IMPLEMENTATION.

  METHOD get.

    result = `sap.ui.define(` && |\n| &&
             `  [` && |\n| &&
             `    "sap/ui/core/UIComponent",` && |\n| &&
             `    "z2ui5/model/models",` && |\n| &&
             `    "z2ui5/core/Server",` && |\n| &&
             `    "z2ui5/core/Session",` && |\n| &&
             `    "sap/ui/VersionInfo",` && |\n| &&
             `    "z2ui5/devtools/DevTools",` && |\n| &&
             `    "z2ui5/core/Lib",` && |\n| &&
             `    "z2ui5/core/Env",` && |\n| &&
             `    "z2ui5/core/Context",` && |\n| &&
             `    "z2ui5/core/Router",` && |\n| &&
             `    "z2ui5/core/ScrollFocus",` && |\n| &&
             `    "z2ui5/core/ViewSlots",` && |\n| &&
             `    "z2ui5/core/actions/Shortcuts",` && |\n| &&
             `  ],` && |\n| &&
             `  (` && |\n| &&
             `    UIComponent,` && |\n| &&
             `    Models,` && |\n| &&
             `    Server,` && |\n| &&
             `    Session,` && |\n| &&
             `    VersionInfo,` && |\n| &&
             `    DevTools,` && |\n| &&
             `    Lib,` && |\n| &&
             `    Env,` && |\n| &&
             `    Context,` && |\n| &&
             `    Router,` && |\n| &&
             `    ScrollFocus,` && |\n| &&
             `    ViewSlots,` && |\n| &&
             `    Shortcuts,` && |\n| &&
             `  ) => {` && |\n| &&
             `    "use strict";` && |\n| &&
             `` && |\n| &&
             `    return UIComponent.extend("z2ui5.Component", {` && |\n| &&
             `      metadata: {` && |\n| &&
             `        manifest: "json",` && |\n| &&
             `        interfaces: ["sap.ui.core.IAsyncContentCreation"],` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      init() {` && |\n| &&
             `        this.ctx = Context.create(this);` && |\n| &&
             `        const state = this.ctx.state;` && |\n| &&
             `` && |\n| &&
             `        const {` && |\n| &&
             `          checkLocal,` && |\n| &&
             `          ccResourceRoot,` && |\n| &&
             `          cccResourceRoot,` && |\n| &&
             `          ...componentData` && |\n| &&
             `        } = this.getComponentData() || {};` && |\n| &&
             `        state.checkLocal = checkLocal === true;` && |\n| &&
             `        state.ccResourceRoot = ccResourceRoot || null;` && |\n| &&
             `        state.cccResourceRoot = cccResourceRoot || null;` && |\n| &&
             `` && |\n| &&
             `        const paths = {};` && |\n| &&
             `        if (state.ccResourceRoot) paths.z2ui5_cci = state.ccResourceRoot;` && |\n| &&
             `        if (state.cccResourceRoot) paths.z2ui5_ccc = state.cccResourceRoot;` && |\n| &&
             `        if (Object.keys(paths).length) sap.ui.loader.config({ paths });` && |\n| &&
             `` && |\n| &&
             `        UIComponent.prototype.init.call(this);` && |\n| &&
             `` && |\n| &&
             `        state.oConfig.ComponentData = Object.keys(componentData).length` && |\n| &&
             `          ? componentData` && |\n| &&
             `          : undefined;` && |\n| &&
             `` && |\n| &&
             `        state.oDeviceModel = Models.createDeviceModel();` && |\n| &&
             `        this.setModel(state.oDeviceModel, "device");` && |\n| &&
             `` && |\n| &&
             `        if (Env.hasMessagingModule()) {` && |\n| &&
             `          sap.ui.require(` && |\n| &&
             `            ["sap/ui/core/Messaging"],` && |\n| &&
             `            () => {},` && |\n| &&
             `            () => {},` && |\n| &&
             `          );` && |\n| &&
             `        }` && |\n| &&
             `` && |\n| &&
             `        this._initLaunchpad();` && |\n| &&
             `        this._initVersionInfo();` && |\n| &&
             `` && |\n| &&
             `        this._installUnloadListener();` && |\n| &&
             `` && |\n| &&
             `        DevTools.install(this.ctx);` && |\n| &&
             `        this._installScrollListener();` && |\n| &&
             `        this._installRouterListener();` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      _installUnloadListener() {` && |\n| &&
             `        this._boundUnload = this._onUnload.bind(this);` && |\n| &&
             `` && |\n| &&
             `        this._unloadEvent = "pagehide";` && |\n| &&
             `        window.addEventListener(this._unloadEvent, this._boundUnload);` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      _installScrollListener() {` && |\n| &&
             `        const ctx = this.ctx;` && |\n| &&
             `        this._boundScroll = (event) => ScrollFocus.onScrollCapture(ctx, event);` && |\n| &&
             `        document.addEventListener("scroll", this._boundScroll, {` && |\n| &&
             `          capture: true,` && |\n| &&
             `          passive: true,` && |\n| &&
             `        });` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      _installRouterListener() {` && |\n| &&
             `        const ctx = this.ctx;` && |\n| &&
             `        Router.init(ctx, () => Server.restoreFromRoute(ctx));` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      _initLaunchpad() {` && |\n| &&
             `        const Container = sap.ui.require("sap/ushell/Container");` && |\n| &&
             `        if (!Container) return;` && |\n| &&
             `` && |\n| &&
             `        const launchpad = { Container };` && |\n| &&
             `        this._launchpad = launchpad;` && |\n| &&
             `        this.ctx.state.oLaunchpad = launchpad;` && |\n| &&
             `` && |\n| &&
             `        const setIfAlive = (key, value) => {` && |\n| &&
             `          if (Lib.isAlive(this) && this._launchpad === launchpad) {` && |\n| &&
             `            launchpad[key] = value;` && |\n| &&
             `          }` && |\n| &&
             `        };` && |\n| &&
             `` && |\n| &&
             `        this.getService("ShellUIService")` && |\n| &&
             `          .then((s) => setIfAlive("ShellUIService", s))` && |\n| &&
             `          .catch((e) =>` && |\n| &&
             `            Lib.logError("Component: ShellUIService init failed", e),` && |\n| &&
             `          );` && |\n| &&
             `` && |\n| &&
             `        Container.getServiceAsync("CrossApplicationNavigation")` && |\n| &&
             `          .then((s) => setIfAlive("CrossAppNavigator", s))` && |\n| &&
             `          .catch((e) =>` && |\n| &&
             `            Lib.logError(` && |\n| &&
             `              "Component: CrossApplicationNavigation init failed",` && |\n| &&
             `              e,` && |\n| &&
             `            ),` && |\n| &&
             `          );` && |\n| &&
             `` && |\n| &&
             `        sap.ui.require(` && |\n| &&
             `          ["sap/ushell/services/AppConfiguration"],` && |\n| &&
             `          (ac) => setIfAlive("AppConfiguration", ac),` && |\n| &&
             `          (e) => Lib.logError("Component: AppConfiguration init failed", e),` && |\n| &&
             `        );` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      async _initVersionInfo() {` && |\n| &&
             `        try {` && |\n| &&
             `          const info = await VersionInfo.load();` && |\n| &&
             `          if (Lib.isAlive(this)) {` && |\n| &&
             `            this.ctx.state.oConfig.S_UI5 = {` && |\n| &&
             `              VERSION: info.version,` && |\n| &&
             `              BUILDTIMESTAMP: info.buildTimestamp,` && |\n| &&
             `              GAV: info.gav,` && |\n| &&
             `              THEME: Env.getTheme(),` && |\n| &&
             `            };` && |\n| &&
             `          }` && |\n| &&
             `        } catch (e) {` && |\n| &&
             `          Lib.logError("Component: VersionInfo load failed", e);` && |\n| &&
             `        }` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      _onUnload(event) {` && |\n| &&
             `        if (event?.persisted) return;` && |\n| &&
             `` && |\n| &&
             `        this.destroy();` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      exit() {` && |\n| &&
             `        const ctx = this.ctx;` && |\n| &&
             `        window.removeEventListener(this._unloadEvent, this._boundUnload);` && |\n| &&
             `        document.removeEventListener("scroll", this._boundScroll, {` && |\n| &&
             `          capture: true,` && |\n| &&
             `        });` && |\n| &&
             `        Router.exit(ctx);` && |\n| &&
             `` && |\n| &&
             `        DevTools.exit(ctx);` && |\n| &&
             `` && |\n| &&
             `        Shortcuts.reset(ctx);` && |\n| &&
             `` && |\n| &&
             `        Server.endSession(ctx);` && |\n| &&
             `` && |\n| &&
             `        Server.reset(ctx);` && |\n| &&
             `` && |\n| &&
             `        Session.reset(ctx);` && |\n| &&
             `` && |\n| &&
             `        ViewSlots.destroy(ctx, "POPUP");` && |\n| &&
             `        ViewSlots.destroy(ctx, "POPOVER");` && |\n| &&
             `` && |\n| &&
             `        Lib.cancelPendingTimers(ctx);` && |\n| &&
             `        if (ctx.state.oDeviceModel) {` && |\n| &&
             `          ctx.state.oDeviceModel.destroy();` && |\n| &&
             `        }` && |\n| &&
             `` && |\n| &&
             `        sap.ui.require("z2ui5/cc/Dirty")?.reset?.(ctx);` && |\n| &&
             `` && |\n| &&
             `        for (const oClient of ctx.state.odataClients) {` && |\n| &&
             `          try {` && |\n| &&
             `            oClient.destroy();` && |\n| &&
             `          } catch (e) {` && |\n| &&
             `            Lib.logError("Component: destroying an OData client failed", e);` && |\n| &&
             `          }` && |\n| &&
             `        }` && |\n| &&
             `` && |\n| &&
             `        try {` && |\n| &&
             `          this._launchpad?.Container?.setDirtyFlag?.(false);` && |\n| &&
             `        } catch (e) {` && |\n| &&
             `          Lib.logError("Component: clearing FLP dirty flag failed", e);` && |\n| &&
             `        }` && |\n| &&
             `        this._launchpad = null;` && |\n| &&
             `` && |\n| &&
             `        ScrollFocus.reset(ctx);` && |\n| &&
             `        Context.destroy(ctx);` && |\n| &&
             `` && |\n| &&
             `        if (UIComponent.prototype.exit) UIComponent.prototype.exit.call(this);` && |\n| &&
             `      },` && |\n| &&
             `    });` && |\n| &&
             `  },` && |\n| &&
             `);` && |\n| &&
             `` && |\n| &&
              ``.

  ENDMETHOD.

ENDCLASS.
