* =====================================================================
* GENERATED FILE - DO NOT EDIT (AGENTS.md rule 2)
* Source: app/webapp/devtools/DeveloperTools.js
* Embedded frontend resource, generated by tools/app2abap/trans2abap.js.
* Change the source file above and run 'npm run app2abap' to regenerate;
* the check_app2abap CI gate fails any manual edit here.
* =====================================================================
CLASS z2ui5_cl_ui5f_dtools_js DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CLASS-METHODS get
      RETURNING
        VALUE(result) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS z2ui5_cl_ui5f_dtools_js IMPLEMENTATION.

  METHOD get.

    result = `sap.ui.define(` && |\n| &&
             `  [` && |\n| &&
             `    "sap/ui/core/Control",` && |\n| &&
             `    "sap/ui/core/Fragment",` && |\n| &&
             `    "sap/ui/model/json/JSONModel",` && |\n| &&
             `    "z2ui5/core/Lib",` && |\n| &&
             `    "z2ui5/core/ErrorView",` && |\n| &&
             `    "z2ui5/devtools/AbapSource",` && |\n| &&
             `    "z2ui5/devtools/Console",` && |\n| &&
             `    "z2ui5/devtools/Inspect",` && |\n| &&
             `    "z2ui5/devtools/LiveEdit",` && |\n| &&
             `    "z2ui5/devtools/Persist",` && |\n| &&
             `    "z2ui5/devtools/Picker",` && |\n| &&
             `    "z2ui5/devtools/Recorder",` && |\n| &&
             `    "z2ui5/devtools/Report",` && |\n| &&
             `    "z2ui5/devtools/Tabs",` && |\n| &&
             `  ],` && |\n| &&
             `  (` && |\n| &&
             `    Control,` && |\n| &&
             `    Fragment,` && |\n| &&
             `    JSONModel,` && |\n| &&
             `    Lib,` && |\n| &&
             `    ErrorView,` && |\n| &&
             `    AbapSource,` && |\n| &&
             `    Console,` && |\n| &&
             `    Inspect,` && |\n| &&
             `    LiveEdit,` && |\n| &&
             `    Persist,` && |\n| &&
             `    Picker,` && |\n| &&
             `    Recorder,` && |\n| &&
             `    Report,` && |\n| &&
             `    Tabs,` && |\n| &&
             `  ) => {` && |\n| &&
             `    "use strict";` && |\n| &&
             `` && |\n| &&
             `    const FRAGMENT_SUFFIX = "tools";` && |\n| &&
             `` && |\n| &&
             `    const LAST_TAB_KEY = "z2ui5.devtools.lastTab";` && |\n| &&
             `` && |\n| &&
             `    const DEFAULT_TAB = "OVERVIEW";` && |\n| &&
             `` && |\n| &&
             `    const STATUS_MS = 6000;` && |\n| &&
             `` && |\n| &&
             `    function readLastTab() {` && |\n| &&
             `      return Persist.read(LAST_TAB_KEY);` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function writeLastTab(tabKey) {` && |\n| &&
             `      Persist.write(LAST_TAB_KEY, tabKey);` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function resolveTab(ctx, tabKey) {` && |\n| &&
             `      if (Tabs.isEnabled(ctx, Tabs.get(tabKey))) return tabKey;` && |\n| &&
             `      if (Tabs.isKnown(tabKey)) {` && |\n| &&
             `        const sibling = Tabs.firstTabOf(ctx, Tabs.groupOf(tabKey));` && |\n| &&
             `        if (sibling) return sibling;` && |\n| &&
             `      }` && |\n| &&
             `      return DEFAULT_TAB;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function preloadCodeEditor() {` && |\n| &&
             `      return new Promise((resolve) => {` && |\n| &&
             `        sap.ui.require(` && |\n| &&
             `          ["sap/ui/codeeditor/library", "sap/ui/codeeditor/CodeEditor"],` && |\n| &&
             `          () => resolve(),` && |\n| &&
             `` && |\n| &&
             `          () => resolve(),` && |\n| &&
             `        );` && |\n| &&
             `      });` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    const DeveloperTools = Control.extend("z2ui5.devtools.DeveloperTools", {` && |\n| &&
             `      fragmentId() {` && |\n| &&
             `        return ``${this.getId()}--${FRAGMENT_SUFFIX}``;` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      renderTab(tabKey, oModel) {` && |\n| &&
             `        const ctx = this.ctx;` && |\n| &&
             `        const key = resolveTab(ctx, tabKey);` && |\n| &&
             `        const tab = Tabs.get(key);` && |\n| &&
             `        const data = oModel.getData();` && |\n| &&
             `` && |\n| &&
             `        data.selectedTab = key;` && |\n| &&
             `        data.selectedGroup = tab.group;` && |\n| &&
             `        writeLastTab(key);` && |\n| &&
             `` && |\n| &&
             `        const slots = Tabs.enabledSlots(ctx).map((slot) => ({` && |\n| &&
             `          key: slot.key,` && |\n| &&
             `          text: slot.label,` && |\n| &&
             `        }));` && |\n| &&
             `        data.slots = slots;` && |\n| &&
             `` && |\n| &&
             `        data.selectedSlot = tab.slot || data.selectedSlot || "MAIN";` && |\n| &&
             `        data.showSlotBar = Boolean(tab.slot) && slots.length > 1;` && |\n| &&
             `` && |\n| &&
             `        let views;` && |\n| &&
             `        if (tab.group === "VIEWDATA") {` && |\n| &&
             `          views = Tabs.aspectsOfSlot(ctx, data.selectedSlot).concat(` && |\n| &&
             `            Tabs.get("PICK"),` && |\n| &&
             `          );` && |\n| &&
             `        } else {` && |\n| &&
             `          views = Tabs.enabledTabs(ctx, tab.group);` && |\n| &&
             `        }` && |\n| &&
             `        data.views = views.map((entry) => ({` && |\n| &&
             `          key: entry.key,` && |\n| &&
             `          text: entry.label,` && |\n| &&
             `        }));` && |\n| &&
             `        data.showViewBar = data.views.length > 1;` && |\n| &&
             `` && |\n| &&
             `        data.isOverview = tab.group === "OVERVIEW";` && |\n| &&
             `        data.isRoundtrips = tab.group === "ROUNDTRIPS";` && |\n| &&
             `        data.isViewData = tab.group === "VIEWDATA";` && |\n| &&
             `        data.isSearch = tab.group === "SEARCH";` && |\n| &&
             `        data.isErrorView = key === "ERROR";` && |\n| &&
             `        data.isSourceView = key === "SOURCE";` && |\n| &&
             `        data.hasRetry =` && |\n| &&
             `          key === "ERROR" && typeof ctx.state.lastError?.onRetry === "function";` && |\n| &&
             `        data.recordPayloads = Recorder.isRecordingPayloads();` && |\n| &&
             `        data.openOnError = Console.isAlertOnError();` && |\n| &&
             `` && |\n| &&
             `        data.problemCount = this.problemCount();` && |\n| &&
             `` && |\n| &&
             `        if (tab.kind === "search") {` && |\n| &&
             `          this.displayEditor(oModel, Tabs.search(ctx, data.searchTerm), "text");` && |\n| &&
             `` && |\n| &&
             `          data.isTemplating = false;` && |\n| &&
             `          oModel.refresh();` && |\n| &&
             `          return;` && |\n| &&
             `        }` && |\n| &&
             `` && |\n| &&
             `        if (tab.kind === "source") {` && |\n| &&
             `          data.canApply = false;` && |\n| &&
             `          data.isTemplating = false;` && |\n| &&
             `          data.templatingSource = false;` && |\n| &&
             `          this.showAbapSource(oModel);` && |\n| &&
             `          return;` && |\n| &&
             `        }` && |\n| &&
             `` && |\n| &&
             `        this.displayEditor(oModel, Tabs.render(ctx, key), tab.kind);` && |\n| &&
             `` && |\n| &&
             `        data.canApply = LiveEdit.canApply(ctx, key);` && |\n| &&
             `        oModel.refresh();` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      onGroupSelect(oEvent) {` && |\n| &&
             `        const oModel = oEvent.getSource().getModel();` && |\n| &&
             `        const groupKey = oEvent.getSource().getSelectedKey();` && |\n| &&
             `        this.renderTab(` && |\n| &&
             `          Tabs.firstTabOf(this.ctx, groupKey) || DEFAULT_TAB,` && |\n| &&
             `          oModel,` && |\n| &&
             `        );` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      onViewSelect(oEvent) {` && |\n| &&
             `        const oSource = oEvent.getSource();` && |\n| &&
             `        this.renderTab(oSource.getSelectedKey(), oSource.getModel());` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      onSlotSelect(oEvent) {` && |\n| &&
             `        const oSource = oEvent.getSource();` && |\n| &&
             `        const oModel = oSource.getModel();` && |\n| &&
             `        const aspect = Tabs.get(oModel.getData().selectedTab)?.aspect;` && |\n| &&
             `        this.renderTab(` && |\n| &&
             `          Tabs.tabFor(this.ctx, oSource.getSelectedKey(), aspect),` && |\n| &&
             `          oModel,` && |\n| &&
             `        );` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      onSearch(oEvent) {` && |\n| &&
             `        const oSource = oEvent.getSource();` && |\n| &&
             `        const oModel = oSource.getModel();` && |\n| &&
             `        oModel.getData().searchTerm = oSource.getValue();` && |\n| &&
             `        this.renderTab("SEARCH", oModel);` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      displayEditor(oModel, content, type) {` && |\n| &&
             `        const data = oModel.getData();` && |\n| &&
             `        data.editor_visible = true;` && |\n| &&
             `        data.source_visible = false;` && |\n| &&
             `` && |\n| &&
             `        data.canApply = false;` && |\n| &&
             `        data.isTemplating = Boolean(content?.includes("xmlns:template"));` && |\n| &&
             `` && |\n| &&
             `        data.templatingSource = false;` && |\n| &&
             `        data.value = content;` && |\n| &&
             `        data.previousValue = content;` && |\n| &&
             `        data.xContent = "";` && |\n| &&
             `        data.type = type;` && |\n| &&
             `        oModel.refresh();` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      onTemplatingPress(oEvent) {` && |\n| &&
             `        const oSource = oEvent.getSource();` && |\n| &&
             `        const oModel = oSource.getModel();` && |\n| &&
             `        const data = oModel.getData();` && |\n| &&
             `` && |\n| &&
             `        if (oSource.getPressed()) {` && |\n| &&
             `          if (!data.xContent) {` && |\n| &&
             `            data.xContent = Tabs.renderTemplated(this.ctx, data.selectedTab);` && |\n| &&
             `          }` && |\n| &&
             `          data.value = data.xContent;` && |\n| &&
             `        } else {` && |\n| &&
             `          data.value = data.previousValue;` && |\n| &&
             `        }` && |\n| &&
             `        oModel.refresh();` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      showAbapSource(oModel) {` && |\n| &&
             `        const contentControl = Fragment.byId(this.fragmentId(), "sourceHtml");` && |\n| &&
             `` && |\n| &&
             `        contentControl?.setContent(AbapSource.iframeHtml(this.ctx));` && |\n| &&
             `` && |\n| &&
             `        AbapSource.fetchSource(this.ctx);` && |\n| &&
             `` && |\n| &&
             `        if (!oModel) return;` && |\n| &&
             `        const data = oModel.getData();` && |\n| &&
             `        data.editor_visible = false;` && |\n| &&
             `        data.source_visible = true;` && |\n| &&
             `        oModel.refresh();` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      onOpenAbapInAdt() {` && |\n| &&
             `        AbapSource.openInAdt(this.ctx);` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      showStatus(oModel, text) {` && |\n| &&
             `        const data = oModel.getData();` && |\n| &&
             `        data.statusText = text;` && |\n| &&
             `        data.hasStatusText = Boolean(text);` && |\n| &&
             `        oModel.refresh();` && |\n| &&
             `        if (!text) return;` && |\n| &&
             `        clearTimeout(this._statusTimer);` && |\n| &&
             `        this._statusTimer = setTimeout(() => {` && |\n| &&
             `          if (Lib.isDestroyed(this)) return;` && |\n| &&
             `          data.statusText = "";` && |\n| &&
             `          data.hasStatusText = false;` && |\n| &&
             `          oModel.refresh();` && |\n| &&
             `        }, STATUS_MS);` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      async onReportBug(oEvent) {` && |\n| &&
             `        const oModel = oEvent.getSource().getModel();` && |\n| &&
             `        const source = await AbapSource.fetchSource(this.ctx);` && |\n| &&
             `        if (Lib.isDestroyed(this)) return;` && |\n| &&
             `        this.showStatus(oModel, Report.copyMarkdown(this.ctx, source));` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      async onExport() {` && |\n| &&
             `        const source = await AbapSource.fetchSource(this.ctx);` && |\n| &&
             `        if (Lib.isDestroyed(this)) return;` && |\n| &&
             `        Report.openDialog(this.ctx, AbapSource.appName(this.ctx), source);` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      async onCopyTab(oEvent) {` && |\n| &&
             `        const oSource = oEvent.getSource();` && |\n| &&
             `        const data = oSource.getModel().getData();` && |\n| &&
             `        let text = data.value || "";` && |\n| &&
             `        if (data.isSourceView) {` && |\n| &&
             `          text = await AbapSource.fetchSource(this.ctx);` && |\n| &&
             `          if (Lib.isDestroyed(oSource)) return;` && |\n| &&
             `        }` && |\n| &&
             `        Lib.copyToClipboard(text);` && |\n| &&
             `` && |\n| &&
             `        Report.confirmOnButton(oSource);` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      onErrorRetry() {` && |\n| &&
             `        const onRetry = this.ctx.state.lastError?.onRetry;` && |\n| &&
             `` && |\n| &&
             `        this.reopenErrorOnClose = false;` && |\n| &&
             `        this.close();` && |\n| &&
             `        if (typeof onRetry === "function") onRetry();` && |\n| &&
             `      },` && |\n| &&
             `      onErrorRestart() {` && |\n| &&
             `        window.location.reload();` && |\n| &&
             `      },` && |\n| &&
             `      onErrorLogout() {` && |\n| &&
             `        ErrorView.handleLogout(this.ctx);` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      onToggleRecordPayloads(oEvent) {` && |\n| &&
             `        const oSource = oEvent.getSource();` && |\n| &&
             `        Recorder.setRecordingPayloads(this.ctx, oSource.getPressed());` && |\n| &&
             `        const oModel = oSource.getModel();` && |\n| &&
             `        this.renderTab(oModel.getData().selectedTab, oModel);` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      onToggleOpenOnError(oEvent) {` && |\n| &&
             `        const oSource = oEvent.getSource();` && |\n| &&
             `        Console.setAlertOnError(oSource.getPressed());` && |\n| &&
             `        const oModel = oSource.getModel();` && |\n| &&
             `        oModel.getData().openOnError = Console.isAlertOnError();` && |\n| &&
             `        oModel.refresh();` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      onPickControl() {` && |\n| &&
             `        const previousTab = this.oDialog?.getModel()?.getData()?.selectedTab;` && |\n| &&
             `        this.reopenErrorOnClose = false;` && |\n| &&
             `        this.close();` && |\n| &&
             `        Picker.start(this.ctx, (report) => {` && |\n| &&
             `          if (Lib.isDestroyed(this)) return;` && |\n| &&
             `          this.show(report ? "PICK" : previousTab);` && |\n| &&
             `        });` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      async onApplyXml(oEvent) {` && |\n| &&
             `        const oModel = oEvent.getSource().getModel();` && |\n| &&
             `        const data = oModel.getData();` && |\n| &&
             `        if (LiveEdit.isBusy(this.ctx)) {` && |\n| &&
             `          this.showStatus(oModel, "A roundtrip is running - try again.");` && |\n| &&
             `          return;` && |\n| &&
             `        }` && |\n| &&
             `        const tabKey = data.selectedTab;` && |\n| &&
             `` && |\n| &&
             `        const before = this.backendXml(tabKey);` && |\n| &&
             `        const result = await LiveEdit.apply(this.ctx, tabKey, data.value);` && |\n| &&
             `        if (Lib.isDestroyed(this)) return;` && |\n| &&
             `        if (!this._appliedXml) this._appliedXml = {};` && |\n| &&
             `        this._appliedXml[tabKey] = {` && |\n| &&
             `          original: before,` && |\n| &&
             `` && |\n| &&
             `          applied: Tabs.render(this.ctx, tabKey),` && |\n| &&
             `        };` && |\n| &&
             `        this.showStatus(oModel, result);` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      backendXml(tabKey) {` && |\n| &&
             `        const current = Tabs.render(this.ctx, tabKey);` && |\n| &&
             `        const record = this._appliedXml?.[tabKey];` && |\n| &&
             `        if (!record) return current;` && |\n| &&
             `        if (record.applied !== current) {` && |\n| &&
             `          delete this._appliedXml[tabKey];` && |\n| &&
             `          return current;` && |\n| &&
             `        }` && |\n| &&
             `        return record.original;` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      onResetXml(oEvent) {` && |\n| &&
             `        const oModel = oEvent.getSource().getModel();` && |\n| &&
             `        const data = oModel.getData();` && |\n| &&
             `        const xml = this.backendXml(data.selectedTab);` && |\n| &&
             `        data.value = xml;` && |\n| &&
             `        data.previousValue = xml;` && |\n| &&
             `        oModel.refresh();` && |\n| &&
             `        this.showStatus(oModel, "");` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      onShowHelp() {` && |\n| &&
             `        sap.ui.require(` && |\n| &&
             `          ["sap/m/Dialog", "sap/m/TextArea", "sap/m/Button"],` && |\n| &&
             `          (Dialog, TextArea, Button) => {` && |\n| &&
             `            const area = new TextArea({` && |\n| &&
             `              editable: false,` && |\n| &&
             `              width: "100%",` && |\n| &&
             `              rows: 25,` && |\n| &&
             `              growing: false,` && |\n| &&
             `            });` && |\n| &&
             `            area.setValue(Inspect.formatHelp());` && |\n| &&
             `            const dialog = new Dialog({` && |\n| &&
             `              title: "abap2UI5 - Developer Tools Help",` && |\n| &&
             `              stretch: true,` && |\n| &&
             `              content: [area],` && |\n| &&
             `              buttons: [` && |\n| &&
             `                new Button({` && |\n| &&
             `                  text: "Close",` && |\n| &&
             `                  type: "Emphasized",` && |\n| &&
             `                  press: () => dialog.close(),` && |\n| &&
             `                }),` && |\n| &&
             `              ],` && |\n| &&
             `              afterClose: () => dialog.destroy(),` && |\n| &&
             `            });` && |\n| &&
             `            dialog.open();` && |\n| &&
             `          },` && |\n| &&
             `        );` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      onClose() {` && |\n| &&
             `        this.close();` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      onEscape(oPromise) {` && |\n| &&
             `        oPromise.reject();` && |\n| &&
             `        this.close();` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      async show(initialTab) {` && |\n| &&
             `        if (this._showPending) return;` && |\n| &&
             `        this._showPending = true;` && |\n| &&
             `        try {` && |\n| &&
             `          if (!this.oDialog) {` && |\n| &&
             `            await preloadCodeEditor();` && |\n| &&
             `            this.oDialog = await Fragment.load({` && |\n| &&
             `              name: "z2ui5.devtools.DeveloperTools",` && |\n| &&
             `              controller: this,` && |\n| &&
             `              id: this.fragmentId(),` && |\n| &&
             `            });` && |\n| &&
             `          }` && |\n| &&
             `` && |\n| &&
             `          if (Lib.isDestroyed(this)) {` && |\n| &&
             `            if (this.oDialog) this.oDialog.destroy();` && |\n|.
    result = result &&
             `            this.oDialog = null;` && |\n| &&
             `            return;` && |\n| &&
             `          }` && |\n| &&
             `` && |\n| &&
             `          const requested =` && |\n| &&
             `            typeof initialTab === "string" && initialTab` && |\n| &&
             `              ? initialTab` && |\n| &&
             `              : readLastTab();` && |\n| &&
             `` && |\n| &&
             `          const appName = AbapSource.appName(this.ctx);` && |\n| &&
             `          const oModel = new JSONModel({` && |\n| &&
             `            title: appName` && |\n| &&
             `              ? ``abap2UI5 - Developer Tools - ${appName}``` && |\n| &&
             `              : "abap2UI5 - Developer Tools",` && |\n| &&
             `            selectedGroup: Tabs.DEFAULT_GROUP,` && |\n| &&
             `            selectedTab: DEFAULT_TAB,` && |\n| &&
             `            selectedSlot: "MAIN",` && |\n| &&
             `            searchTerm: "",` && |\n| &&
             `            slots: [],` && |\n| &&
             `            views: [],` && |\n| &&
             `            showSlotBar: false,` && |\n| &&
             `            showViewBar: false,` && |\n| &&
             `            isOverview: true,` && |\n| &&
             `            isRoundtrips: false,` && |\n| &&
             `            isViewData: false,` && |\n| &&
             `            isSearch: false,` && |\n| &&
             `            isErrorView: false,` && |\n| &&
             `            isSourceView: false,` && |\n| &&
             `            hasRetry: false,` && |\n| &&
             `            canApply: false,` && |\n| &&
             `            isTemplating: false,` && |\n| &&
             `            templatingSource: false,` && |\n| &&
             `            statusText: "",` && |\n| &&
             `            hasStatusText: false,` && |\n| &&
             `` && |\n| &&
             `            problemCount: this.problemCount(),` && |\n| &&
             `            recordPayloads: Recorder.isRecordingPayloads(),` && |\n| &&
             `            openOnError: Console.isAlertOnError(),` && |\n| &&
             `            type: "text",` && |\n| &&
             `            value: "",` && |\n| &&
             `            previousValue: "",` && |\n| &&
             `            xContent: "",` && |\n| &&
             `            source_visible: false,` && |\n| &&
             `            editor_visible: true,` && |\n| &&
             `          });` && |\n| &&
             `` && |\n| &&
             `          const oDialog = this.oDialog;` && |\n| &&
             `          oDialog.setModel(oModel);` && |\n| &&
             `          this.renderTab(requested, oModel);` && |\n| &&
             `          oDialog.open();` && |\n| &&
             `        } catch (e) {` && |\n| &&
             `          Lib.logError("DeveloperTools.show failed", e);` && |\n| &&
             `        } finally {` && |\n| &&
             `          this._showPending = false;` && |\n| &&
             `        }` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      problemCount() {` && |\n| &&
             `        const errors = (Lib.errors || []).length;` && |\n| &&
             `        const total = errors + (this.ctx?.state?.lastError ? 1 : 0);` && |\n| &&
             `        return total ? String(total) : "";` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      close() {` && |\n| &&
             `        if (!this.oDialog?.isOpen()) return;` && |\n| &&
             `` && |\n| &&
             `        const reopenError = this.reopenErrorOnClose;` && |\n| &&
             `        this.reopenErrorOnClose = false;` && |\n| &&
             `` && |\n| &&
             `        this.oDialog.close();` && |\n| &&
             `        if (reopenError) ErrorView.reopenErrorDialog(this.ctx);` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      exit() {` && |\n| &&
             `        this.reopenErrorOnClose = false;` && |\n| &&
             `        clearTimeout(this._statusTimer);` && |\n| &&
             `        this._appliedXml = null;` && |\n| &&
             `        if (this.oDialog) {` && |\n| &&
             `          this.oDialog.close();` && |\n| &&
             `          this.oDialog.destroy();` && |\n| &&
             `          this.oDialog = null;` && |\n| &&
             `        }` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      toggle() {` && |\n| &&
             `        if (this.oDialog?.isOpen()) {` && |\n| &&
             `          this.close();` && |\n| &&
             `        } else {` && |\n| &&
             `          this.show();` && |\n| &&
             `        }` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      renderer: Lib.EMPTY_RENDERER,` && |\n| &&
             `    });` && |\n| &&
             `` && |\n| &&
             `    return DeveloperTools;` && |\n| &&
             `  },` && |\n| &&
             `);` && |\n| &&
             `` && |\n| &&
              ``.

  ENDMETHOD.

ENDCLASS.
