* =====================================================================
* GENERATED FILE - DO NOT EDIT (AGENTS.md rule 2)
* Source: app/webapp/core/ErrorView.js
* Embedded frontend resource, generated by tools/app2abap/trans2abap.js.
* Change the source file above and run 'npm run app2abap' to regenerate;
* the check_app2abap CI gate fails any manual edit here.
* =====================================================================
CLASS z2ui5_cl_ui5f_errview_js DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CLASS-METHODS get
      RETURNING
        VALUE(result) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS z2ui5_cl_ui5f_errview_js IMPLEMENTATION.

  METHOD get.

    result = `sap.ui.define(["z2ui5/core/AppState"], (AppState) => {` && |\n| &&
             `  "use strict";` && |\n| &&
             `` && |\n| &&
             `  const ERROR_MAX_LENGTH = 50000;` && |\n| &&
             `` && |\n| &&
             `  const PREVIEW_MAX_LENGTH = 500;` && |\n| &&
             `` && |\n| &&
             `  const DEFAULT_TITLE = "Application Error - Please Restart The App";` && |\n| &&
             `` && |\n| &&
             `  const STYLE_ID = "z2ui5ErrorViewStyle";` && |\n| &&
             `  const DIALOG_CLASS = "z2ui5ErrorDialog";` && |\n| &&
             `  const MESSAGE_CLASS = "z2ui5ErrorMessage";` && |\n| &&
             `  const HINT_CLASS = "z2ui5ErrorHint";` && |\n| &&
             `` && |\n| &&
             `  let lastDialogTitle = "";` && |\n| &&
             `  let lastDialogDetails = "";` && |\n| &&
             `  let lastDialogOptions = {};` && |\n| &&
             `` && |\n| &&
             `  let friendlyDialog = null;` && |\n| &&
             `` && |\n| &&
             `  function decodeEntities(s) {` && |\n| &&
             `    return s` && |\n| &&
             `      .replace(/&nbsp;/gi, " ")` && |\n| &&
             `      .replace(/&lt;/gi, "<")` && |\n| &&
             `      .replace(/&gt;/gi, ">")` && |\n| &&
             `      .replace(/&quot;/gi, '"')` && |\n| &&
             `      .replace(/&apos;|&#0*39;/gi, "'")` && |\n| &&
             `      .replace(/&copy;/gi, String.fromCharCode(169))` && |\n| &&
             `      .replace(/&#(\d+);/g, (_, n) => String.fromCharCode(Number(n)))` && |\n| &&
             `      .replace(/&#x([0-9a-f]+);/gi, (_, n) =>` && |\n| &&
             `        String.fromCharCode(parseInt(n, 16)),` && |\n| &&
             `      )` && |\n| &&
             `      .replace(/&amp;/gi, "&");` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  const cleanText = (s) =>` && |\n| &&
             `    decodeEntities(s.replace(/<[^>]+>/g, " "))` && |\n| &&
             `      .replace(/\s+/g, " ")` && |\n| &&
             `      .trim();` && |\n| &&
             `` && |\n| &&
             `  function extractServerError(html) {` && |\n| &&
             `    const parts = [];` && |\n| &&
             `    const rx = /class="(?:errorTextHeader|detailText)"[^>]*>([\s\S]*?)<\/p>/gi;` && |\n| &&
             `    let m;` && |\n| &&
             `    while ((m = rx.exec(html))) parts.push(cleanText(m[1]));` && |\n| &&
             `    return parts` && |\n| &&
             `      .filter(Boolean)` && |\n| &&
             `      .filter((t) => !/^server time:/i.test(t))` && |\n| &&
             `      .join(" - ");` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  const ERROR_SECTION_HEADER = "--- error ---";` && |\n| &&
             `` && |\n| &&
             `  function extractFrameworkMessages(text) {` && |\n| &&
             `    const lines = text.split("\n");` && |\n| &&
             `    const start = lines.findIndex(` && |\n| &&
             `      (line) => line.trim() === ERROR_SECTION_HEADER,` && |\n| &&
             `    );` && |\n| &&
             `    if (start < 0) return "";` && |\n| &&
             `    const messages = [];` && |\n| &&
             `    for (const line of lines.slice(start + 1)) {` && |\n| &&
             `      if (line.trim().startsWith("---")) break;` && |\n| &&
             `      const cleaned = cleanText(line);` && |\n| &&
             `      if (cleaned) messages.push(cleaned);` && |\n| &&
             `    }` && |\n| &&
             `    return messages.join("\n");` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  function buildErrorPreview(text) {` && |\n| &&
             `    if (!text) return "";` && |\n| &&
             `    let preview = extractFrameworkMessages(text);` && |\n| &&
             `    if (!preview) {` && |\n| &&
             `      preview = text;` && |\n| &&
             `      if (/<[a-z][\s\S]*>/i.test(preview)) {` && |\n| &&
             `        preview =` && |\n| &&
             `          extractServerError(preview) ||` && |\n| &&
             `          cleanText(` && |\n| &&
             `            preview.replace(/<(script|style|title)[\s\S]*?<\/\1>/gi, " "),` && |\n| &&
             `          );` && |\n| &&
             `      }` && |\n| &&
             `      preview = preview.replace(/\s+/g, " ").trim();` && |\n| &&
             `    }` && |\n| &&
             `    return preview.length > PREVIEW_MAX_LENGTH` && |\n| &&
             `      ? ``${preview.slice(0, PREVIEW_MAX_LENGTH)}...``` && |\n| &&
             `      : preview;` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  function copyToClipboard(text) {` && |\n| &&
             `    const value = String(text == null ? "" : text);` && |\n| &&
             `    let copied;` && |\n| &&
             `    const textarea = document.createElement("textarea");` && |\n| &&
             `    textarea.value = value;` && |\n| &&
             `` && |\n| &&
             `    textarea.style.cssText =` && |\n| &&
             `      "position:fixed;top:-9999px;left:-9999px;opacity:0;";` && |\n| &&
             `    textarea.setAttribute("readonly", "");` && |\n| &&
             `    document.body.appendChild(textarea);` && |\n| &&
             `    try {` && |\n| &&
             `      textarea.focus();` && |\n| &&
             `      textarea.select();` && |\n| &&
             `      textarea.setSelectionRange(0, value.length);` && |\n| &&
             `      copied = document.execCommand("copy");` && |\n| &&
             `    } catch {` && |\n| &&
             `      copied = false;` && |\n| &&
             `    }` && |\n| &&
             `    textarea.remove();` && |\n| &&
             `    if (!copied && navigator.clipboard?.writeText) {` && |\n| &&
             `      navigator.clipboard.writeText(value).catch(() => {});` && |\n| &&
             `    }` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  const DIALOG_STYLES = ``` && |\n| &&
             `.${DIALOG_CLASS}.sapMDialog,` && |\n| &&
             `.${DIALOG_CLASS} .sapMDialogTitleGroup,` && |\n| &&
             `.${DIALOG_CLASS} .sapMIBar,` && |\n| &&
             `.${DIALOG_CLASS} .sapMDialogFooter,` && |\n| &&
             `.${DIALOG_CLASS} .sapMDialogScrollCont,` && |\n| &&
             `.${DIALOG_CLASS} .sapMBtnInner {` && |\n| &&
             `  border-radius: 0 !important;` && |\n| &&
             `}` && |\n| &&
             `.${MESSAGE_CLASS} {` && |\n| &&
             `  display: block;` && |\n| &&
             `  margin: 0 0 0.5rem 0;` && |\n| &&
             `  padding: 0.5rem 0.75rem;` && |\n| &&
             `  border-left: 0.1875rem solid var(--sapNegativeColor, #bb0000);` && |\n| &&
             `  background: var(--sapErrorBackground, #ffebeb);` && |\n| &&
             `  color: var(--sapTextColor, #32363a);` && |\n| &&
             `  line-height: 1.4;` && |\n| &&
             `  overflow-wrap: anywhere;` && |\n| &&
             `}` && |\n| &&
             `.${MESSAGE_CLASS}:last-of-type {` && |\n| &&
             `  margin-bottom: 0;` && |\n| &&
             `}` && |\n| &&
             `.${HINT_CLASS} {` && |\n| &&
             `  display: block;` && |\n| &&
             `  margin-top: 0.75rem;` && |\n| &&
             `  color: var(--sapContent_LabelColor, #6a6d70);` && |\n| &&
             `  font-size: 0.8125rem;` && |\n| &&
             `}` && |\n| &&
             ```;` && |\n| &&
             `` && |\n| &&
             `  function ensureDialogStyles() {` && |\n| &&
             `    try {` && |\n| &&
             `      if (document.getElementById(STYLE_ID)) return;` && |\n| &&
             `      const head = document.head || document.documentElement;` && |\n| &&
             `      if (!head) return;` && |\n| &&
             `      const style = document.createElement("style");` && |\n| &&
             `      style.id = STYLE_ID;` && |\n| &&
             `      style.textContent = DIALOG_STYLES;` && |\n| &&
             `      head.appendChild(style);` && |\n| &&
             `    } catch {}` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  function withClass(control, className) {` && |\n| &&
             `    if (control && typeof control.addStyleClass === "function") {` && |\n| &&
             `      control.addStyleClass(className);` && |\n| &&
             `    }` && |\n| &&
             `    return control;` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  function createContainer() {` && |\n| &&
             `    document.getElementById("serverErrorContainer")?.remove();` && |\n| &&
             `` && |\n| &&
             `    const container = document.createElement("div");` && |\n| &&
             `    container.id = "serverErrorContainer";` && |\n| &&
             `` && |\n| &&
             `    container.style.cssText = ``` && |\n| &&
             `      position: fixed;` && |\n| &&
             `      top: 50%;` && |\n| &&
             `      left: 50%;` && |\n| &&
             `      transform: translate(-50%, -50%);` && |\n| &&
             `      width: 90%;` && |\n| &&
             `      height: 90%;` && |\n| &&
             `      background: white;` && |\n| &&
             `      border: 1px solid #bb0000;` && |\n| &&
             `      border-radius: 0;` && |\n| &&
             `      box-shadow: 0 0.5rem 1rem rgba(0,0,0,0.25);` && |\n| &&
             `      z-index: 9999;` && |\n| &&
             `      display: flex;` && |\n| &&
             `      flex-direction: column;` && |\n| &&
             `      font-family: "72", "72full", Arial, Helvetica, sans-serif;` && |\n| &&
             `    ``;` && |\n| &&
             `    document.body.appendChild(container);` && |\n| &&
             `    return container;` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  function hasErrorDetails() {` && |\n| &&
             `    return (AppState.state.onErrorDetails || []).length > 0;` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  function openErrorDetails() {` && |\n| &&
             `    for (const fn of AppState.state.onErrorDetails || []) {` && |\n| &&
             `      if (!fn) continue;` && |\n| &&
             `      try {` && |\n| &&
             `        fn();` && |\n| &&
             `      } catch {}` && |\n| &&
             `    }` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  function showFriendlyDialog(title, details, options = {}) {` && |\n| &&
             `    try {` && |\n| &&
             `      const Dialog = sap.ui.require("sap/m/Dialog");` && |\n| &&
             `      const Button = sap.ui.require("sap/m/Button");` && |\n| &&
             `      const Text = sap.ui.require("sap/m/Text");` && |\n| &&
             `      if (!Dialog || !Button || !Text) return false;` && |\n| &&
             `      lastDialogTitle = title;` && |\n| &&
             `      lastDialogDetails = details;` && |\n| &&
             `      lastDialogOptions = options;` && |\n| &&
             `` && |\n| &&
             `      if (friendlyDialog) {` && |\n| &&
             `        friendlyDialog.destroy();` && |\n| &&
             `        friendlyDialog = null;` && |\n| &&
             `      }` && |\n| &&
             `      ensureDialogStyles();` && |\n| &&
             `` && |\n| &&
             `      const message = buildErrorPreview(details) || "An error occurred.";` && |\n| &&
             `` && |\n| &&
             `      const content = message.split("\n").map((line) => {` && |\n| &&
             `        const text = new Text({ text: line });` && |\n| &&
             `` && |\n| &&
             `        if (typeof text.setRenderWhitespace === "function") {` && |\n| &&
             `          text.setRenderWhitespace(true);` && |\n| &&
             `        }` && |\n| &&
             `        return withClass(text, MESSAGE_CLASS);` && |\n| &&
             `      });` && |\n| &&
             `` && |\n| &&
             `      if (String(details || "").trim() !== message) {` && |\n| &&
             `        content.push(` && |\n| &&
             `          withClass(` && |\n| &&
             `            new Text({` && |\n| &&
             `              text: "Choose Details for the full technical information.",` && |\n| &&
             `            }),` && |\n| &&
             `            HINT_CLASS,` && |\n| &&
             `          ),` && |\n| &&
             `        );` && |\n| &&
             `      }` && |\n| &&
             `` && |\n| &&
             `      const restartButton = new Button({` && |\n| &&
             `        text: "Restart",` && |\n| &&
             `        type: "Emphasized",` && |\n| &&
             `        press: () => window.location.reload(),` && |\n| &&
             `      });` && |\n| &&
             `` && |\n| &&
             `      const copyText = ``${title || DEFAULT_TITLE}\n\n${details}``;` && |\n| &&
             `      const copyButton = new Button({` && |\n| &&
             `        text: "Copy",` && |\n| &&
             `        press: () => {` && |\n| &&
             `          copyToClipboard(copyText);` && |\n| &&
             `          copyButton.setText("Copied");` && |\n| &&
             `          setTimeout(() => {` && |\n| &&
             `            if (!copyButton.bIsDestroyed) copyButton.setText("Copy");` && |\n| &&
             `          }, 1500);` && |\n| &&
             `        },` && |\n| &&
             `      });` && |\n| &&
             `` && |\n| &&
             `      const buttons = [];` && |\n| &&
             `` && |\n| &&
             `      if (hasErrorDetails()) {` && |\n| &&
             `        buttons.push(` && |\n| &&
             `          new Button({` && |\n| &&
             `            text: "Details",` && |\n| &&
             `            press: () => {` && |\n| &&
             `              dialog.close();` && |\n| &&
             `              openErrorDetails();` && |\n| &&
             `            },` && |\n| &&
             `          }),` && |\n| &&
             `        );` && |\n| &&
             `      }` && |\n| &&
             `      buttons.push(copyButton);` && |\n| &&
             `      if (typeof options.onRetry === "function") {` && |\n| &&
             `        buttons.push(` && |\n| &&
             `          new Button({` && |\n| &&
             `            text: "Retry",` && |\n| &&
             `            press: () => {` && |\n| &&
             `              dialog.close();` && |\n| &&
             `              options.onRetry();` && |\n| &&
             `            },` && |\n| &&
             `          }),` && |\n| &&
             `        );` && |\n| &&
             `      }` && |\n| &&
             `      buttons.push(restartButton);` && |\n| &&
             `` && |\n| &&
             `      const dialog = new Dialog({` && |\n| &&
             `        title: title || "Application Error",` && |\n| &&
             `        type: "Message",` && |\n| &&
             `        state: "Error",` && |\n| &&
             `        icon: "sap-icon://message-error",` && |\n| &&
             `` && |\n| &&
             `        contentWidth: "36rem",` && |\n| &&
             `` && |\n| &&
             `        escapeHandler: (oPromise) => oPromise.reject(),` && |\n| &&
             `        content,` && |\n| &&
             `        buttons,` && |\n| &&
             `        initialFocus: restartButton,` && |\n| &&
             `        afterClose: () => {` && |\n| &&
             `          if (friendlyDialog === dialog) friendlyDialog = null;` && |\n| &&
             `          dialog.destroy();` && |\n| &&
             `        },` && |\n| &&
             `      });` && |\n| &&
             `      withClass(dialog, DIALOG_CLASS);` && |\n| &&
             `      friendlyDialog = dialog;` && |\n| &&
             `      dialog.open();` && |\n| &&
             `      return true;` && |\n| &&
             `    } catch {` && |\n| &&
             `      return false;` && |\n| &&
             `    }` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  function reopenErrorDialog() {` && |\n| &&
             `    return showFriendlyDialog(` && |\n| &&
             `      lastDialogTitle,` && |\n| &&
             `      lastDialogDetails,` && |\n| &&
             `      lastDialogOptions,` && |\n| &&
             `    );` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  function handleLogout() {` && |\n| &&
             `    const fallback = () => {` && |\n| &&
             `      window.location.href = "/sap/public/bc/icf/logoff";` && |\n| &&
             `    };` && |\n| &&
             `    try {` && |\n| &&
             `      if (AppState.state.oLaunchpad?.Container?.logout) {` && |\n| &&
             `        AppState.state.oLaunchpad.Container.logout();` && |\n| &&
             `      } else {` && |\n| &&
             `        fallback();` && |\n| &&
             `      }` && |\n| &&
             `    } catch {` && |\n| &&
             `      fallback();` && |\n| &&
             `    }` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  function loadFriendlyDialogAsync(title, details, options) {` && |\n| &&
             `    try {` && |\n| &&
             `      const require = sap?.ui?.require;` && |\n| &&
             `      if (typeof require !== "function") return false;` && |\n| &&
             `      require(["sap/m/Dialog", "sap/m/Button", "sap/m/Text"], () => {` && |\n| &&
             `        if (!showFriendlyDialog(title, details, options)) {` && |\n| &&
             `          showRawOverlay(title, details, options);` && |\n| &&
             `        }` && |\n| &&
             `      }, () => showRawOverlay(title, details, options));` && |\n| &&
             `      return true;` && |\n| &&
             `    } catch {` && |\n| &&
             `      return false;` && |\n| &&
             `    }` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  function show(response, title, options = {}) {` && |\n| &&
             `    const stack = response?.stack ? String(response.stack) : "";` && |\n| &&
             `    const message = String(response);` && |\n| &&
             `    const full = stack` && |\n| &&
             `      ? stack.includes(message)` && |\n| &&
             `        ? stack` && |\n| &&
             `        : ``${message}\n${stack}``` && |\n| &&
             `      : message;` && |\n| &&
             `` && |\n| &&
             `    const errorMessage =` && |\n| &&
             `      full.length > ERROR_MAX_LENGTH` && |\n| &&
             `        ? ``${full.slice(0, ERROR_MAX_LENGTH)}\n\n[... truncated after ${ERROR_MAX_LENGTH} characters]``` && |\n| &&
             `        : full;` && |\n| &&
             `` && |\n| &&
             `    AppState.state.lastError = {` && |\n| &&
             `      title: title || DEFAULT_TITLE,` && |\n| &&
             `      text: errorMessage,` && |\n| &&
             `      onRetry: typeof options.onRetry === "function" ? options.onRetry : null,` && |\n| &&
             `    };` && |\n| &&
             `` && |\n| &&
             `    if (showFriendlyDialog(title, errorMessage, options)) return;` && |\n| &&
             `` && |\n| &&
             `    if (loadFriendlyDialogAsync(title, errorMessage, options)) return;` && |\n| &&
             `` && |\n| &&
             `    showRawOverlay(title, errorMessage, options);` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  function showRawOverlay(title, errorMessage, options = {}) {` && |\n| &&
             `    const errorContainer = createContainer();` && |\n| &&
             `` && |\n| &&
             `    errorContainer.setAttribute("role", "alertdialog");` && |\n| &&
             `    errorContainer.setAttribute("aria-modal", "true");` && |\n| &&
             `    errorContainer.setAttribute("aria-labelledby", "serverErrorTitle");` && |\n| &&
             `` && |\n| &&
             `    const headerDiv = document.createElement("div");` && |\n| &&
             `    headerDiv.style.cssText =` && |\n| &&
             `      "padding: 0.75rem 1rem; background: #bb0000; color: white; display: flex; justify-content: space-between; align-items: center; gap: 1rem;";` && |\n| &&
             `` && |\n| &&
             `    const h3 = document.createElement("h3");` && |\n| &&
             `    h3.id = "serverErrorTitle";` && |\n| &&
             `    h3.textContent = title || DEFAULT_TITLE;` && |\n| &&
             `    h3.style.cssText = "margin: 0; font-size: 1rem; font-weight: bold;";` && |\n| &&
             `    headerDiv.appendChild(h3);` && |\n| &&
             `` && |\n| &&
             `    const btnStyle =` && |\n| &&
             `      "padding: 0.375rem 0.875rem; background: white; color: #bb0000; border: 1px solid white; border-radius: 0; cursor: pointer; font: inherit; font-weight: bold; white-space: nowrap;";` && |\n| &&
             `` && |\n| &&
             `    const actionsDiv = document.createElement("div");` && |\n| &&
             `    actionsDiv.style.cssText = "display: flex; gap: 8px;";` && |\n| &&
             `` && |\n| &&
             `    const addAction = (label, onClick) => {` && |\n| &&
             `      const button = document.createElement("button");` && |\n| &&
             `      button.type = "button";` && |\n| &&
             `      button.textContent = label;` && |\n|.
    result = result &&
             `      button.style.cssText = btnStyle;` && |\n| &&
             `      button.addEventListener("click", onClick);` && |\n| &&
             `      actionsDiv.appendChild(button);` && |\n| &&
             `    };` && |\n| &&
             `` && |\n| &&
             `    if (typeof options.onRetry === "function") {` && |\n| &&
             `      addAction("Retry", () => {` && |\n| &&
             `        errorContainer.remove();` && |\n| &&
             `        options.onRetry();` && |\n| &&
             `      });` && |\n| &&
             `    }` && |\n| &&
             `    addAction("Refresh", () => window.location.reload());` && |\n| &&
             `    addAction("Logout", () => handleLogout());` && |\n| &&
             `` && |\n| &&
             `    headerDiv.appendChild(actionsDiv);` && |\n| &&
             `    errorContainer.appendChild(headerDiv);` && |\n| &&
             `` && |\n| &&
             `    const trapButtons = actionsDiv.querySelectorAll("button");` && |\n| &&
             `    const firstTrap = trapButtons[0];` && |\n| &&
             `    const lastTrap = trapButtons[trapButtons.length - 1];` && |\n| &&
             `    errorContainer.addEventListener("keydown", (event) => {` && |\n| &&
             `      if (event.key !== "Tab") return;` && |\n| &&
             `      if (event.shiftKey && document.activeElement === firstTrap) {` && |\n| &&
             `        event.preventDefault();` && |\n| &&
             `        lastTrap.focus();` && |\n| &&
             `      } else if (!event.shiftKey && document.activeElement === lastTrap) {` && |\n| &&
             `        event.preventDefault();` && |\n| &&
             `        firstTrap.focus();` && |\n| &&
             `      }` && |\n| &&
             `    });` && |\n| &&
             `` && |\n| &&
             `    const iframe = document.createElement("iframe");` && |\n| &&
             `    iframe.id = "errorIframe";` && |\n| &&
             `    iframe.style.cssText = "width: 100%; height: 100%; border: none; flex: 1;";` && |\n| &&
             `    iframe.setAttribute("sandbox", "allow-same-origin");` && |\n| &&
             `    errorContainer.appendChild(iframe);` && |\n| &&
             `` && |\n| &&
             `    const createPre = (ownerDocument) => {` && |\n| &&
             `      const pre = ownerDocument.createElement("pre");` && |\n| &&
             `      pre.style.cssText =` && |\n| &&
             `        "margin:0;padding:1rem;font-family:monospace;font-size:0.75rem;line-height:1.5;white-space:pre-wrap;overflow-wrap:anywhere;";` && |\n| &&
             `      pre.textContent = errorMessage;` && |\n| &&
             `      return pre;` && |\n| &&
             `    };` && |\n| &&
             `` && |\n| &&
             `    const contentDocument = iframe.contentDocument;` && |\n| &&
             `    if (contentDocument) {` && |\n| &&
             `      const target = contentDocument.body || contentDocument.documentElement;` && |\n| &&
             `      target.appendChild(createPre(contentDocument));` && |\n| &&
             `    } else {` && |\n| &&
             `      errorContainer.appendChild(createPre(document));` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    if (firstTrap) firstTrap.focus();` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  return { show, handleLogout, reopenErrorDialog };` && |\n| &&
             `});` && |\n| &&
             `` && |\n| &&
              ``.

  ENDMETHOD.

ENDCLASS.
