* =====================================================================
* GENERATED FILE - DO NOT EDIT (AGENTS.md rule 2)
* Source: app/webapp/model/formatter.js
* Embedded frontend resource, generated by tools/app2abap/trans2abap.js.
* Change the source file above and run 'npm run app2abap' to regenerate;
* the check_app2abap CI gate fails any manual edit here.
* =====================================================================
CLASS z2ui5_cl_ui5f_format_js DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CLASS-METHODS get
      RETURNING
        VALUE(result) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS z2ui5_cl_ui5f_format_js IMPLEMENTATION.

  METHOD get.

    result = `sap.ui.define(["sap/ui/core/IconPool"], (IconPool) => {` && |\n| &&
             `  "use strict";` && |\n| &&
             `` && |\n| &&
             `  function parseYmd(d) {` && |\n| &&
             `    return [` && |\n| &&
             `      Number(d.slice(0, 4)),` && |\n| &&
             `      Number(d.slice(4, 6)) - 1,` && |\n| &&
             `      Number(d.slice(6, 8)),` && |\n| &&
             `    ];` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  function isNoAbapDate(d) {` && |\n| &&
             `    const s = String(d);` && |\n| &&
             `    if (!/^\d{8}$/.test(s)) return true;` && |\n| &&
             `` && |\n| &&
             `    return (` && |\n| &&
             `      Number(s.slice(0, 4)) === 0 ||` && |\n| &&
             `      Number(s.slice(4, 6)) === 0 ||` && |\n| &&
             `      Number(s.slice(6, 8)) === 0` && |\n| &&
             `    );` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  return {` && |\n| &&
             `    DateCreateObject(s) {` && |\n| &&
             `      if (!s) return null;` && |\n| &&
             `      return new Date(s);` && |\n| &&
             `    },` && |\n| &&
             `    DateAbapDateToDateObject(d) {` && |\n| &&
             `      if (isNoAbapDate(d)) return null;` && |\n| &&
             `      return new Date(...parseYmd(d));` && |\n| &&
             `    },` && |\n| &&
             `` && |\n| &&
             `    DateAbapDateTimeToDateObject(d, t = "000000") {` && |\n| &&
             `      if (isNoAbapDate(d)) return null;` && |\n| &&
             `      return new Date(` && |\n| &&
             `        ...parseYmd(d),` && |\n| &&
             `        Number(t.slice(0, 2)),` && |\n| &&
             `        Number(t.slice(2, 4)),` && |\n| &&
             `        Number(t.slice(4, 6)),` && |\n| &&
             `      );` && |\n| &&
             `    },` && |\n| &&
             `` && |\n| &&
             `    expandInlineIcons(text) {` && |\n| &&
             `      if (!text) return "";` && |\n| &&
             `      return String(text).replace(` && |\n| &&
             `        /%%icon:(sap-icon:\/\/[^%]+)%%/g,` && |\n| &&
             `        (match, uri) => {` && |\n| &&
             `          const info = IconPool.getIconInfo(uri);` && |\n| &&
             `          if (!info) return "";` && |\n| &&
             `          return ``<span class="sapMMsgStripInlineIcon" style="font-family:'${info.fontFamily}'">${info.content}</span>``;` && |\n| &&
             `        },` && |\n| &&
             `      );` && |\n| &&
             `    },` && |\n| &&
             `  };` && |\n| &&
             `});` && |\n| &&
             `` && |\n| &&
              ``.

  ENDMETHOD.

ENDCLASS.
