* =====================================================================
* GENERATED FILE - DO NOT EDIT (AGENTS.md rule 2)
* Source: app/webapp/core/AppState.js
* Embedded frontend resource, generated by tools/app2abap/trans2abap.js.
* Change the source file above and run 'npm run app2abap' to regenerate;
* the check_app2abap CI gate fails any manual edit here.
* =====================================================================
CLASS z2ui5_cl_ui5f_appstate_js DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CLASS-METHODS get
      RETURNING
        VALUE(result) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS z2ui5_cl_ui5f_appstate_js IMPLEMENTATION.

  METHOD get.

    result = `sap.ui.define([], () => {` && |\n| &&
             `  "use strict";` && |\n| &&
             `` && |\n| &&
             `  function createState() {` && |\n| &&
             `    return {` && |\n| &&
             `      checkLocal: false,` && |\n| &&
             `      endpoint: null,` && |\n| &&
             `      url: null,` && |\n| &&
             `      oConfig: {},` && |\n| &&
             `      ccResourceRoot: null,` && |\n| &&
             `      cccResourceRoot: null,` && |\n| &&
             `      nodePath: null,` && |\n| &&
             `      embedded: false,` && |\n| &&
             `` && |\n| &&
             `      oApp: null,` && |\n| &&
             `      oOwnerComponent: null,` && |\n| &&
             `      oDeviceModel: null,` && |\n| &&
             `      oView: null,` && |\n| &&
             `      oViewNest: null,` && |\n| &&
             `      oViewNest2: null,` && |\n| &&
             `      oViewPopup: null,` && |\n| &&
             `      oViewPopover: null,` && |\n| &&
             `      oController: null,` && |\n| &&
             `      oControllerNest: null,` && |\n| &&
             `      oControllerNest2: null,` && |\n| &&
             `      oControllerPopup: null,` && |\n| &&
             `      oControllerPopover: null,` && |\n| &&
             `      slotXml: {},` && |\n| &&
             `      slotApp: {},` && |\n| &&
             `      oLaunchpad: null,` && |\n| &&
             `` && |\n| &&
             `      mainArrival: "",` && |\n| &&
             `      mainInstance: "",` && |\n| &&
             `      mainTransition: null,` && |\n| &&
             `` && |\n| &&
             `      oBody: null,` && |\n| &&
             `      oResponse: null,` && |\n| &&
             `      renderedApp: null,` && |\n| &&
             `      responseData: null,` && |\n| &&
             `      contextId: null,` && |\n| &&
             `      isBusy: false,` && |\n| &&
             `      oQueuedEvent: null,` && |\n| &&
             `      oSentModel: null,` && |\n| &&
             `      lastRequestBytes: null,` && |\n| &&
             `      lastRoundtripMs: null,` && |\n| &&
             `      lastMainDisplayOptions: null,` && |\n| &&
             `` && |\n| &&
             `      navRouting: false,` && |\n| &&
             `      navMode: null,` && |\n| &&
             `      currentApp: null,` && |\n| &&
             `      currentDraftId: null,` && |\n| &&
             `      navFromHash: false,` && |\n| &&
             `      navDirection: "",` && |\n| &&
             `      hashEvent: null,` && |\n| &&
             `      appHash: "",` && |\n| &&
             `      pendingAppHash: null,` && |\n| &&
             `` && |\n| &&
             `      hashPushCount: 0,` && |\n| &&
             `` && |\n| &&
             `      timers: Object.create(null),` && |\n| &&
             `      shortcuts: Object.create(null),` && |\n| &&
             `      lastScrolled: {},` && |\n| &&
             `      odataClients: new Set(),` && |\n| &&
             `      viewSizeLimits: Object.create(null),` && |\n| &&
             `      treeStates: Object.create(null),` && |\n| &&
             `      lastError: null,` && |\n| &&
             `` && |\n| &&
             `      onBeforeRoundtrip: [],` && |\n| &&
             `      onAfterRoundtrip: [],` && |\n| &&
             `      onAfterRendering: [],` && |\n| &&
             `      onBeforeEventFrontend: [],` && |\n| &&
             `      onErrorDetails: [],` && |\n| &&
             `    };` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  const COMPONENT_FIELDS = new Set([` && |\n| &&
             `    "checkLocal",` && |\n| &&
             `    "endpoint",` && |\n| &&
             `    "url",` && |\n| &&
             `    "oConfig",` && |\n| &&
             `    "ccResourceRoot",` && |\n| &&
             `    "cccResourceRoot",` && |\n| &&
             `    "nodePath",` && |\n| &&
             `    "embedded",` && |\n| &&
             `    "oApp",` && |\n| &&
             `    "oOwnerComponent",` && |\n| &&
             `    "oDeviceModel",` && |\n| &&
             `    "oLaunchpad",` && |\n| &&
             `    "onBeforeRoundtrip",` && |\n| &&
             `    "onAfterRoundtrip",` && |\n| &&
             `    "onAfterRendering",` && |\n| &&
             `    "onBeforeEventFrontend",` && |\n| &&
             `    "onErrorDetails",` && |\n| &&
             `  ]);` && |\n| &&
             `` && |\n| &&
             `  function resetApp(state) {` && |\n| &&
             `    const fresh = createState();` && |\n| &&
             `    for (const key of Object.keys(fresh)) {` && |\n| &&
             `      if (!COMPONENT_FIELDS.has(key)) state[key] = fresh[key];` && |\n| &&
             `    }` && |\n| &&
             `  }` && |\n| &&
             `` && |\n| &&
             `  return { createState, resetApp, COMPONENT_FIELDS };` && |\n| &&
             `});` && |\n| &&
             `` && |\n| &&
              ``.

  ENDMETHOD.

ENDCLASS.
