* =====================================================================
* GENERATED FILE - DO NOT EDIT (AGENTS.md rule 2)
* Source: app/webapp/devtools/Tabs.js
* Embedded frontend resource, generated by tools/app2abap/trans2abap.js.
* Change the source file above and run 'npm run app2abap' to regenerate;
* the check_app2abap CI gate fails any manual edit here.
* =====================================================================
CLASS z2ui5_cl_ui5f_tabs_js DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.

    CLASS-METHODS get
      RETURNING
        VALUE(result) TYPE string.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.


CLASS z2ui5_cl_ui5f_tabs_js IMPLEMENTATION.

  METHOD get.

    result = `// The developer tools' tab registry - ONE table that says what a tab is.` && |\n| &&
             `//` && |\n| &&
             `// Before this module the same fact was written down four times: a source` && |\n| &&
             `// table (jsonSources / xmlSources / textSources), a hand-maintained list` && |\n| &&
             `// of the tabs that had their own branch in renderTab, the scan list of` && |\n| &&
             `// the cross-tab search, and the hand-written section list of the export.` && |\n| &&
             `// They drifted, exactly as that arrangement invites: the search never` && |\n| &&
             `// looked at the Model Diff or the picked control, and the export's` && |\n| &&
             `// section titles ("ROUNDTRIP HISTORY") named tabs that do not exist, so` && |\n| &&
             `// its own truncation hint pointed at nothing.` && |\n| &&
             `//` && |\n| &&
             `// Now every consumer reads this table:` && |\n| &&
             `//` && |\n| &&
             `//   the dialog   which sub-views a group offers, and what to render` && |\n| &&
             `//   the search   every searchable tab, evaluated the way it renders` && |\n| &&
             `//   the export   every exported tab, in exportOrder` && |\n| &&
             `//` && |\n| &&
             `// Adding a tab is one entry here. Nothing else has to be touched.` && |\n| &&
             `//` && |\n| &&
             `// The tab KEYS are a compatibility surface and deliberately unchanged:` && |\n| &&
             `// "?z2ui5-devtools=HISTORY" and the remembered last tab in` && |\n| &&
             `// sessionStorage both store them, and a key that stopped resolving would` && |\n| &&
             `// silently reopen on the default tab. What changed is only how they are` && |\n| &&
             `// GROUPED for display.` && |\n| &&
             `sap.ui.define(` && |\n| &&
             `  [` && |\n| &&
             `    "z2ui5/core/AppState",` && |\n| &&
             `    "z2ui5/core/ViewSlots",` && |\n| &&
             `    "z2ui5/devtools/Format",` && |\n| &&
             `    "z2ui5/devtools/Inspect",` && |\n| &&
             `    "z2ui5/devtools/Picker",` && |\n| &&
             `    "z2ui5/devtools/Recorder",` && |\n| &&
             `  ],` && |\n| &&
             `  (AppState, ViewSlots, Format, Inspect, Picker, Recorder) => {` && |\n| &&
             `    "use strict";` && |\n| &&
             `` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `    // Slot readers - the developer tools' view onto ViewSlots` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `` && |\n| &&
             `    function getModelJson(view) {` && |\n| &&
             `      const model = view?.getModel?.();` && |\n| &&
             `      return model?.getData?.();` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // A model tab is only worth offering when the slot's model carries` && |\n| &&
             `    // DATA - an app without bound attributes serves an empty object, and` && |\n| &&
             `    // omitting the sub-view says "nothing here" more clearly than` && |\n| &&
             `    // rendering {}.` && |\n| &&
             `    function hasModelData(slotKey) {` && |\n| &&
             `      const data = getModelJson(ViewSlots.getView(slotKey));` && |\n| &&
             `      return Boolean(data) && Object.keys(data).length > 0;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function getViewContent(view) {` && |\n| &&
             `      // Private member access (developer tools only): XMLView keeps the raw` && |\n| &&
             `      // XML string as a pseudo property in mProperties, but does not declare` && |\n| &&
             `      // it in its metadata - getProperty("viewContent") therefore throws and` && |\n| &&
             `      // would abort the whole tab selection. Read the plain object instead.` && |\n| &&
             `      return view?.mProperties?.viewContent;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function getRenderedContent(view) {` && |\n| &&
             `      // Private member access (developer tools only): _xContent holds the` && |\n| &&
             `      // view XML after XML templating ran; there is no public equivalent.` && |\n| &&
             `      return view?._xContent?.outerHTML;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // The view XML a slot currently holds: the live view's own viewContent` && |\n| &&
             `    // when UI5 kept it, else the source ViewSlots recorded when the slot was` && |\n| &&
             `    // filled (a fragment or a ``definition``-built view keeps none).` && |\n| &&
             `    //` && |\n| &&
             `    // Read from the SLOT, never from the last response: a slot lives and dies` && |\n| &&
             `    // by ViewSlots.setView/destroy, and both ways of tearing one down end up` && |\n| &&
             `    // there - the backend's ["VIEW_SLOTS","destroy",...] action and the` && |\n| &&
             `    // roundtrip-free frontend close (cs_event-popup_close / popover_close,` && |\n| &&
             `    // which the backend formats as that very same action). Scraping the last` && |\n| &&
             `    // response's display action instead made the frontend close look like a` && |\n| &&
             `    // popup that was still open: no roundtrip happens, so the response that` && |\n| &&
             `    // opened it stayed the current one.` && |\n| &&
             `    function getSlotXml(slotKey) {` && |\n| &&
             `      return (` && |\n| &&
             `        getViewContent(ViewSlots.getView(slotKey)) ||` && |\n| &&
             `        ViewSlots.getViewXml(slotKey) ||` && |\n| &&
             `        ""` && |\n| &&
             `      );` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function slotFilled(slotKey) {` && |\n| &&
             `      return Boolean(getSlotXml(slotKey));` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `    // Groups - the five questions the tools are opened with` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `` && |\n| &&
             `    // A group is a top-level tab. They are ordered the way a session` && |\n| &&
             `    // runs: what is going on, what broke, what went over the wire, what` && |\n| &&
             `    // the screen is made of, what the system underneath looks like.` && |\n| &&
             `    const GROUPS = [` && |\n| &&
             `      { key: "OVERVIEW", label: "Overview" },` && |\n| &&
             `      { key: "PROBLEMS", label: "Problems" },` && |\n| &&
             `      { key: "ROUNDTRIPS", label: "Roundtrips" },` && |\n| &&
             `      { key: "VIEWDATA", label: "View & Data" },` && |\n| &&
             `      { key: "SYSTEM", label: "System" },` && |\n| &&
             `    ];` && |\n| &&
             `` && |\n| &&
             `    const DEFAULT_GROUP = "OVERVIEW";` && |\n| &&
             `` && |\n| &&
             `    // The View & Data group is TWO dimensions - which slot, and which` && |\n| &&
             `    // aspect of it - rather than the eight flat tabs it used to be` && |\n| &&
             `    // (VIEW / MODEL / POPUP / POPUP_MODEL / POPOVER / POPOVER_MODEL /` && |\n| &&
             `    // NEST1 / NEST2, most of them greyed out most of the time). The slot` && |\n| &&
             `    // is picked in one selector, the aspect in another, and only the` && |\n| &&
             `    // combinations that actually exist are offered.` && |\n| &&
             `    const SLOTS = [` && |\n| &&
             `      { key: "MAIN", label: "Main" },` && |\n| &&
             `      { key: "POPUP", label: "Popup" },` && |\n| &&
             `      { key: "POPOVER", label: "Popover" },` && |\n| &&
             `      { key: "NEST", label: "Nested 1" },` && |\n| &&
             `      { key: "NEST2", label: "Nested 2" },` && |\n| &&
             `    ];` && |\n| &&
             `` && |\n| &&
             `    // Aspect order inside a slot: the XML is what the backend sent, the` && |\n| &&
             `    // model is what fills it, the bindings are the check between the two.` && |\n| &&
             `    const ASPECTS = ["XML", "MODEL", "BINDINGS"];` && |\n| &&
             `` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `    // The table` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `` && |\n| &&
             `    // Every entry:` && |\n| &&
             `    //   key          stable identity (URL parameter, remembered last tab)` && |\n| &&
             `    //   group        the top-level tab it appears under` && |\n| &&
             `    //   label        its name in the sub-view selector` && |\n| &&
             `    //   kind         "json" | "xml" | "text" | "source" - how it renders` && |\n| &&
             `    //   produce()    the finished display string` && |\n| &&
             `    //   rendered()   optional: the post-XML-templating variant (xml only)` && |\n| &&
             `    //   enabled()    optional: false hides the sub-view entirely` && |\n| &&
             `    //   slot/aspect  View & Data only - the two selector dimensions` && |\n| &&
             `    //   exportOrder  position in the export; absent = not exported` && |\n| &&
             `    //   exportTitle  section title; defaults to the upper-cased label` && |\n| &&
             `    //   searchable   false keeps a tab out of the cross-tab search` && |\n| &&
             `    const TABS = [` && |\n| &&
             `      // -------- Overview --------` && |\n| &&
             `      {` && |\n| &&
             `        key: "OVERVIEW",` && |\n| &&
             `        group: "OVERVIEW",` && |\n| &&
             `        label: "Overview",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Inspect.formatOverview(),` && |\n| &&
             `        // Not exported and not searched: every line of it is a summary of` && |\n| &&
             `        // a section the export already carries in full.` && |\n| &&
             `        searchable: false,` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      // -------- Problems --------` && |\n| &&
             `      {` && |\n| &&
             `        key: "ERROR",` && |\n| &&
             `        group: "PROBLEMS",` && |\n| &&
             `        label: "Error",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Inspect.formatError(),` && |\n| &&
             `        enabled: () => Boolean(AppState.state.lastError),` && |\n| &&
             `        exportOrder: 20,` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "LOG",` && |\n| &&
             `        group: "PROBLEMS",` && |\n| &&
             `        label: "Log",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Inspect.formatLog(),` && |\n| &&
             `        exportOrder: 30,` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      // -------- Roundtrips --------` && |\n| &&
             `      {` && |\n| &&
             `        key: "HISTORY",` && |\n| &&
             `        group: "ROUNDTRIPS",` && |\n| &&
             `        label: "History",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Recorder.formatHistory(),` && |\n| &&
             `        exportOrder: 40,` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "REQUEST",` && |\n| &&
             `        group: "ROUNDTRIPS",` && |\n| &&
             `        label: "Request",` && |\n| &&
             `        kind: "json",` && |\n| &&
             `        produce: () => Format.toJson(AppState.state.oBody),` && |\n| &&
             `        exportOrder: 80,` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "PLAIN",` && |\n| &&
             `        group: "ROUNDTRIPS",` && |\n| &&
             `        label: "Response",` && |\n| &&
             `        kind: "json",` && |\n| &&
             `        produce: () => Format.toJson(AppState.state.responseData),` && |\n| &&
             `        exportOrder: 70,` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "ACTIONS",` && |\n| &&
             `        group: "ROUNDTRIPS",` && |\n| &&
             `        label: "Actions",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Inspect.formatActions(),` && |\n| &&
             `        exportOrder: 60,` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "DIFF",` && |\n| &&
             `        group: "ROUNDTRIPS",` && |\n| &&
             `        label: "Model Diff",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Recorder.formatModelDiff(),` && |\n| &&
             `        // Only in the export when it says something: without payload` && |\n| &&
             `        // recording it is a one-line "switch it on" notice, and a report` && |\n| &&
             `        // full of those reads as if the tools were broken.` && |\n| &&
             `        exportOrder: 50,` && |\n| &&
             `        inExport: () => Recorder.isRecordingPayloads(),` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "VIEWDIFF",` && |\n| &&
             `        group: "ROUNDTRIPS",` && |\n| &&
             `        label: "View Diff",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Recorder.formatViewDiff(),` && |\n| &&
             `        exportOrder: 51,` && |\n| &&
             `        inExport: () => Recorder.isRecordingPayloads(),` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      // -------- View & Data --------` && |\n| &&
             `      // MAIN` && |\n| &&
             `      {` && |\n| &&
             `        key: "VIEW",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "MAIN",` && |\n| &&
             `        aspect: "XML",` && |\n| &&
             `        label: "XML",` && |\n| &&
             `        kind: "xml",` && |\n| &&
             `        produce: () => Format.prettifyXml(getSlotXml("MAIN")),` && |\n| &&
             `        rendered: () =>` && |\n| &&
             `          Format.prettifyXml(getRenderedContent(ViewSlots.getView("MAIN"))),` && |\n| &&
             `        enabled: () => slotFilled("MAIN"),` && |\n| &&
             `        exportOrder: 90,` && |\n| &&
             `        exportTitle: "VIEW",` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "MODEL",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "MAIN",` && |\n| &&
             `        aspect: "MODEL",` && |\n| &&
             `        label: "Model",` && |\n| &&
             `        kind: "json",` && |\n| &&
             `        produce: () => Format.toJson(getModelJson(ViewSlots.getView("MAIN"))),` && |\n| &&
             `        enabled: () => hasModelData("MAIN"),` && |\n| &&
             `        exportOrder: 91,` && |\n| &&
             `        exportTitle: "VIEW MODEL",` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "BINDINGS",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "MAIN",` && |\n| &&
             `        aspect: "BINDINGS",` && |\n| &&
             `        label: "Bindings",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Inspect.formatBindings("MAIN"),` && |\n| &&
             `        enabled: () => hasModelData("MAIN"),` && |\n| &&
             `        exportOrder: 92,` && |\n| &&
             `        exportTitle: "VIEW BINDINGS",` && |\n| &&
             `      },` && |\n| &&
             `      // POPUP` && |\n| &&
             `      {` && |\n| &&
             `        key: "POPUP",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "POPUP",` && |\n| &&
             `        aspect: "XML",` && |\n| &&
             `        label: "XML",` && |\n| &&
             `        kind: "xml",` && |\n| &&
             `        produce: () => Format.prettifyXml(getSlotXml("POPUP")),` && |\n| &&
             `        enabled: () => slotFilled("POPUP"),` && |\n| &&
             `        exportOrder: 100,` && |\n| &&
             `        // Every slot has a sub-view called "XML", so the export title` && |\n| &&
             `        // has to name the slot - the default (the label) would produce` && |\n| &&
             `        // three sections called "XML".` && |\n| &&
             `        exportTitle: "POPUP",` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "POPUP_MODEL",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "POPUP",` && |\n| &&
             `        aspect: "MODEL",` && |\n| &&
             `        label: "Model",` && |\n| &&
             `        kind: "json",` && |\n| &&
             `        produce: () => Format.toJson(getModelJson(ViewSlots.getView("POPUP"))),` && |\n| &&
             `        enabled: () => hasModelData("POPUP"),` && |\n| &&
             `        exportOrder: 101,` && |\n| &&
             `        exportTitle: "POPUP MODEL",` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "POPUP_BINDINGS",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "POPUP",` && |\n| &&
             `        aspect: "BINDINGS",` && |\n| &&
             `        label: "Bindings",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Inspect.formatBindings("POPUP"),` && |\n| &&
             `        enabled: () => hasModelData("POPUP"),` && |\n| &&
             `        exportOrder: 102,` && |\n| &&
             `        exportTitle: "POPUP BINDINGS",` && |\n| &&
             `      },` && |\n| &&
             `      // POPOVER` && |\n| &&
             `      {` && |\n| &&
             `        key: "POPOVER",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "POPOVER",` && |\n| &&
             `        aspect: "XML",` && |\n| &&
             `        label: "XML",` && |\n| &&
             `        kind: "xml",` && |\n| &&
             `        produce: () => Format.prettifyXml(getSlotXml("POPOVER")),` && |\n| &&
             `        enabled: () => slotFilled("POPOVER"),` && |\n| &&
             `        exportOrder: 110,` && |\n| &&
             `        exportTitle: "POPOVER",` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "POPOVER_MODEL",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "POPOVER",` && |\n| &&
             `        aspect: "MODEL",` && |\n| &&
             `        label: "Model",` && |\n| &&
             `        kind: "json",` && |\n| &&
             `        produce: () =>` && |\n| &&
             `          Format.toJson(getModelJson(ViewSlots.getView("POPOVER"))),` && |\n| &&
             `        enabled: () => hasModelData("POPOVER"),` && |\n| &&
             `        exportOrder: 111,` && |\n| &&
             `        exportTitle: "POPOVER MODEL",` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "POPOVER_BINDINGS",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "POPOVER",` && |\n| &&
             `        aspect: "BINDINGS",` && |\n| &&
             `        label: "Bindings",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Inspect.formatBindings("POPOVER"),` && |\n| &&
             `        enabled: () => hasModelData("POPOVER"),` && |\n| &&
             `        exportOrder: 112,` && |\n| &&
             `        exportTitle: "POPOVER BINDINGS",` && |\n| &&
             `      },` && |\n| &&
             `      // The nested slots carry no model of their own - they inherit` && |\n| &&
             `      // MAIN's by UI5 propagation, so only the XML is an aspect here.` && |\n| &&
             `      {` && |\n| &&
             `        key: "NEST1",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "NEST",` && |\n| &&
             `        aspect: "XML",` && |\n| &&
             `        label: "XML",` && |\n| &&
             `        kind: "xml",` && |\n| &&
             `        produce: () => Format.prettifyXml(getSlotXml("NEST")),` && |\n| &&
             `        rendered: () =>` && |\n| &&
             `          Format.prettifyXml(getRenderedContent(ViewSlots.getView("NEST"))),` && |\n| &&
             `        enabled: () => slotFilled("NEST"),` && |\n| &&
             `        exportOrder: 120,` && |\n| &&
             `        exportTitle: "NEST1",` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "NEST2",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        slot: "NEST2",` && |\n| &&
             `        aspect: "XML",` && |\n| &&
             `        label: "XML",` && |\n| &&
             `        kind: "xml",` && |\n| &&
             `        produce: () => Format.prettifyXml(getSlotXml("NEST2")),` && |\n| &&
             `        rendered: () =>` && |\n| &&
             `          Format.prettifyXml(getRenderedContent(ViewSlots.getView("NEST2"))),` && |\n| &&
             `        enabled: () => slotFilled("NEST2"),` && |\n| &&
             `        exportOrder: 121,` && |\n| &&
             `        exportTitle: "NEST2",` && |\n| &&
             `      },` && |\n| &&
             `      // The picked control belongs to this group - going from a control` && |\n| &&
             `      // on screen to the attribute that feeds it is the same question` && |\n| &&
             `      // the bindings answer from the other end - but it is the one entry` && |\n| &&
             `      // here that is NOT about a slot, so it hides the slot selector.` && |\n| &&
             `      {` && |\n| &&
             `        key: "PICK",` && |\n| &&
             `        group: "VIEWDATA",` && |\n| &&
             `        aspect: "PICK",` && |\n| &&
             `        label: "Picked Control",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () =>` && |\n| &&
             `          Picker.lastReport() ||` && |\n| &&
             `          'No control picked yet - press "Pick Control", then click any' +` && |\n| &&
             `            " control in the app.",` && |\n| &&
             `        searchable: true,` && |\n| &&
             `      },` && |\n| &&
             `` && |\n| &&
             `      // -------- System --------` && |\n| &&
             `      {` && |\n| &&
             `        key: "ENV",` && |\n| &&
             `        group: "SYSTEM",` && |\n| &&
             `        label: "Environment",` && |\n|.
    result = result &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Inspect.formatEnvironment(),` && |\n| &&
             `        // First section of the export on purpose: versions, UI5` && |\n| &&
             `        // distribution, launchpad and device are what a reader of a` && |\n| &&
             `        // shared report needs before anything else, and asking for them` && |\n| &&
             `        // is the standard first reply to a bug report.` && |\n| &&
             `        exportOrder: 10,` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "REGISTRY",` && |\n| &&
             `        group: "SYSTEM",` && |\n| &&
             `        label: "Registry",` && |\n| &&
             `        kind: "text",` && |\n| &&
             `        produce: () => Inspect.formatRegistry(),` && |\n| &&
             `        exportOrder: 61,` && |\n| &&
             `      },` && |\n| &&
             `      {` && |\n| &&
             `        key: "SOURCE",` && |\n| &&
             `        group: "SYSTEM",` && |\n| &&
             `        label: "ABAP Source",` && |\n| &&
             `        // Not the code editor: the ADT endpoint renders the class itself,` && |\n| &&
             `        // framed by the dialog (see devtools/AbapSource.js).` && |\n| &&
             `        kind: "source",` && |\n| &&
             `        produce: () => "",` && |\n| &&
             `        // The class source travels in the export, but it is fetched` && |\n| &&
             `        // asynchronously and passed in - Report.js places it, not this.` && |\n| &&
             `        searchable: false,` && |\n| &&
             `      },` && |\n| &&
             `    ];` && |\n| &&
             `` && |\n| &&
             `    const byKey = new Map(TABS.map((tab) => [tab.key, tab]));` && |\n| &&
             `` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `    // Lookup` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `` && |\n| &&
             `    function get(tabKey) {` && |\n| &&
             `      return byKey.get(tabKey);` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function isKnown(tabKey) {` && |\n| &&
             `      return Boolean(tabKey && byKey.has(tabKey));` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function isEnabled(tab) {` && |\n| &&
             `      if (!tab) return false;` && |\n| &&
             `      try {` && |\n| &&
             `        return tab.enabled ? Boolean(tab.enabled()) : true;` && |\n| &&
             `      } catch {` && |\n| &&
             `        // A source that throws while deciding whether it has anything to` && |\n| &&
             `        // show must not take the whole tab strip with it.` && |\n| &&
             `        return false;` && |\n| &&
             `      }` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function groupOf(tabKey) {` && |\n| &&
             `      return get(tabKey)?.group || DEFAULT_GROUP;` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // The tabs of a group that have something to show right now, in` && |\n| &&
             `    // table order.` && |\n| &&
             `    function enabledTabs(groupKey) {` && |\n| &&
             `      return TABS.filter((tab) => tab.group === groupKey && isEnabled(tab));` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // The tab a group opens on when it is selected without a specific` && |\n| &&
             `    // sub-view - the first one that is enabled.` && |\n| &&
             `    function firstTabOf(groupKey) {` && |\n| &&
             `      const [first] = enabledTabs(groupKey);` && |\n| &&
             `      return first?.key || "";` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // The slots that hold something, in SLOTS order. Drives the slot` && |\n| &&
             `    // selector of View & Data; empty slots are not offered at all.` && |\n| &&
             `    function enabledSlots() {` && |\n| &&
             `      const available = new Set(` && |\n| &&
             `        enabledTabs("VIEWDATA")` && |\n| &&
             `          .filter((tab) => tab.slot)` && |\n| &&
             `          .map((tab) => tab.slot),` && |\n| &&
             `      );` && |\n| &&
             `      return SLOTS.filter((slot) => available.has(slot.key));` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // The aspects available for one slot, in ASPECTS order.` && |\n| &&
             `    function aspectsOfSlot(slotKey) {` && |\n| &&
             `      return enabledTabs("VIEWDATA")` && |\n| &&
             `        .filter((tab) => tab.slot === slotKey)` && |\n| &&
             `        .sort((a, b) => ASPECTS.indexOf(a.aspect) - ASPECTS.indexOf(b.aspect));` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // The tab for a (slot, aspect) pair, falling back to the slot's` && |\n| &&
             `    // first available aspect - switching from Popup/Model to a slot that` && |\n| &&
             `    // has no model must land somewhere rather than nowhere.` && |\n| &&
             `    function tabFor(slotKey, aspect) {` && |\n| &&
             `      const aspects = aspectsOfSlot(slotKey);` && |\n| &&
             `      const exact = aspects.find((tab) => tab.aspect === aspect);` && |\n| &&
             `      return (exact || aspects[0])?.key || "";` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `    // Content` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `` && |\n| &&
             `    // The finished display string of a tab. Guarded: one broken source` && |\n| &&
             `    // may not blank the dialog, and the message says which tab broke.` && |\n| &&
             `    function render(tabKey) {` && |\n| &&
             `      const tab = get(tabKey);` && |\n| &&
             `      if (!tab) return "";` && |\n| &&
             `      try {` && |\n| &&
             `        return tab.produce() ?? "";` && |\n| &&
             `      } catch (e) {` && |\n| &&
             `        return ``(${tab.label} could not be rendered: ${e?.message || e})``;` && |\n| &&
             `      }` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // The post-XML-templating variant, for the tabs that have one.` && |\n| &&
             `    function renderTemplated(tabKey) {` && |\n| &&
             `      const tab = get(tabKey);` && |\n| &&
             `      if (!tab?.rendered) return "";` && |\n| &&
             `      try {` && |\n| &&
             `        return tab.rendered() || "";` && |\n| &&
             `      } catch {` && |\n| &&
             `        return "";` && |\n| &&
             `      }` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // Every tab the cross-tab search looks at. A tab that is disabled` && |\n| &&
             `    // right now holds nothing, so searching it would only cost time.` && |\n| &&
             `    function searchableTabs() {` && |\n| &&
             `      return TABS.filter((tab) => tab.searchable !== false && isEnabled(tab));` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // Every tab the export carries, in exportOrder. ``inExport`` is the` && |\n| &&
             `    // second gate, for content that exists but says nothing worth` && |\n| &&
             `    // shipping (a model diff without payload recording).` && |\n| &&
             `    function exportTabs() {` && |\n| &&
             `      return TABS.filter((tab) => {` && |\n| &&
             `        if (tab.exportOrder === undefined) return false;` && |\n| &&
             `        if (!isEnabled(tab)) return false;` && |\n| &&
             `        try {` && |\n| &&
             `          return tab.inExport ? Boolean(tab.inExport()) : true;` && |\n| &&
             `        } catch {` && |\n| &&
             `          return false;` && |\n| &&
             `        }` && |\n| &&
             `      }).sort((a, b) => a.exportOrder - b.exportOrder);` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    function exportTitle(tab) {` && |\n| &&
             `      return tab.exportTitle || tab.label.toUpperCase();` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `    // Cross-tab search` && |\n| &&
             `    // ------------------------------------------------------------------` && |\n| &&
             `` && |\n| &&
             `    // Hits reported per tab. A term that matches a whole model would` && |\n| &&
             `    // otherwise bury the tabs that matched it once.` && |\n| &&
             `    const MAX_HITS_PER_TAB = 20;` && |\n| &&
             `` && |\n| &&
             `    // The name a hit is reported under. A View & Data tab needs its slot` && |\n| &&
             `    // to be identifiable at all - three slots have a sub-view called` && |\n| &&
             `    // "XML", and "[XML] 4 hits" would say nothing about where to look.` && |\n| &&
             `    function searchLabel(tab) {` && |\n| &&
             `      const group = GROUPS.find((entry) => entry.key === tab.group);` && |\n| &&
             `      const slot = SLOTS.find((entry) => entry.key === tab.slot);` && |\n| &&
             `      const parts = [group?.label || tab.group];` && |\n| &&
             `      if (slot) parts.push(slot.label);` && |\n| &&
             `      parts.push(tab.label);` && |\n| &&
             `      return parts.join(" > ");` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    // Search every tab at once and report which of them contain the term.` && |\n| &&
             `    // With more than twenty views, "where does CUSTOMER appear?" is a` && |\n| &&
             `    // question the dialog could not answer at all - the developer had to` && |\n| &&
             `    // open each one and use the editor's own find.` && |\n| &&
             `    //` && |\n| &&
             `    // Tabs.render is guarded per tab, so one throwing source can never` && |\n| &&
             `    // blank the whole result.` && |\n| &&
             `    function search(term) {` && |\n| &&
             `      const needle = String(term || "").toLowerCase();` && |\n| &&
             `      if (!needle) return "(enter a search term)";` && |\n| &&
             `      const sections = [];` && |\n| &&
             `      let totalHits = 0;` && |\n| &&
             `` && |\n| &&
             `      for (const tab of searchableTabs()) {` && |\n| &&
             `        const text = render(tab.key);` && |\n| &&
             `        if (!text) continue;` && |\n| &&
             `        const lines = String(text).split("\n");` && |\n| &&
             `        const hits = [];` && |\n| &&
             `        for (let i = 0; i < lines.length; i += 1) {` && |\n| &&
             `          if (!lines[i].toLowerCase().includes(needle)) continue;` && |\n| &&
             `          hits.push(``    ${String(i + 1).padStart(5)}: ${lines[i].trim()}``);` && |\n| &&
             `          if (hits.length >= MAX_HITS_PER_TAB) break;` && |\n| &&
             `        }` && |\n| &&
             `        if (!hits.length) continue;` && |\n| &&
             `        totalHits += hits.length;` && |\n| &&
             `        sections.push(` && |\n| &&
             `          ``  [${searchLabel(tab)}]  ${hits.length}`` +` && |\n| &&
             `            ``${hits.length >= MAX_HITS_PER_TAB ? "+" : ""} hit(s)``,` && |\n| &&
             `        );` && |\n| &&
             `        sections.push(...hits);` && |\n| &&
             `        sections.push("");` && |\n| &&
             `      }` && |\n| &&
             `` && |\n| &&
             `      const head = [` && |\n| &&
             `        ``Search for "${term}" across every tab``,` && |\n| &&
             `        "",` && |\n| &&
             `        totalHits` && |\n| &&
             `          ? ``${totalHits} hit(s) - the tab is named in brackets.``` && |\n| &&
             `          : "(no hit in any tab)",` && |\n| &&
             `        "",` && |\n| &&
             `      ];` && |\n| &&
             `      return head.concat(sections).join("\n");` && |\n| &&
             `    }` && |\n| &&
             `` && |\n| &&
             `    return {` && |\n| &&
             `      GROUPS,` && |\n| &&
             `      SLOTS,` && |\n| &&
             `      ASPECTS,` && |\n| &&
             `      DEFAULT_GROUP,` && |\n| &&
             `      get,` && |\n| &&
             `      isKnown,` && |\n| &&
             `      isEnabled,` && |\n| &&
             `      groupOf,` && |\n| &&
             `      enabledTabs,` && |\n| &&
             `      firstTabOf,` && |\n| &&
             `      enabledSlots,` && |\n| &&
             `      aspectsOfSlot,` && |\n| &&
             `      tabFor,` && |\n| &&
             `      render,` && |\n| &&
             `      renderTemplated,` && |\n| &&
             `      search,` && |\n| &&
             `      searchableTabs,` && |\n| &&
             `      exportTabs,` && |\n| &&
             `      exportTitle,` && |\n| &&
             `      // exposed for the unit specs` && |\n| &&
             `      _internals: { TABS, getSlotXml, hasModelData, searchLabel },` && |\n| &&
             `    };` && |\n| &&
             `  },` && |\n| &&
             `);` && |\n| &&
             `` && |\n| &&
              ``.

  ENDMETHOD.

ENDCLASS.
