name: ABAP_STANDARD

on:
  pull_request:

concurrency:
  group: ABAP_STANDARD-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  ABAP_STANDARD:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-node@v6
      with:
        node-version: '22'
        cache: 'npm'
    - run: npm ci
    - run: npx abaplint .github/abaplint/abap_standard.jsonc
