name: auto_downport

on:
  push:
    branches: [main]

jobs:
  auto_downport:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - run: npm ci
    - run: npm run auto_downport

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git diff --staged --quiet || git commit -m "Downport changes"
        git checkout -b 702
        git push --force origin HEAD:702
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
