name: auto_downport

on:
  push:
    branches: [main]

concurrency:
  group: auto_downport

permissions:
  contents: read

jobs:
  auto_downport:
    if: github.repository == 'abap2UI5/abap2UI5'
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout Repository
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Set up Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: '22'
        cache: 'npm'

    - run: npm ci
    - run: npm run auto_downport

    - name: Commit and Push Changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add .
        git diff --staged --quiet || git commit -m "Downport changes"
        git checkout -b 702
        git push --force origin HEAD:702
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
