name: check_frontend

on:
  pull_request:

concurrency:
  group: check_frontend-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check_frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    defaults:
      run:
        working-directory: ./app
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: app/package-lock.json
      - run: npm ci
      - name: ESLint
        run: npm run lint
