name: check_frontend

on:
  pull_request:

concurrency:
  group: check_frontend-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check_frontend:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Prettier format check
        run: npm run format:check
      - name: ESLint
        run: npm run lint
