name: create_app2abap

on:
  push:
    branches: [main]

concurrency:
  group: create_app2abap

permissions:
  contents: read

jobs:
  create_app2abap:
    if: github.repository == 'abap2UI5/abap2UI5'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: ./.github/actions/setup
        with:
          app-npm-ci: "true"
          npm-ci: "true"

      - name: run transformation
        run: npm run app2abap

      - name: Open PR
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          title: auto-app2abap
          branch: auto-app2abap
