name: create_app2abap

on:
  push:
    branches: [main]

concurrency:
  group: create_app2abap

permissions:
  contents: read

jobs:
  create_app2abap:
    if: github.repository == 'abap2UI5/abap2UI5'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: 'npm'

      - name: run transformation
        run: |
          npm ci
          npm --prefix app ci
          npm run app2abap

      - name: Open PR
        uses: peter-evans/create-pull-request@v8.1.1
        with:
          title: auto-app2abap
          branch: auto-app2abap
