name: mirror_srtti

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 1 * *'

permissions:
  contents: read

jobs:
  mirror_srtti:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    uses: ./.github/workflows/mirror.yaml
    with:
      mirror_repo: srtti_mirror
      target_path: src/00/02
      pr_branch: mirror-srtti-update
