name: mirror_ajson

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * 1'

permissions:
  contents: read

jobs:
  mirror_ajson:
    # Origin repo only
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    if: github.repository == 'abap2UI5/abap2UI5'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - name: run
      run: |
        git clone https://github.com/abap2UI5/ajson_mirror.git
        ls -l
        rm src/00/01/z*
        cp ajson_mirror/src/z* src/00/01/
        rm -rf ajson_mirror
        git status
    - name: Open PR
      uses: peter-evans/create-pull-request@v4
      with:
        title: mirror-ajson-update
        branch: mirror-ajson-update
