name: mirror_ajson

on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 1 * *'

permissions:
  contents: read

jobs:
  mirror_ajson:
    permissions:
      contents: write
      pull-requests: write
      issues: write
    uses: ./.github/workflows/mirror.yaml
    with:
      mirror_repo: ajson_mirror
      target_path: src/00/01
      pr_branch: mirror-ajson-update
