name: test_unit

on:
  pull_request:

concurrency:
  group: test_unit-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test_unit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: ./.github/actions/setup
      with:
        npm-ci: "true"
    - run: npm run downport
    - run: npm run auto_transpile
    - run: npm run unit
