name: test_unit

on:
  pull_request:

concurrency:
  group: test_unit-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  test_unit:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
    - uses: ./.github/actions/setup
      with:
        npm-ci: "true"
    - run: npm run downport
    - run: npm run auto_transpile
    - run: npm run unit
